### ISSUE TITLE
I am absolutely hyped af to play this great and long awaited mod, but it seems to crash with my modpack, hope its a simple mod incompatability or smthn

### ISSUE THREAD

**Issue by SilverMantis** [AlexModGuy/AlexsCaves#1]
as the title said, I'd really appriciate some help wit this!

[crash_report_alec_cav.txt](https://github.com/AlexModGuy/AlexsCaves/files/13039658/crash_report_alec_cav.txt)

**Comment by AlexModGuy** [comment]
try without optifine/rubidium

**Comment by Gbergz** [comment]
Nevermind? It might be a conflict with Citadel or AlexsCaves.
Issue: `https://github.com/dima-dencep/rubidium-extra/issues/60`

**Comment by SilverMantis** [comment]
just tried my modpack without rubidium extras, and it worked, the game doesen't crash anymore

Thanks!
