### ISSUE TITLE
Error code 1, not having any other mods installed than Citadel

### ISSUE THREAD

**Issue by javex412** [AlexModGuy/AlexsCaves#100]

**Comment by mrbadperson** [comment]
The mod requires Citadel, If you did not have any other mod installed, Then there's your problem.

**Comment by javex412** [comment]
Doesn't it comes with the mod itself? 
And im pretty sure I have it already
![a](https://github.com/AlexModGuy/AlexsCaves/assets/49798987/bdd0eea9-b565-4930-b895-c57280cddcfd)

**Comment by javex412** [comment]
I have the crash repport if it helps
[hs_err_pid30088.log](https://github.com/AlexModGuy/AlexsCaves/files/13048329/hs_err_pid30088.log)

**Comment by AlexModGuy** [comment]
increase memory, use latest forge
