### ISSUE TITLE
[1.20.1] Disable nature's compass breaking feature

### ISSUE THREAD

**Issue by SigmaFlame** [AlexModGuy/AlexsCaves#1003]
Hello,

I would like to ask if there is a way to disable the nature's compass breaking feature?
The normal way to find your biomes is not working on our server since we use a lot of world generator worlds.
At this moment, the only way to find your biomes is the command /locate.
I need a way to allow my survival players to find your biomes.

Thanks you in advance.

**Comment by JustAnotherBugReporter** [comment]
find cabins, translate tablets, and make maps, thats how you actually locate them

**Comment by HallucigeniaGaming** [comment]
Git gud

**Comment by PlummetStudios** [comment]
There is a tag you can datapack
