### ISSUE TITLE
CRITICAL BUG-Server lags almost to death 

### ISSUE THREAD

**Issue by PydingAbsorber** [AlexModGuy/AlexsCaves#1005]
When any player teleports randomly in any world, it takes 15-20 seconds to load instead of 3-4, server just freezes for this time and it's only with your's mod 100%. On the server with barely 5-6 players it's already impossible to play, cause it's lagging to death! Your mod adds so much stuff and fun, but it's not playable on server at all. For now I must remove it, but I hope very much for fix...

**Comment by AlexModGuy** [comment]
what do you mean teleports randomly

**Comment by AlexModGuy** [comment]
dupe #1079
