### ISSUE TITLE
Bernsol Blocks light and Visual Issue.

### ISSUE THREAD

**Issue by KombyTiger** [AlexModGuy/AlexsCaves#1035]
I recommend turning off the Bernsol Blocks Lights as they are buggy and look ugly. Some lights at far only appear on the screen and its really annoying.
![2024-04-08_12 02 54](https://github.com/AlexModGuy/AlexsCaves/assets/166385463/3f97f862-c0e9-4d7d-a3be-d4c0fb4fa1e7)

**Comment by JustAnotherBugReporter** [comment]
Shader issue.
