### ISSUE TITLE
Server crash when the desolate dagger is used to hit an entity.

### ISSUE THREAD

**Issue by CtrlAnt** [AlexModGuy/AlexsCaves#1050]
Error : java.lang.ClassCastException: class com.github.alexmodguy.alexscaves.server.entity.item.DesolateDaggerEntity cannot be cast to class net.minecraft.world.entity.LivingEntity (com.github.alexmodguy.alexscaves.server.entity.item.DesolateDaggerEntity is in module alexscaves@1.1.4 of loader 'TRANSFORMER' @1c2dd89b; net.minecraft.world.entity.LivingEntity is in module minecraft@1.20.1 of loader 'TRANSFORMER' @1c2dd89b)

Here is the complete crash report : https://pastebin.com/wQxGhxrh

**Comment by AlexModGuy** [comment]
> at com.teamdurt.netherdungeons.event.NDEventsHandler.applyVampirismEffect(NDEventsHandler.java:22) ~[netherdungeons-1.1.0-alpha2.jar%23444!/:1.1.0-alpha2] {re:classloading}

netherdungeons needs to check if an entity belongs to LivingEntity before casting it to that. report this to their bug tracker.
