### ISSUE TITLE
Some Structures spawn in walls

### ISSUE THREAD

**Issue by Jasdernn** [AlexModGuy/AlexsCaves#106]
I saw it with an Abyssal Chasm structure, but I don't got a picture of it. But I got a picture of an Underzealot house is the side of a cave.
![2023-10-19_19 14 35](https://github.com/AlexModGuy/AlexsCaves/assets/148498785/44c8cdc9-cd8f-40f3-bee5-e9a1bbc310b0)

**Comment by Jasdernn** [comment]
Update: Found it
![2023-10-19_21 39 57](https://github.com/AlexModGuy/AlexsCaves/assets/148498785/580c3798-157b-4c00-afc3-2cbe4c1adc15)

**Comment by ChrisLTheNerd** [comment]
Using Alex's Caves 1.0.4 and I can confirm.
![2023-10-21_21 56 55](https://github.com/AlexModGuy/AlexsCaves/assets/50182206/5835105a-c55a-4f1e-8ad9-99318aaf726a)
