### ISSUE TITLE
[Suggestion] Buff Galena gauntlet magnet damage when using anvils

### ISSUE THREAD

**Issue by ChrisJacobs2** [AlexModGuy/AlexsCaves#1062]
Currently, the gauntlet does half a heart of damage when using it to sling around heavy blocks. I think it would be more fun if the anvil did more damage.

**Comment by MHImoment** [comment]
Wait huh? they can be used with blocks? I thought the point of gauntlet is that theyre for weapon or tools only? or maybe blocks being used is unintentional/bug??

**Comment by ChrisJacobs2** [comment]
I think it is intentional. It works with iron ingots and diamonds (if you have the enchantment for it) as well, but they only do half a heart of damage. Consider also that the magnetron enemies will lift and use metal blocks as well, including anvils.

**Comment by MHImoment** [comment]
Maybe you can ask on the server if non iron netherite weapon is intentional to be used or not.Or check wiki or the book so its all clear.Since pretty sure gauntlet are meant to bw a weapon based on teletor abilities, not magnetron

**Comment by ChrisJacobs2** [comment]
Whether or not it is intended can be determined by checking the code. Looking at the code, two JSON files are used to see if the gauntlet can move an item:

**Named MAGNETIC_ITEMS in the tag registry**
[src/main/resources/data/alexscaves/tags/items/ferromagnetic_items.json](https://github.com/AlexModGuy/AlexsCaves/blob/2e8fc8b4fab4502ec4dd558dfcc467abd74953bd/src/main/resources/data/alexscaves/tags/items/ferromagnetic_items.json) 

**Named GALENA_GAUNTLET_CRYSTALLIZATION_ITEMS in the tag registry**
[src/main/resources/data/alexscaves/tags/items/galena_gauntlet_crystallization_items.json](https://github.com/AlexModGuy/AlexsCaves/blob/2e8fc8b4fab4502ec4dd558dfcc467abd74953bd/src/main/resources/data/alexscaves/tags/items/galena_gauntlet_crystallization_items.json) 

**They are referenced in GalenaGauntletItem.java.**
[src/main/java/com/github/alexmodguy/alexscaves/server/item/GalenaGauntletItem.java](https://github.com/AlexModGuy/AlexsCaves/blob/2e8fc8b4fab4502ec4dd558dfcc467abd74953bd/src/main/java/com/github/alexmodguy/alexscaves/server/item/GalenaGauntletItem.java#L38)

As you can see, both anvils and diamonds are listed here. Iron blocks and raw iron blocks are also listed. It is pretty evident by what the author put in those lists, that this is intended behavior. This is also reflected in the book.
