### ISSUE TITLE
[Suggestion] Galena gauntlet mechanic enhancements

### ISSUE THREAD

**Issue by ThePiekar** [AlexModGuy/AlexsCaves#1076]
In order to make this very cool mechanic mesh more seamlessly into modpacks, i'd like to see the gauntlet use a configurable whitelist of items it can interact with (it's a little jarring when metal/diamond-like tools from different mods don't work with it).
(I'm aware it is technically achievable by tags, however a config on top of that would greatly reduce the level of entry for adjustments)

On top of that maybe allow it to be inserted into the hands curio slot. In that configuration it would work exactly the same, except not being in the offhand slot.

**Comment by PlummetStudios** [comment]
Tags are more sufficient for modpacks as they allow individual mods to add their items by default. 

Curio support is not planned.
