### ISSUE TITLE
Terrible chunks / world generation after installing Alex's Caves

### ISSUE THREAD

**Issue by ElenaNya** [AlexModGuy/AlexsCaves#1079]
Minecraft: 1.20.1
Forge: 47.2.30

Spectator mode at full speed.

Before:
![image](https://github.com/AlexModGuy/AlexsCaves/assets/94359925/a80ae1ba-9e4d-49c2-afd4-f8b55bb3e7a5)

After:
![image](https://github.com/AlexModGuy/AlexsCaves/assets/94359925/f26b502f-d2cc-4e8b-bcf8-22d56a0ebd96)

In general, it is quite logical that the generation mod slows chunks down, but it is too much, plus it seems to affect and chunks in which there is nothing from Alex's Caves?

**Comment by LucaBarbaLata** [comment]
i also have this issue. but this time it lowers my server's tps.

**Comment by Vikthos** [comment]
I have the same issue :(
