### ISSUE TITLE
Flickering When Using NostalgiaTweaks (default settings)

### ISSUE THREAD

**Issue by ProjIss** [AlexModGuy/AlexsCaves#109]
Render fog and blocks at the edge of render distance flicker in and out of view when using NostalgiaTweak's Base configuration, as well as all other configurations it would seem.
Steps to reproduce:

- Boot a standard 47.2.0 instance of forge
- Install NostalgiaTweaks
- Install Alex's Caves
- Load into world

**Comment by ProjIss** [comment]
Flashing Lights Warning for any photosensitive viewers:
https://youtu.be/wAESpESGmqw

**Comment by AlexModGuy** [comment]
disable biome_sky_fog_overrides in the config. Options like this exist because of possible mod conflicts.

**Comment by ProjIss** [comment]
Love me weirdly passive aggressive minecraft mod devs.

**Comment by Cheaterpaul** [comment]
I do not really see how the `nearness` here
https://github.com/AlexModGuy/AlexsCaves/blob/849fe576c180606ee78896ca712c50ca1b1aa3dc/src/main/java/com/github/alexmodguy/alexscaves/client/event/ClientEvents.java#L598

will ever be equal 1.0 with all the calculations done in the BiomeSampler. I am constantly getting values like 1.00000001 or 0.99999999. Apparently this check does only work reliable when no other mod uses fog.
