### ISSUE TITLE
Primordial Caves spawned in the Nether

### ISSUE THREAD

**Issue by vulturesalesman** [AlexModGuy/AlexsCaves#1090]
Somehow I got a Primordial Caves spawn in the Nether. It's small, but there??

![javaw_00Ak2ezdH8](https://github.com/AlexModGuy/AlexsCaves/assets/170268771/14625c27-9580-40f2-80f3-df59fa9ae364)
![javaw_TTZcVXIcrb](https://github.com/AlexModGuy/AlexsCaves/assets/170268771/76c0444e-b308-4141-a406-be222861fc25)

**Comment by PlummetStudios** [comment]
Mod Conflict
