### ISSUE TITLE
Could we do something about this? (Rapid spawnrate of Quark mobs)

### ISSUE THREAD

**Issue by SlytherTheUndertaker** [AlexModGuy/AlexsCaves#1093]
Aside from the weird lava generation, floating cave pillars, etc. (which I'm unsure if that also should be fixed), there are tons of Oretoises and Stonelings from the Quark mod spawning in the Primordial biome, and they look out of character with what the Primordial caves are supposed to be (and potentially other caves).
![2024-06-03_17 08 40](https://github.com/AlexModGuy/AlexsCaves/assets/109980632/0fc4c786-d6eb-4ab8-a1ca-c8cd5c6092d1)

**Comment by SlytherTheUndertaker** [comment]
On a different side note: The golden frogs, when picked up with a bucket, just turns them into regular frogs.

**Comment by AlexModGuy** [comment]
remove Tiny Alex's Caves Tweaks

**Comment by SlytherTheUndertaker** [comment]
> remove Tiny Alex's Caves Tweaks

I didn't have that mod installed. It was just Quark and Alex's Caves that I have.
