### ISSUE TITLE
Ticking Entity Crash when Luxtructosaurus uses its Meteor attack

### ISSUE THREAD

**Issue by SPYROHAWK** [AlexModGuy/AlexsCaves#1094]
As the title says, I get a Ticking Entity crash when the Lux uses it's Meteor attack. I think specifically when the Meteor hits the ground? Unsure. The Ticking Entity issue persists in the world, causing the crash upon trying to load the world, effectively corrupting the world. I'm using the latest version for Forge 1.20.1 and the latest version of Alex's Caves.

EDIT: I am seeing something about "noBreak2" in the crash. It may be worth mentioning that, at least in this most recent instance, I had gamerule doMobGriefing to false. I forget about other instances. I also know that in all instances I can remember I was in creative and the Lux was fighting another mob (Tremorzilla in this most recent case). But I highly doubt this issue cares about the player being in survival or what the Lux is fighting.

Here is a log example for trying to join the world after the crash:

[latest.log](https://github.com/user-attachments/files/15540843/latest.log)

Here is the associated crash report:

[crash-2024-06-03_19.40.35-server.txt](https://github.com/user-attachments/files/15540850/crash-2024-06-03_19.40.35-server.txt)

And here is my modlist:

`[1.20.1]illusion_onslaught-1.0.0.jar
[v1.3.2]-Cam's-Better-Lights.jar
aieaustraps.1.0.1.jar
alex_cave_addon-1.0.0-1.20.1.jar
Alex's Mobs Music Mod 1.20.1.jar
alexs_caves_plus-1.0.1.jar
alexscaves_adventure-1.0.1-forge-1.20.1.jar
alexscaves_torpedoes-1.0.2.jar
alexscaves-1.1.4.jar
alexscavestrimmed-1.0.2.jar
alexsmobs-1.22.8.jar
alexsmobsinteraction-2.0.jar
amendments-1.20-1.1.11.jar
anthropophagy-1.20-4.jar
appleskin-forge-mc1.20.1-2.5.1.jar
ArchaeologyBanners-Forge-1.20.1-5.1.4.jar
architectury-9.2.14-forge.jar
armored_redstone-1.20.1-0.4.0.jar
arthropocolypse-1.0.0.jar
astikorcarts-redux-1.20.1-1.1.7.jar
automobility-0.4.2+1.20.1-forge.jar
azurelib-neo-1.20.1-2.0.20.jar
BadOptimizations-2.1.0.jar
badpackets-forge-0.4.3.jar
bagofyurting-1.20.1-4.0.0.1.jar
batsgalore-forge-1.20.1-1.2.0.jar
BetterAdvancements-1.20.1-0.3.2.162.jar
betterarcheology-1.1.7-1.20.1.jar
bettercombat-forge-1.8.4+1.20.1.jar
BetterTridents-v8.0.1-1.20.1-Forge.jar
biomancy-forge-1.20.1-2.4.4.0.jar
biomemakeover-FORGE-1.20.1-1.11.4.jar
blocky_siege-6.1.92-1.20.1.jar
bloodmagic-1.20.1-3.3.2-44.jar
blossom.jar
Bookshelf-Forge-1.20.1-20.1.10.jar
born_in_chaos_[Forge]1.20.1_1.2.jar
Bountiful-6.0.3+1.20.1-forge.jar
BugFixes2.jar
build_your_campfire-1.0.0-1.20.1.jar
butcher-1.7.jar
caelus-forge-3.1.0+1.20.jar
camps_castles_carriages-1.1.1.jar
cannibal-1.0.5-1.20.1.jar
celestisynth-1.20.1-1.2.2.jar
chalk-1.20.1-1.6.3.jar
chat_heads-0.10.32-forge-1.20.jar
Choup's_Drakvyrn_Mod_for_1.20.1_(v2.2.0).jar
citadel-2.5.4-1.20.1.jar
cleanswing-1.20-1.5.jar
cloth-config-11.1.118-forge.jar
Clumps-forge-1.20.1-12.0.0.3.jar
clutter-1.20-0.5.7.jar
collective-1.20.1-7.40.jar
Connectible Chains-forge-1.20.1-1.0.0.jar
Connector-1.0.0-beta.39+1.20.1.jar
ConnectorExtras-1.10.0+1.20.1.jar
Controlling-forge-1.20.1-12.0.2.jar
Copperative 1.20.1--1.1.0.jar
coroutil-forge-1.20.1-1.3.7.jar
corpse-forge-1.20.1-1.0.12.jar
corundumguardian-2.1.2.jar
cosmeticarmorreworked-1.20.1-v1a.jar
Cozy_home-3.0.2-1.20.1.jar
create_connected-0.7.4-mc1.20.1-all.jar
create_oppenheimered-1.20.1-1.0.2.jar
create_strutures_arise-132.4.2.lib-forge-1.20.1.jar
create-1.20.1-0.5.1.f.jar
Create-Guardian-Beam-Defense-1.3.0b-1.20.1.jar
create-stuff-additions1.20.1_v2.0.4a.jar
createaddition-1.20.1-1.2.3.jar
createbigcannons-forge-1.20.1-0.5.3.b.jar
createdieselgenerators-1.20.1-1.2h.jar
createloveandwar-0.1-1.20.1.jar
creature_compendium-1.2.1.jar
cristellib-1.1.5-forge.jar
CthulhuFishingPort_1.20.1_v.1.3.0_beta.jar
CullLessLeaves-Reforged-1.20.1-1.0.5.jar
curios-forge-5.7.2+1.20.1.jar
curious_armor_stands-1.20-5.0.1.jar
CyclopsCore-1.20.1-1.19.0.jar
dark-waters-connector-1.20.1-0.0.22.jar
darkness-forge-1.20.1-2.0.103-fork.jar
Deep Dark Regrowth 1.2.5.0 - 1.20.1.jar
deeperdarker-forge-1.20.1-1.2.1.jar
DistantWorlds-Reborn-1.20.1-v1.1.0-Beta.jar
DistractingTrims-Forge-1.20.1-2.0.3.jar
dmnr-3.1.8.jar
drinkbeer-refill-1.20.1-1.0.4.jar
dummmmmmy-1.20-1.8.14.jar
DungeonsArise-1.20.x-2.1.58-release.jar
dynamic-fps-3.4.2+minecraft-1.20.4-forge.jar
dynamiclightsreforged-1.20.1_v1.6.0.jar
ecologics-forge-1.20.1-2.2.0.jar
eidolon_repraised-1.20.1-0.3.8.8b.jar
Eldritch_End-FORGE-MC1.20.1-0.2.31.jar
elytratrims-forge-2.1.2+1.20.1.jar
embeddium-0.3.9+mc1.20.1.jar
embeddiumplus-1.20.1-v1.2.5.jar
emi_loot-0.6.5+1.20.1+forge.jar
emi-1.1.4+1.20.1+forge.jar
emiffect-forge-1.1.2+mc1.20.1.jar
emitrades-forge-1.2.1+mc1.20.1.jar
enchantsmith-forge-1.0.4-1.20.jar
entropy-1.0.6.jar
EvilCraft-1.20.1-1.2.37.jar
expanded_ecosphere-3.2.4-forge.jar
explosivepitcherpods-1.20.1-1.0.jar
exposure-1.20.1-1.4.1-forge.jar
fabric-api-0.92.0+1.11.3+1.20.1.jar
FastFurnace-1.20.1-8.0.2.jar
FastLeafDecay-31.jar
Fastload-Reforged-mc1.20.1-3.4.0.jar
FastSuite-1.20.1-5.0.1.jar
FastWorkbench-1.20.1-8.0.4.jar
ferritecore-6.0.1-forge.jar
fire_extinguisher-forge-1.20.1-6.3.0.jar
firearrows-1.20.1-11-forge.jar
FireSticks+V.1.2+[1.20.1].jar
flansmod-1.20.1-0.4.168.jar
fnc-1.2.5.jar
forbidden_arcanus-1.20.1-2.2.6.jar
forgottenrecipes-forge-1.20-1.2.0.jar
FPS_Increaser_Forge.jar
from-another-world-1.2A.1-forge.jar
FromAnotherLibrary-forge-1.20.1-1.0.2.jar
gardens-of-the-dead-forge-4.0.1.jar
geckolib-forge-1.20.1-4.4.4.jar
giacomos_automatable_cauldrons-1.20.1-1.0.6.jar
glowroot1.0.5.jar
gnumus_settlement_[Forge]1.20.1_v1.0.jar
goated-1.20-1.3.4.jar
goblins_tyranny-1.0.1.jar
goety-2.5.16.0.jar
GoodEnding-1.20.1-1.0.1-Forge.jar
guardvillagers-1.20.1-1.6.4.jar
harvestwithease-1.20.1-8.0.1.0-forge.jar
hauntedharvest-1.20-3.1.19.jar
healingcampfire-1.20.1-5.3.jar
herbology-1.1.1.jar
hexxitgear_r-forge1.20.1-1.1.jar
HopoBetterRuinedPortals-[1.20-1.20.2]-1.3.7.jar
HWGMod-connector-1.20.1-2.0.1.jar
illagerrevolutionmod-1.4.jar
ImmediatelyFast-Forge-1.2.11+1.20.4.jar
immersive_aircraft-1.0.1+1.20.1-forge.jar
immersive_armors-1.6.1+1.20.1-forge.jar
ImmersiveEngineering-1.20.1-10.0.0-169.jar
incontrol-1.20-9.2.2.jar
invhud.forge.1.20.1-3.4.18.jar
ironchests-5.0.2-forge.jar
jearchaeology-1.20.1-1.0.3.jar
jeed-1.20-2.1.12.jar
jei-1.20.1-forge-15.3.0.4.jar
JustEnoughProfessions-forge-1.20.1-3.0.1.jar
JustEnoughResources-1.20.1-1.4.0.247.jar
justleveling-forge-1.20.x-v1.7.jar
Kambrik-6.1.1+1.20.1-forge.jar
Kleiders Custom Renderer API 6.0.0 1.20.1.jar
kotlinforforge-4.10.0-all.jar
Laendli_1.7.6a_24016 (1.20.1_forge).jar
light-overlay-8.0.0-forge.jar
LUMINOUS V1.3.3 - 1.20.jar
Lunar-forge-1.20.1-0.1.10.jar
man_of_many_planes-0.0.3+1.20.1-forge.jar
map_atlases-1.20-6.0.3.jar
marbledsapi-1.20.1-1.0.6.jar
marbledsarsenal-1.20.1-2.1.0cPRE-RELEASE-1.jar
MaxHealthFix-Forge-1.20.1-12.0.2.jar
mna-forge-1.20.1-3.0.0.11-all.jar
mobbattle-1.20.1-2.4.7-forge.jar
modernfix-forge-5.15.0+mc1.20.1.jar
modonomicon-1.20.1-forge-1.62.0.jar
monobank-1.20.1-1.1.4.jar
moonlight-1.20-2.11.9-forge.jar
mopeds_1.1_1.20.1.jar
MouseTweaks-forge-mc1.20-2.25.jar
Mutant Iceologer 2.0.1.jar
MutantMonsters-v8.0.7-1.20.1-Forge.jar
naturalist-forge-4.0.3-1.20.1.jar
NaturesCompass-1.20.1-1.11.2-forge.jar
Necronomicon-Forge-1.4.2.jar
nethers_exorcism-0.3.1D.jar
nyfsspiders-forge-1.20.1-2.1.1.jar
obscure_api-15.jar
Obscure-Tooltips-2.2.jar
oculus-mc1.20.1-1.6.15a.jar
Oreganized_1.20.1-2.0.3.jar
overloadedarmorbar-1.20.1-1.jar
Patchouli-1.20.1-84-FORGE.jar
Placeables 1.8.1.jar
Placebo-1.20.1-8.6.1.jar
player-animation-lib-forge-1.0.2-rc1+1.20.jar
polymorph-forge-0.49.2+1.20.1.jar
protection_pixel-0.9.1.jar
PuzzlesLib-v8.1.20-1.20.1-Forge.jar
pvz_zengarden-1.2.0.jar
radiantgear-forge-2.1.4+1.20.1.jar
radiation_zone-1.20.1_forge-1.0.2.jar
Realistic-Cobwebs-NeoForge-2.1.0-all.jar
realmrpg_creep_and_crop_1.0.2_forge_1.20.1.jar
realmrpg_dragon_wyrms_1.0.1_forge_1.20.1.jar
realmrpg_fallen_adventurers_1.0.3_forge_1.20.1.jar
realmrpg_imps_and_demons_0.9.0_forge_1.20.1.jar
realmrpg_pots_and_mimics_1.0.2_forge_1.20.1.jar
realmrpg_seadwellers_2.9.9_forge_1.20.1.jar
recruits-1.20.1-1.10.15.jar
reeves-furniture-1.20.1-1.11-forge.jar
resourcefulconfig-forge-1.20.1-2.1.2.jar
restApi-0.10.1-1.20.1-forge.jar
roost-1.1.0.jar
royal_variations_[Forge]_1.20.1_1.0.jar
rsec-1.1-1.20.1-forge.jar
rsgauges-1.2.20.jar
rustic_engineer-1.0.0.jar
sanitydim-mc1.20-1.1.0.jar
sawmill-1.20-1.3.9.jar
sculkhorde-1.20.1-0.9.0.jar
Searchables-forge-1.20.1-1.0.2.jar
seasonhud-forge-1.20.1-1.7.16.jar
sereneseasonfix-1.20.1-1.0.8.jar
SereneSeasons-1.20.1-9.0.0.46.jar
SherdDuplication-Forge-1.20.1-2.0.7.jar
ShieldExpansion-1.20.1-1.1.7a.jar
showcaseitem-1.20.1-1.2.jar
sight-1.2.2.jar
Silence's Turrets.jar
simplyswords-forge-1.54.0-1.20.1.jar
Sip'nSavor1.20.1+1.3.jar
sleep_tight-1.20-1.1.19.jar
smallships-forge-1.20.1-2.0.0-b1.1.jar
SmartBrainLib-forge-1.20.1-1.13.jar
sneak_through_berries-forge-8.0.0+1.20.1.jar
snowundertrees-1.20.1-1.4.3.jar
sophisticatedbackpacks-1.20.1-3.20.3.1034.jar
sophisticatedcore-1.20.1-0.6.12.589.jar
soulfired-1.20.1-3.2.1.0-forge.jar
spawn-1.0.2-forge.jar
SpelunkersCharm-3.5.8-1.20.1.jar
Spiritual_Come_Back_1.6.1_1.20.1.jar
spore_1.20.1_2.0.6b.jar
SporeMore-1.1-1.20.1.jar
structure_gel-1.20.1-2.16.1.jar
structure-expansion-2.0.1-build.11.jar
supermartijn642configlib-1.1.8-forge-mc1.20.jar
supermartijn642corelib-1.1.17-forge-mc1.20.1.jar
supplementaries-1.20-2.8.10.jar
suppsquared-1.20-1.1.14.jar
takesapillage-1.0.3-1.20.1.jar
TaxStructureArchitect+M.1.20.1+ForM.1.1.0.jar
TaxVillageArchitect+M.1.120.1+ForM.1.0.0.jar
tectonic-forge-1.19.3-2.3.1.jar
TerraBlender-forge-1.20.1-3.0.1.4.jar
textrues_embeddium_options-0.1.5+mc1.20.1.jar
tfmg-0.8.0b-1.20.1.jar
TFTH 1.1.jar
the-orcs-1.0-FORGE-1.20.x.jar
THEUNDEADREVAMPED_1.0u_1.20.1[Lightlevelfix].jar
theurgy-1.20.1-1.17.1.jar
through-the-lilypads-gently--mc1.20--1.1.1.jar
tidal-towns-1.2.jar
ToastControl-1.20.1-8.0.3.jar
toms_storage-1.20-1.6.5.jar
torchflower_arrows-1.20.1-1.0.jar
torchflower_relit-1.0.0.jar
Towns-and-Towers-1.12-Fabric+Forge.jar
TradingPost-v8.0.2-1.20.1-Forge.jar
Trapcraft-1.20.1-2.10.2.jar
trashcans-1.0.18b-forge-mc1.20.jar
trenzalore-forge-3.3.10+mc1.20.1-all.jar
trimsbegone-1.1-1.20.1.jar
underwaterenchanting-1.20.1-2.7.jar
valhelsia_core-forge-1.20.1-1.1.2.jar
villagesandpillages-forge-mc1.20.1-1.0.0.jar
VoidCubes-1.2.0-forge.jar
Voidscape-1.20.1-1.5.389.jar
water_from_cactus-1.2.0.jar
weather2-1.20.1-2.8.2.jar
Wild-West-1.1.0-1.20.1.jar
workers-1.20.1-1.7.8.jar
wthit-forge-8.8.0.jar
wthitharvestability-mc1.20.1-2.2.0.jar
WWOO-FABRIC+FORGE+QUILT-2.0.0.jar
YungsApi-1.20-Forge-4.0.4.jar
zume-0.17.0.jar`

If it is easier, here's a (highly updated) zip to the important folders:
https://www.dropbox.com/scl/fi/heqet12wnpvjruhypy4j7/Lin-Horror-Pack-31.zip?rlkey=jntzvjyb4ffovzhx80z7djifb&st=gcr45rxx&dl=0

**Comment by AlexModGuy** [comment]
> Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method noBreak2(ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V in alex_cave_addon.mixins.json:TephraExplosionMixin from mod alex_cave_addon failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap alex_cave_addon.refmap.json

remove whatever mod "alex_cave_addon" is.
