### ISSUE TITLE
[crash] the mod somehow nullifies the player?

### ISSUE THREAD

**Issue by OrangeSniper** [AlexModGuy/AlexsCaves#1104]
the game crashes when fully loaded into the world
[crash-2024-06-11_20.57.29-client.txt](https://github.com/user-attachments/files/15796404/crash-2024-06-11_20.57.29-client.txt)

**Comment by JMaraki** [comment]
I'm having the same issue. It only occurs when I re-add Create to my modpack though. It was working fine before, but broke one day when I updated a completely different mod. On a related note, Alex's mobs is having an odd interaction with Cobblemon at times where removing it causes the Restoration tank fluid to bug out and cause a crash upon attempting to launch the game.
