### ISSUE TITLE
alexs caves doesn't work with distant horizions

### ISSUE THREAD

**Issue by TreeTrunksUHC** [AlexModGuy/AlexsCaves#1107]
it wont load the LOD's when i use alexs caves

**Comment by weegeeluigi** [comment]
Can confirm, I'm guessing it crashes the renderer but it doesn't throw the error on the client.  Don't see it either on the logs side.

**Comment by moninformateur** [comment]
Can also confirm I'm having the same issue here. This only happens when Alex's Caves is enabled.

**Comment by HenrikoMagnifico** [comment]
Same issue. Alex Caves is not compatible with Distant Horizons

**Comment by CookieG77** [comment]
In order to make LOD work again in latest versions you need to turn off 'biome_ambient_light_coloring' in the client config of alex caves. (Work in 1.20.1 with both mod last version).

**Comment by benjamin051000** [comment]
See https://github.com/AlexModGuy/AlexsCaves/issues/519

**Comment by AlexModGuy** [comment]
fixed with solution for #1210
