### ISSUE TITLE
Cave Map not working

### ISSUE THREAD

**Issue by Pheonix5324** [AlexModGuy/AlexsCaves#1110]
The map is not working. The arrow in the cave map doesn't move. One update the cave map couldn't even find the cave. Stop saying that everything looks fine, Alex.

**Comment by PlummetStudios** [comment]
Are you close enough to the cave for it to move? Everything is fine for everyone else

**Comment by Pheonix5324** [comment]
I'm always at the edge of the map.

**Comment by ismael892** [comment]
then you are just extremely far away, caves can be thousands of blocks away. If you get a map in which you spawn in the middle of an edge instead of the corner, you should be able to see the arrow moving sideways when moving in that direction, even if not getting close to the biome
