### ISSUE TITLE
[Freeze/Crash] Forge 1.20.1, Riding Tremorzilla and Pressing F5

### ISSUE THREAD

**Issue by Werebearguy** [AlexModGuy/AlexsCaves#1112]
Hello, big fan of this mod. I recently hatched my first Tremorzilla, and I've had an absolute blast riding around on the big fella after getting him to grow up. I've encountered an issue however where, upon attempting to ride Tremorzilla in any variant of F5, causes the game to either freeze or crash, more often crashing. Here is my latest crash log and list of enabled mods:

Version: 1.20.1, Forge
[Mod List.txt](https://github.com/user-attachments/files/15937315/Mod.List.txt)
[crash-2024-06-22_11.47.28-client.txt](https://github.com/user-attachments/files/15937301/crash-2024-06-22_11.47.28-client.txt)

I don't know if it's this mod causing it or one of the many random mods in my pack, but I'm posting here since this only occurs with Tremorzilla and not any other mountable entity, from this mod or another.

**Comment by CockroachTheFoul** [comment]
Having a similar issue on a private server. It looks like it fails to render players riding or being picked up by mobs and crashes everyone that renders the interaction. It looks like it's an issue with embeddium, but this is the first instance I've seen of someone else having this issue. Maybe there's another mod causing it?
