### ISSUE TITLE
Submarine Light Issue In Third-Person With No Shaders

### ISSUE THREAD

**Issue by ChrisLTheNerd** [AlexModGuy/AlexsCaves#1114]
In first-person the lights are fine in Alex's Caves 1.1.4 and citadel-2.5.4. I tested it with no other mods aside from Alex's Caves and Citadel.
![2024-06-22_18 36 07](https://github.com/AlexModGuy/AlexsCaves/assets/50182206/f1b2f0dd-753c-472f-9c88-ae867e483643)

But in third-person most of the light turns invisible.
![2024-06-22_18 36 24](https://github.com/AlexModGuy/AlexsCaves/assets/50182206/1fde0e40-2017-4c75-9c5c-83978bcd7561)
![2024-06-22_18 36 28](https://github.com/AlexModGuy/AlexsCaves/assets/50182206/b8a2756b-49fd-4c42-80b6-ce6124863958)

**Comment by deleted-src** [comment]
If you're using optifine, I'd recommend switching to Embeddium + Oculus as Optifine can cause rendering issues (at least that happened with me)

**Comment by PlummetStudios** [comment]
The submarine renderer is designed to be used in first person
