### ISSUE TITLE
Hood and Cloak of Darkness Rendering Issue with Oculus/Embeddium

### ISSUE THREAD

**Issue by SlotMachineGun777** [AlexModGuy/AlexsCaves#1116]
With Oculus+Embeddium Installed, The cloak of darkness' gemstone flickers strangely
while wearing the hood. No other mods installed, No shaders being used. I am not very knowledgable when it comes to issues, so if this is not something you can fix i apologize for the inconvenience.

Edit: Uploaded the wrong video agh

https://github.com/AlexModGuy/AlexsCaves/assets/87162957/841d65ef-d87d-44db-b1f2-b582fda43f7c

**Comment by PlummetStudios** [comment]
Rendering changes can cause minor rendering issues. Mod incompat
