### ISSUE TITLE
Very slow chunkloading

### ISSUE THREAD

**Issue by Vikthos** [AlexModGuy/AlexsCaves#1133]
Minecraft; 1.20.1
Forge: 47.3.0
Alexscaves: 1.1.4

Other mods used:
- Embeddium
- Radium
- immediatelyfast

I've been having a problem of slow chunkloading in my modpack and after spending a very long time testing, alexscaves seems to be the cause. It more than doubles loading times of chunks which makes exploring difficult even though its an exploration mod. I really hope there can be a performance improvement because I love this mod !

**Comment by Vikthos** [comment]
I think it has to do with either some noise thing or the underground cabin because even with all biome generation completely disabled, the world generation time still takes 30 seconds instead of 10 and chunks are still incredibly slow.

**Comment by AlexModGuy** [comment]
dupe #1079
