### ISSUE TITLE
compatibility request: Create new age. 

### ISSUE THREAD

**Issue by Orionox** [AlexModGuy/AlexsCaves#1139]
Would be awesome if the magnetic cave could spawn the blocks used in create:new age

**Comment by TsameCorvy** [comment]
there's an existing yet unnoficial mod that integrates C:NA and Alex's Caves Together. It's not by a lot but it's neat.
But I agree that a more expanded integration would be cool, Uranium and Neodymium have features I can count with one hand, and especially the Neodymium part doesn't have any use that isn't made redundant by even vanilla contraptions. But. another unnoficial mod called Alex's Caves: Stuff & Torpedoes, despite the name, expands mostly on the Magnetic Caves, giving it much more justice in my opinion.
