### ISSUE TITLE
Abyssal chasm bugs way to much with tectonic.

### ISSUE THREAD

**Issue by Moctamm** [AlexModGuy/AlexsCaves#1149]
For me, the submarines and the structures appears but the blocks, corals, worms and every block that should generate doesn't generates. The mobs also do appear except for the hullbreaker and deep ones, the most important ones!! My world is already very progressed I have a lot of farms and the only thing I want from the abyssal chasm are the deep ones; could somebody tell me how to make them spawn so I can get the special items? Il be very grateful.

**Comment by AlexModGuy** [comment]
dupe #108
