### ISSUE TITLE
 primordial caves world lag.. need help plz

### ISSUE THREAD

**Issue by gongberlae** [AlexModGuy/AlexsCaves#1151]
As soon as I approach the primitive cave the server stops and a huge chunk loading lag starts. Any suggestions? The other caves didn't have a problem.

need help.

[latest.log](https://github.com/user-attachments/files/16272280/latest.log)

this is the lastest log. when i tp the primitve caves, the chunk lag was started

**Comment by AlexModGuy** [comment]
dupe #1079
