### ISSUE TITLE
Alex's Caves with Tectonic doesn't work fine

### ISSUE THREAD

**Issue by EzequielMTZ-18** [AlexModGuy/AlexsCaves#1154]
i play on a modded server with my gf and we noticed its very rare to find the new caves, but we did find some with the Cave Codex map thing. we visited Fornlorn Hollows and Magtenic Caves, both seemed to generate fine i think?

but we have problems with the Abyssmal Chasm, it doesnt generate at all, just structures.

we are using Tectonic mod for terrain, is there any fix to this?

anybody knows a terrain mod whiich works fine with Alexs Caves and how can we copy some chunks (our home and structures) to a new world?

**Comment by joebobthethird** [comment]
if you disable the deeper oceans config for tectonic then the chasm doesnt generate weirdly/not at all

**Comment by EzequielMTZ-18** [comment]
i didnt disabled anything, are you saying i should disable deeper ocean for tectonic to make Chasm able to generate ok? (any idea how to do it?)

**Comment by AlexModGuy** [comment]
dupe #794
