### ISSUE TITLE
Alex's Caves incompatibility with Pehkui size scaling

### ISSUE THREAD

**Issue by Kryllex** [AlexModGuy/AlexsCaves#116]
**With Alex's caves installed**, any direct usage of scaling (/scale set (anything different than one) or an indirect use of pehkui via another mod that changes height like Origins Pixie or Inchling or Giant **causes the player POV to stay at 2 blocks **tall.**** When crouching, the screen flys down to match the correct scaled down crouching height, but standing up makes the POV fly back up to original 2 block height. 100% chance to replicate in my testing with any other mods or just the 2.

**Comment by xtriel** [comment]
can confirm, had this issue with custom player models which also uses pehkui

**Comment by ThePizzaMan1** [comment]
Apologies, but I was wondering if this issue was resolved with the recent 1.0.4 Update or if the Conflict was with another matter between the two mods entirely?
The issue persisted after the update and resolved itself after I removed the mod from my folder.
Any feedback is appreciated.

**Comment by xtriel** [comment]
can confirm again this is still an issue after the most recent patch

**Comment by Kryllex** [comment]
Yep issue is still here! No running around in rat tubes just yet :c

**Comment by ThePizzaMan1** [comment]
Thanks for letting me know fellas, I figured they just needs to patch it in since he closed the issue with the new code that should hopefully resolve it. lol

**Comment by VillainousEater** [comment]
a year later and the bug still persists

**Comment by LYAN0526** [comment]
This problem still exists now
