### ISSUE TITLE
Maps leading to wrong biome

### ISSUE THREAD

**Issue by ismael892** [AlexModGuy/AlexsCaves#1167]
Simply, i have a map to primordial caves, i go there, toxic caves, even a long time ago when the mod just came out this problem existed, and with a different mod set altogether, i had a map to toxic caves, used it, dark caves (sorry i just forgot the name of those, the ones with the watcher and the moles).

This has happened many times in between, so much that to this day i have not find primordial caves with maps yet.

I've seen that other people also have problems with them not generating at all, why is this happening? Does anyone know?

**Comment by AlexModGuy** [comment]
dupe #395
