### ISSUE TITLE
Abyssal chasm floating blocks

### ISSUE THREAD

**Issue by LoofScared** [AlexModGuy/AlexsCaves#1171]
Floating blocks appear all over in the abyssal chasm, around where normal ocean depth would be.

Running NeoForge 47.1.106, Citadel 2.5.6, and Alex's Caves 1.1.4.

No other mods.

![Screenshot 2024-08-07 232254](https://github.com/user-attachments/assets/19f29bb5-3d7b-4b6b-bc10-a3ae7a41c68d)

**Comment by AlexModGuy** [comment]
dupe #227
