### ISSUE TITLE
[1.20.1] Peering Coprolith z-fighting, incompatibility with Acedium/Nvidium

### ISSUE THREAD

**Issue by Reshy** [AlexModGuy/AlexsCaves#1173]
Without Acedium:
![2024-08-09_19 11 47](https://github.com/user-attachments/assets/0b79ccce-b45a-4ebe-a919-44ce65b7710b)

With Acedium:
![2024-08-09_19 08 02](https://github.com/user-attachments/assets/c6f37704-e1e0-4cd4-8566-0a36124fcf61)

General Z-Fighting on normal behavior:
![2024-08-09_19 12 04](https://github.com/user-attachments/assets/6f17ec1d-5255-4279-9fea-09ffaa5d0428)
![2024-08-09_19 11 53](https://github.com/user-attachments/assets/959aebf3-9a71-4e6a-b08b-658e29c9bb23)

**Comment by AlexModGuy** [comment]
dupe #1134
