### ISSUE TITLE
Raygun causing screen to zoom into bottom left of screen with shaders on

### ISSUE THREAD

**Issue by BigBunkus** [AlexModGuy/AlexsCaves#1174]
Shooting raygun with shaders (im using optifine complimentary reimagined shaders) causes screen to zoom in to bottom left of my screen. It also happens when a mob that has been shot with the raygun is in my screen. it stops when the affected mob isnt. idk if its some kind of incompatability or a bug. pls help. and weird thing is, my friend has the exact same mods i have and yet his screen is fine.

Version: 1.20.1
Mods & their dependancies together:
-advancement plaques
-alexcaves
-alexcaves torpedoes
-alexmobs
-ambientsounds
-appleskin
-backpacked
-citadel
-collective
-corpse
-creativecore
-curiousapi
-eatinganimation
-enhancedvisuals
-explosiuveenhancment
-framework
-gml
-healingcampfire
-iceberg
-immersive aricraft
-jei
-journey map
-just enough resources
-mousetweaks
-moogs voyager structures
-not enough animations
-physics
-player revive
-skinlayers 3d
-sound physics remastered
-tiny alex caves tweaks
- travalers titles (comes with the alex caves titles resource pack)
- visuality
-simple vc
-yungs api
-yungs better mineshaft

Resource packs: (idk if its part of the issue im just including it incase)
-alex's titles
-create immersive aircraft 
-fresh animations

before firing
![Screenshot 2024-08-11 141530](https://github.com/user-attachments/assets/2703bc43-8c73-4715-86e7-7b9c64332f58)

after firing 
![Screenshot 2024-08-11 141643](https://github.com/user-attachments/assets/940ebb48-e0ea-48da-a453-3706a885b4e6)

**Comment by AlexModGuy** [comment]
caused by your shaders, alexs caves doesnt play nice with them. disable radiation glow in the configs to fix
