### ISSUE TITLE
Ray Cats Make Lag

### ISSUE THREAD

**Issue by fortnitelover228** [AlexModGuy/AlexsCaves#1177]
I already know that i can turn off the Irradiation glowing effect in config and its gonna fix the problem, but i want to keep it because ray Cat looks ugly without the Irradiated glowing effect and my Laptop is very strong, i also wanna see myself glow when Irradiated.

**Comment by fortnitelover228** [comment]
Uhhh aparently i got the oculus mod and it fixed the problem but uhhh it doesn't glow

**Comment by AlexModGuy** [comment]
dupe  #157
