### ISSUE TITLE
game crashed 

### ISSUE THREAD

**Issue by WKK199994** [AlexModGuy/AlexsCaves#1184]
The game crashed whilst exception generating new chunk
Error: java.lang.NullPointerException: Cannot invoke "com.github.alexthe666.citadel.config.biome.SpawnBiomeData.matches(net.minecraft.core.Holder, net.minecraft.resources.ResourceLocation)" because the return value of "java.util.Map.get(Object)" is null
[crash-2024-08-21_19.55.40-server.txt](https://github.com/user-attachments/files/16691172/crash-2024-08-21_19.55.40-server.txt)

**Comment by AlexModGuy** [comment]
> at com.github.alexthe666.iceandfire.config.BiomeConfig.test
wrong mod
