### ISSUE TITLE
Incompatibility of the tectonic mod with deep-sea caves.

### ISSUE THREAD

**Issue by ruWELIC** [AlexModGuy/AlexsCaves#1188]
Good afternoon, I have the Tectonic 2.3.5a mod, and the Alex Cave 1.1.5 mod. The problem is that the biome itself will not spawn, but only its structures.

**Comment by AlexModGuy** [comment]
dupe #794

**Comment by CrazyBarkley** [comment]
I do confirm that there still is an issue with worldgen concerning terralith+tectonic. this is where the volcano should be:

![Image](https://github.com/user-attachments/assets/a98b6a71-d8e7-4bdb-a02e-4863859207d2)
