### ISSUE TITLE
Abyssal Chasm Never Generates

### ISSUE THREAD

**Issue by bobs911** [AlexModGuy/AlexsCaves#119]
![image](https://github.com/AlexModGuy/AlexsCaves/assets/60241488/04272b29-7313-4fb9-9d87-6068e54c2414)
It just never does, this is in the 1.0.3 version of the mod.

**Comment by MykolaHamster** [comment]
Having the same issue with only Alex's caves 1.0.3 and Blueprint 7.0.0 installed

**Comment by Keneoo** [comment]
its just too far away

**Comment by bobs911** [comment]
> its just too far away

My guy, I created 5 worlds and teleported millions of blocks, either I am statistically the unluckiest person ever or there is a bug.

**Comment by AlexModGuy** [comment]
update citadel to 2.4.7
