### ISSUE TITLE
Radiation related effects cause players to continue experiencing black screens

### ISSUE THREAD

**Issue by SMFDrummer** [AlexModGuy/AlexsCaves#1190]
As title, after being exposed to the irradiation effect, players will experience a black screen when their perspective rotates to a specific angle, making it impossible to play. Even if the irradiation effect ends, this will still be the case.
This is error.
![image](https://github.com/user-attachments/assets/17381648-81ea-45f6-aee9-5a0cca9f4714)
This is normal
![image](https://github.com/user-attachments/assets/80aebaf8-f9ca-47a3-b879-f471559dada8)
You must fix this issue as soon as possible, otherwise the mod will greatly affect playability.

**Comment by SMFDrummer** [comment]
Bug stable triggering method, any level of irradiation effect in the body, and wait for the irradiation effect to end. Continue waiting for a moment, and if there is any view field include the raycat, whatever under a wall or else, the screen will be black.

**Comment by Cattomaniac** [comment]
i am having the same issue

**Comment by AlexModGuy** [comment]
disable radiation glow effect in the config
