### ISSUE TITLE
Watcher crashes game when trying to posses player.

### ISSUE THREAD

**Issue by Dorian211** [AlexModGuy/AlexsCaves#1193]
Whenever a watcher tries possessing me or i try to use the occult gem with a beholder the game crashes.

[crash-2024-08-29_21.42.42-client.txt](https://github.com/user-attachments/files/16812978/crash-2024-08-29_21.42.42-client.txt)

**Comment by AlexModGuy** [comment]
>	at polarisnighten.entropy.procedures.CameraShakeProcedure.computeCameraAngles(CameraShakeProcedure.java:42) ~[entropy-1.3.2.jar%23302!/:?] {re:classloading}


bug caused by polaris, should not assume the camera entity is a player
