### ISSUE TITLE
Biomes not spawning correctly when paired with Deeper Oceans

### ISSUE THREAD

**Issue by Rainflea** [AlexModGuy/AlexsCaves#1197]
As the title said, whenever I try to pair deeper oceans with AlexsCaves The Abyssal Chasm ends up generating incorrectly as an completely enclosed underground cave or a block of solid abyssmarine.

**Comment by AlexModGuy** [comment]
you need to adjust the generation values of the abyssal chasm biome in the config for this to work properly.
