### ISSUE TITLE
[1.20.1] Alex's Caves Crash

### ISSUE THREAD

**Issue by HaizUber** [AlexModGuy/AlexsCaves#12]
Forge: 47.1.3
Embeddium 0.2.2
Oculus 1.6.9

Steps to Reproduce:
1. Install Alex's Caves 1.0.0 with my current modlist

If this helps, I have Sinytra Connector (https://modrinth.com/mod/connector) installed and a bunch of fabric mods that can be seen in the log

Crash-Report: https://gist.github.com/HaizUber/84e3392ad5b62a0269b090403cc1b29b

can provide additional information when needed

**Comment by HaizUber** [comment]
[latest.log](https://github.com/AlexModGuy/AlexsCaves/files/13042078/latest.log)
latest.log if it helps

**Comment by AlexModGuy** [comment]
conflict with sodium extras
