### ISSUE TITLE
Unable to find any biomes the cave biome map cannot detect any nearby.

### ISSUE THREAD

**Issue by BestOperaUser** [AlexModGuy/AlexsCaves#1204]
I've heard about this mod from YouTube and it sounded pretty sick so I changed from fabric to neoforge to use it but i cannot detect the biomes anywhere at all using /locate and the cave biome map, so is there any config to make the biome spawn more commonly, tell me step by step how to make it more common by config.

**Comment by CirinH** [comment]
As far as I know. There're 3 ways:
1. edit config file: it should be in \.minecraft\versions\[your version]\config\alexscaves_biome_generation, which you can find 5 json file, open them, "alexscaves_rarity_offset" controls the rarity, change its value to 0 should increase the chance of cave generation.
2. use the mod : https://www.curseforge.com/minecraft/mc-mods/tact
3. some old version mod cause bugs, the caves are not RARE but DONT generate, try update your Alex Caves and Citadel
