### ISSUE TITLE
Falling Through Blocks Moved by Magnets

### ISSUE THREAD

**Issue by BugReportingAccount** [AlexModGuy/AlexsCaves#1219]
My interpretation of the magnets is that they are, among other uses, for making platforms and elevators.

I have built a two by two elevator on my modded world. The elevator moves from a ground floor to a platform made of slabs. It is moved using a pair of magnets under it (One repelling and one attracting, triggered in alternation to make it move). Almost every time when using the elevator _upwards_ the player phases through the elevator. This happened to me and my friend. Note that I am travelling abroad and am therefore using a woefully underpowered laptop. Jumping just before the platform moves fixes the issue, and one usually phases through the block at the top of the elevator.

Note that this world features some other mods including Create.

**Comment by PlummetStudios** [comment]
Known issue :(
