### ISSUE TITLE
cant walk up non-full blocks anymore when mod is installed

### ISSUE THREAD

**Issue by dudeguy57** [AlexModGuy/AlexsCaves#122]
ALL entities lose the ability to quickly walk up stairs, slabs, tilled dirt, dirt paths, snow, and any other non-full block. villagers are literally stuck within the confines of the village's dirt paths. also horses lose the ability to walk over blocks vertically, not just half blocks but full blocks, they just walk straight into them, you must jump over them. in conclusion is seems that alex's caves disables the ability to quickstep over any block at all for all entities. this IS game-breaking, please fix soon because I love the features in this mod.

**Comment by Bondzberg** [comment]
This has been fixed in 1.03. Curseforge is acting weird with which version it considers to be the latest so make sure you have the most up-to-date version.
