### ISSUE TITLE
Alex's caves causes Distant horizons to not Generate LODs

### ISSUE THREAD

**Issue by Airstor** [AlexModGuy/AlexsCaves#1220]
if using Distant Horizons and Alex's caves in 1.20.1, Alex's caves config setting: Biome Ambient Light Coloring causes Distant Horizon LODs to stop rendering (screenshot 1) and with some shaders causes the terrain to duplicate itself across the skybox (screenshot 2), i tested with and without shaders. However if the Config Biome Ambient Light Coloring is disabled, Distant Horizons Functions Normally AND you can reenable Biome Ambient Light Coloring with no issues until you reload the world (screenshots 3 and 4). Screenshots provided below.

![1](https://github.com/user-attachments/assets/1f536dfa-abe6-44de-9f26-664ff4f55605)

![2](https://github.com/user-attachments/assets/68db7e64-df77-4757-825c-6fffdda8aeeb)

![3](https://github.com/user-attachments/assets/89dbeeca-24c1-45b0-b709-65449daa1020)

![4](https://github.com/user-attachments/assets/846c0546-4f5b-45fe-bdc0-c3d2fdf866bb)

**Comment by AlexModGuy** [comment]
dupe #519
