### ISSUE TITLE
The discord invite link on curseforge and modrinth is invalid

### ISSUE THREAD

**Issue by xErrorAmelie** [AlexModGuy/AlexsCaves#1224]
This is the invite link: https://discord.com/invite/alexsmods

**Comment by itsdeadfrosty** [comment]
which is ALSO expired. do you not know how to set the links to not expire??

**Comment by Billnotic** [comment]
Yeah none of the links to join work.

**Comment by itsdeadfrosty** [comment]
theyre so confident too LMAO
