### ISSUE TITLE
Проблема с модом alex caves с генерацией пещер и картой в версии мода 1.1.5

### ISSUE THREAD

**Issue by Hardsmoke23** [AlexModGuy/AlexsCaves#1229]
Столкнулся с проблемой карты,точнее ее неправильной навигации, карта у меня была первобытных пещер,я пришел туда куда надо,и там оказались токсичные пещеры и на карте показывало,что рядом есть и первобытные пещеры,но на самом деле их там не было,Я решил поискать по другой карте и мне показало,что первобытные пещеры в другой стороне.Я прилетел туда и там снова были токсичные пещеры.Исправьте данную проблему

**Comment by AlexModGuy** [comment]
dupe #1155
