### ISSUE TITLE
Glow Ink Bombs give you blindness forever and make everything above water look foggy

### ISSUE THREAD

**Issue by Jasdernn** [AlexModGuy/AlexsCaves#123]
Weird
![2023-10-19_21 54 01](https://github.com/AlexModGuy/AlexsCaves/assets/148498785/c7793d1f-8f54-4f87-ac05-78f20a542732)
![2023-10-19_21 54 03](https://github.com/AlexModGuy/AlexsCaves/assets/148498785/0813e677-4169-4bac-901b-8dd08d54b4d2)

**Comment by AlexModGuy** [comment]
having trouble replicating this. what visual mods are you using

**Comment by Jasdernn** [comment]
None, but I also had deepsight and night vision on for infinity without particles.
