### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by superblast1** [AlexModGuy/AlexsCaves#1230]
i got this issue 

Error: java.lang.ClassCastException: class com.github.alexmodguy.alexscaves.server.entity.living.WatcherEntity cannot be cast to class net.minecraft.world.entity.player.Player (com.github.alexmodguy.alexscaves.server.entity.living.WatcherEntity is in module alexscaves@1.1.5 of loader 'TRANSFORMER' @6bf2ecbb; net.minecraft.world.entity.player.Player is in module minecraft@1.20.1 of loader 'TRANSFORMER' @6bf2ecbb)

heres the crash log
[https://pastebin.com/ADd5fq0J](url)

https://pastebin.com/ADd5fq0J

**Comment by AlexModGuy** [comment]
> 	at polarisnighten.entropy.procedures.__CameraShakeProcedure_computeCameraAngles_ComputeCameraAngles.invoke(.dynamic) ~[entropy-1.3.2.jar%23619!/:?] {re:classloading,pl:eventbus:B}

"polaris" mod needs to instanceof Player check before modifying the camera angle. Report to their devs
