### ISSUE TITLE
CRITICAL: Unholy lag from Sundrops in Candy Cavity with high tickrate

### ISSUE THREAD

**Issue by Inonedn** [AlexModGuy/AlexsCaves#1238]
![image](https://github.com/user-attachments/assets/008047ea-138b-4b94-94c9-5fc1fa897c32)

**Comment by Inonedn** [comment]
![image](https://github.com/user-attachments/assets/96ef3606-e54d-4571-af07-449ad6ea0d58)

**Comment by PlummetStudios** [comment]
I would not change the tick rate then
