### ISSUE TITLE
Visual bug w/ gummy worms while in spectator mode

### ISSUE THREAD

**Issue by Munchalotl** [AlexModGuy/AlexsCaves#1239]
Hi! I went into spectator mode to check out a gummy worm in all its glory, and there seems to be a slight rendering/visual issue with a stretching texture (see image below). The stretchy bits only appear like that while I'm in the ground -- when I'm not clipped inside of blocks, the texture lingers for a moment before disappearing. So I'm assuming it has something to do with loading/culling bits of the mob when it is/isn't visible?

![2024-10-19_17 29 08](https://github.com/user-attachments/assets/8f73f34a-0d02-401b-b118-77268f29ae5f)

**Comment by Munchalotl** [comment]
Hey ok so I found a more notable issue with the rendering of these guys, don't know how it happened this time because I'm just flying around purely in creative now. But I saw this a few minutes after making the original post.

![2024-10-19_17 34 59](https://github.com/user-attachments/assets/eab5a9de-6f97-4294-80af-bbeb4392bf0f)

**Comment by AlexModGuy** [comment]
do you have the entity culling mod installed?

**Comment by Munchalotl** [comment]
Yes, I do. I'm assuming that's the issue here?
Thank you, sorry for the trouble.
