### ISSUE TITLE
Issues with Quark : Spawn of Oretoise and Stonelings in candy cavity, and Monster Box

### ISSUE THREAD

**Issue by HyperAxo** [AlexModGuy/AlexsCaves#1241]
These mobs are spawning everywhere and a lot, especially the Oretoise
![imagem_2024-10-19_183116528](https://github.com/user-attachments/assets/d3a52a71-897b-4f70-ae28-2e989b918412)
![imagem_2024-10-19_183455169](https://github.com/user-attachments/assets/cca471d4-8c4a-4363-8606-fd58cabb1717)

**Comment by AlexModGuy** [comment]
remove tiny alex cave tweaks

**Comment by YocyCraft** [comment]
I didn't installed tiny alex cave tweaks but I hace the same issue
