### ISSUE TITLE
You can trigger the Conversion Crucible without using up the Biome Treat

### ISSUE THREAD

**Issue by Munchalotl** [AlexModGuy/AlexsCaves#1242]
While messing with the Conversion Crucible, I accidentally missed when I tossed my Biome Treat toward the pot. Instead of going inside, it landed on the edge. Despite this, the conversion ritual began while the Biome Treat sat hovering on the edge of the pot. This seems to only happen with the Biome Treat, and not with any of the subsequent ingredients.

![2024-10-19_18 10 40](https://github.com/user-attachments/assets/0168211e-a858-4868-b3ce-2cdd5e8a9569)

**Comment by Munchalotl** [comment]
Actually, it seems like the crucibles just don't destroy the biome treat at all, even when tossed in and left there. I can pick it back up at any time while the ritual is happening without stopping the ritual.

**Comment by kaboom24** [comment]
i will confirm this, not sure if its intentional though

**Comment by X66Herobrine66X** [comment]
Pretty sure its intentional. They're quite expensive to make and there's a lot of different biomes. It doesn't make sense to force the player to craft a new one for every 12 block circle they want to convert. Seems more likely that once you have one, its yours.

**Comment by X66Herobrine66X** [comment]
Fuckkkk. They deemed it a bug and fixed it, that sucks.
