### ISSUE TITLE
Crash with advancementplaques 

### ISSUE THREAD

**Issue by itstaajaae** [AlexModGuy/AlexsCaves#1243]
[crash-2024-10-19_17.30.57-client.txt](https://github.com/user-attachments/files/17447486/crash-2024-10-19_17.30.57-client.txt)

**Comment by itstaajaae** [comment]
The crash happened when hovering over items in creative menu,

Apologies if this issue is not up to slandered.

**Comment by AlexModGuy** [comment]
dupe #1244
