### ISSUE TITLE
Gum Worms freezing

### ISSUE THREAD

**Issue by beanboy1129** [AlexModGuy/AlexsCaves#1247]
So there are two ways the gum worm can, The first is if a gobthumber cannot be reached by a Gum Worm in which case it freezes. Second, if two gobthumpers are placed some distance away from each other so that the Gum Worm can't eat it in one bite then it will eat the first gobthuper then freeze. If you hit the Gum Worm in survival mode then it will not being frozen and attack you or if your break the gobthupers then attack it.
![2024-10-19_21 50 06](https://github.com/user-attachments/assets/cf3578aa-cb8e-48b0-94bc-c639cdcf2482)

**Comment by shromide** [comment]
They also tend to freak out if a Gobthumper is placed underwater, freezing while trying to path to it.
(the Forsaken has no pathing while in water either)

**Comment by shromide** [comment]
Caused by Entity Culling - known issue
