### ISSUE TITLE
Gingerbread Armor not working with optifine

### ISSUE THREAD

**Issue by beanboy1129** [AlexModGuy/AlexsCaves#1249]
![2024-10-19_21 59 14](https://github.com/user-attachments/assets/67ff036c-3665-43e3-95eb-4d4f1b61fc89)
![2024-10-19_21 59 20](https://github.com/user-attachments/assets/6661aa0c-bc8d-4988-a293-5fd025c494dd)

**Comment by AlexModGuy** [comment]
no custom modeled armors work with optifine. this bug is their problem, not ours.

**Comment by PlummetStudios** [comment]
Optifine is incompatible with this mod

**Comment by beanboy1129** [comment]
Do you know a performance mod that works with Alex's caves

**Comment by vinicius1232426** [comment]
Embeddium
