### ISSUE TITLE
licowitches spawned from eggs dont experiment

### ISSUE THREAD

**Issue by kaboom24** [AlexModGuy/AlexsCaves#1252]
becuase of https://github.com/AlexModGuy/AlexsCaves/issues/1251#issue-2599889002 I have to spawn my licowitches with spawn eggs and they dont experiment which is annoying (maybe happens with more than just spawn egged licowitches but I cant tell since they dont natrually spawn for me)

**Comment by AlexModGuy** [comment]
not able to reproduce

**Comment by kaboom24** [comment]
yeah looks like I didnt wait long enough
