### ISSUE TITLE
The sugar rush saturated vision not staying when swiching gamemodes

### ISSUE THREAD

**Issue by beanboy1129** [AlexModGuy/AlexsCaves#1271]

**Comment by Zer0-Rei** [comment]
I also tried it, but when switching game modes via commands, the saturated vision persists. If you're referring to the saturated vision changing when switching game modes with F3+F4, then that's not an issue. Pressing F4 toggles shaders on and off, which is a feature of Minecraft. This includes things like spectating spiders in spectator mode.
