### ISSUE TITLE
Visual Glitch when using other mods

### ISSUE THREAD

**Issue by Sombra-zx** [AlexModGuy/AlexsCaves#1276]
- Here is my issue im playing with 2 friends a minecraft server that used the anterior version of the mod, i updated the mod when we added others mods and now i have visual issues or better sayed certain candy cavities blocks does not appear and they are replace with other blocks from the add on mod Torpedoes and Stuff, here are a few screenshots:

![2024-10-20_17 29 15](https://github.com/user-attachments/assets/e747654e-0e57-473b-ad35-b67d698ad2a4)
![2024-10-20_17 29 19](https://github.com/user-attachments/assets/61cfbc5e-dc12-413f-b17e-3a1de473fe47)
![2024-10-20_17 26 27](https://github.com/user-attachments/assets/b12ab5e4-3f98-430f-8835-93ba9b911ed4)

**Comment by AlexModGuy** [comment]
expected behavior with block Id's being shifted. Not something that can be fixed
