### ISSUE TITLE
Using a Conversion Crucible with a Biome Treat that has an invalid biome value causes a crash.

### ISSUE THREAD

**Issue by Zer0-Rei** [AlexModGuy/AlexsCaves#1277]
Using the Biome Treat obtained with commands like 
`/give @s alexscaves:biome_treat{CaveBiome: "minecraft:example_cave"}` or 
`/give @s alexscaves:biome_treat{}`
in the Conversion Crucible causes a crash at the moment the biome is changed. Additionally, attempting to re-enter that world will also result in a crash.

**Comment by AlexModGuy** [comment]
crash log?

**Comment by Zer0-Rei** [comment]
> クラッシュログ？

[crash-2024-10-21_01.44.28-server.txt](https://github.com/user-attachments/files/17451301/crash-2024-10-21_01.44.28-server.txt)
