### ISSUE TITLE
Conversion Crucible Biome Overlap Reversion.

### ISSUE THREAD

**Issue by Cerinox** [AlexModGuy/AlexsCaves#1293]
A curious issue I have found, is that when you use the crucible to convert a biome, and that radius overlaps with a previously converted biome (by the crucible), the first-changed biome is undone back into it’s previous state as the next is converted.

I came upon this discovery when trying to make a new candy-cavity biome on the surface larger than the single radius.

**Comment by AlexModGuy** [comment]
dupe #1255
