### ISSUE TITLE
Sound subtitle is wrong.

### ISSUE THREAD

**Issue by Zer0-Rei** [AlexModGuy/AlexsCaves#1298]
The translation key used for the subtitles when the sound "alexscaves:caniac_swing" is played is "alexscaves.sound.subtitle.caniac_attack" instead of "alexscaves.sound.subtitle.caniac_swing."

**Reproduce:**
1. Enable subtitles in the settings.
2. Enter the command `/playsound alexscaves:caniac_swing master @s` in the chat.

**Comment by AlexModGuy** [comment]
dupe #1285
