### ISSUE TITLE
Large dinos sink into the ground on superflat worlds

### ISSUE THREAD

**Issue by Temosaurus** [AlexModGuy/AlexsCaves#130]
![2023-10-19_21 12 20](https://github.com/AlexModGuy/AlexsCaves/assets/77913467/4ac118a6-0a22-4760-b3c4-737201077d33)
![2023-10-19_21 13 03](https://github.com/AlexModGuy/AlexsCaves/assets/77913467/30112866-a28c-4422-b6f4-7ab03715e65f)

**Comment by PCAwesomeness** [comment]
#128

**Comment by AlexModGuy** [comment]
^
