### ISSUE TITLE
Distant horizons incompatibility with alexs caves

### ISSUE THREAD

**Issue by Jkizzy69** [AlexModGuy/AlexsCaves#1300]
in the 2.0.0 update you stated in the changelog that you had fixed the incompatibility issues so i went to test it and it still did not work no LODs would load, and an error message kept showing up thank you for your time i love the mod.

**Comment by Bonkjumper** [comment]
I believe this is possibly an issue DH side, as it's probably only checking whether the mod is present or not and whether the specific config changes were made, but again this is my guess

**Comment by AlexModGuy** [comment]
this is on DH's side then, changes were made according to their instruction: [#1220 ](https://github.com/AlexModGuy/AlexsCaves/issues/519)
