### ISSUE TITLE
Z-fighting when 2 icecream blocks places horizontally adjacent to each other

### ISSUE THREAD

**Issue by YocyCraft** [AlexModGuy/AlexsCaves#1305]
When the screen zoomed there will be some white and pink dots in the slit of chocolate icecream (hard to see though).
![2024-10-21_17 13 40](https://github.com/user-attachments/assets/c61be5de-26f0-405a-a2e1-7c9c9ee37087)

This picture is easier to see:
```
/execute in minecraft:overworld run tp @s 228.47 -4.99 2654.50 -1804.66 51.15
/setblock 227 -4 2655 alexscaves:vanilla_ice_cream[type=1]
/setblock 227 -4 2654 alexscaves:chocolate_ice_cream[type=1]
```
![2024-10-21_17 19 03](https://github.com/user-attachments/assets/20af3ca5-c442-41e3-9dd1-c0c03b831c95)

**Comment by AlexModGuy** [comment]
dupe #1304
