### ISSUE TITLE
Conversion crucible don't need sculk block to convert into deep dark biome

### ISSUE THREAD

**Issue by YocyCraft** [AlexModGuy/AlexsCaves#1306]
The terrain of deep dark biome is made of sculk blocks and deepslates, however conversion crucible still need grass blocks and dirts to convert into deep dark (as well as most overworld biomes). Also after conversion terrain blocks will not converted into sculk blocks.
![2024-10-21_18 27 08](https://github.com/user-attachments/assets/156905e9-3eed-4b9e-82b9-b543b0703568)
![2024-10-21_18 27 19](https://github.com/user-attachments/assets/a326661a-b248-488b-b6da-3214c5c98ff9)
![2024-10-21_18 27 36](https://github.com/user-attachments/assets/7d1ad391-5783-4d6a-b339-d6d6e5073143)

**Comment by AlexModGuy** [comment]
correct, skulk blocks are not technically the "surface" blocks of the deep dark biome, that is actually grass. you can see this by creating a single biome deep dark world and notice the surface is all grass.

**Comment by YocyCraft** [comment]
> correct, skulk blocks are not technically the "surface" blocks of the deep dark biome, that is actually grass. you can see this by creating a single biome deep dark world and notice the surface is all grass.

But thia behavior is counter-intuitive for most players.

**Comment by X66Herobrine66X** [comment]
> > correct, skulk blocks are not technically the "surface" blocks of the deep dark biome, that is actually grass. you can see this by creating a single biome deep dark world and notice the surface is all grass.
> 
> But this behavior is counter-intuitive for most players.

You really expect him to take the time to code a specific exception to the algorithm just for the deep dark, when it works fine as is?
