### ISSUE TITLE
Conversion crucible can convert into not exist biomes and crash the game

### ISSUE THREAD

**Issue by YocyCraft** [AlexModGuy/AlexsCaves#1307]
Reproduce:
1. Run command `/give @s alexscaves:biome_treat{CaveBiomes:"notexist:not_found_404"}`
2. Use the given biome treat on conversion crucible
3. Use dirts, grass blocks and diamond to complete the conversion procedure
4. The game crashed
5. Try to restart the world and HAHA! The game crashed again
6. Now you successfully ruined your world save, congradulations

[Crash report](https://mclo.gs/29L8E4W)

**Comment by Zer0-Rei** [comment]
dupe https://github.com/AlexModGuy/AlexsCaves/issues/1277
That issue has already been resolved.
