### ISSUE TITLE
World crash when looking at candy cavity items in jei/rei

### ISSUE THREAD

**Issue by MONKEYGODEMPEROR** [AlexModGuy/AlexsCaves#1309]
Tried both rei and jei with and without addons, if i type alex’s caves into the search bar it works fine for the other biomes, it’s specifically when i look at candy cavity items that the crash happens. I can look at the items in my inventory and the creative menu just fine. Everything else looks cool as hell though, great update.

**Comment by AlexModGuy** [comment]
what is the crash log

**Comment by AlexModGuy** [comment]
dupe #1244
