### ISSUE TITLE
Attempting to un-waterlog a Gummy Ring hard-crashes the game

### ISSUE THREAD

**Issue by endro555** [AlexModGuy/AlexsCaves#1319]
https://github.com/user-attachments/assets/d28ff2c4-3fb4-4701-991a-bc00ea7ee32d

Using an empty bucket on a waterlogged Gummy Ring will immediately crash the game
[Logs](https://github.com/user-attachments/files/17465117/latest.log)

**Comment by AlexModGuy** [comment]
dupe #1250
