### ISSUE TITLE
Cinder Blocks Weird Textures

### ISSUE THREAD

**Issue by SuperStefan97** [AlexModGuy/AlexsCaves#132]
I found a weird bug regarding cinder blocks, they are nice and all, but when you get too far from them, they start to look like this, with the End Portal gateway texture... not sure why. I took this screenshots without any kind of shaders and without rubidium/oculus
![2023-10-19_20 41 08](https://github.com/AlexModGuy/AlexsCaves/assets/96614259/798c3309-1742-4eee-ad81-c336ef268d4b)
![2023-10-19_20 41 16](https://github.com/AlexModGuy/AlexsCaves/assets/96614259/f97491b0-bc20-4f92-bcc2-8729eb6b79ab)

**Comment by SuperStefan97** [comment]
Nvm, it was Forgified Fabric API version 26, downgrading to version 25 solves the issue.

**Comment by SuperStefan97** [comment]
Solved

**Comment by SuperStefan97** [comment]
Nvm, the problem is still present with textures

**Comment by AlexModGuy** [comment]
![2023-10-20_08 06 41](https://github.com/AlexModGuy/AlexsCaves/assets/8662109/fa491630-0ddf-4e58-b608-732a35b40396)
not able to replicate. what visual mods are you using

**Comment by SuperStefan97** [comment]
[latest.log](https://github.com/AlexModGuy/AlexsCaves/files/13055836/latest.log)
Here is my .latest in case it's helpful. It also seems to me there could be a loosen pixel (not sure if that's the correcto word) in the superior left quadrant of the block's texture, from near, that only little space looks like the end portal.

**Comment by SuperStefan97** [comment]
I had a hunch, and tested it. There is a mod named Stellarity that revamps the end, it uses empty textures in order to use their end portal block. 
When playing without Stellarity, the cinder blocks look normal, but when re installing it, the mod detects a small gap in the model and thinks it's an ender portal. I will also tell them about it
![2023-10-20_09 37 40](https://github.com/AlexModGuy/AlexsCaves/assets/96614259/80f11d86-c15c-46cf-a91c-8ff29349f1ea)
![2023-10-20_09 41 34](https://github.com/AlexModGuy/AlexsCaves/assets/96614259/b65fd1ad-330f-4af9-ae74-84d268f7e370)
![2023-10-20_09 41 59](https://github.com/AlexModGuy/AlexsCaves/assets/96614259/0bc1fda4-2142-4893-aa66-12e17f90bada)
![2023-10-20_09 42 20](https://github.com/AlexModGuy/AlexsCaves/assets/96614259/704dd526-7ad0-4461-a483-a4622b207e2e)

**Comment by AlexModGuy** [comment]
fixed the alpha on that texture, but the bug should be promoted to the other mod since its likely this will happen again for other devs.

**Comment by SuperStefan97** [comment]
Thanks! I told them too, as yeah... it might break something else later. Thanks for your help!
