### ISSUE TITLE
Crash when looking at a page in EMI

### ISSUE THREAD

**Issue by undefined06855** [AlexModGuy/AlexsCaves#1322]
Can't really tell you what item specifically or even if it's related to Alex's Caves, but at default GUI scale (4) the crash is on page 6 when you search "@Alex" in EMI (so only alex's caves items are being shown)
[crash log (https://mclo.gs/TUeJgsW)](https://mclo.gs/TUeJgsW)
Certainly not Rubidium or DH though

**Comment by YocyCraft** [comment]
Dupe #1244

**Comment by AlexModGuy** [comment]
fixed https://modrinth.com/mod/alexs-caves/version/2.0.1
