### ISSUE TITLE
Mobs in buckets lacks dispenser behavior

### ISSUE THREAD

**Issue by thelegitdolt** [AlexModGuy/AlexsCaves#1323]
In vanilla, dispensing a fish bucket places down the bucket with the fish in it. However, this does not apply to fish bucket added in alex caves, like radgill buckets, sweetish fish buckets, et cetera

**Comment by thelegitdolt** [comment]
Water buckets can be dispensed to catch the fish as normal.

**Comment by YocyCraft** [comment]
Dupe #1315

**Comment by thelegitdolt** [comment]
oops
