### ISSUE TITLE
Tectonic mod in conflict with Alex cave 

### ISSUE THREAD

**Issue by Spidergame30** [AlexModGuy/AlexsCaves#1333]
![image_2024-10-22_081951664](https://github.com/user-attachments/assets/f6fde521-4a1b-47cc-b666-218a9bfb15ae)
![image_2024-10-22_082007375](https://github.com/user-attachments/assets/62a3481a-deea-4d73-885f-37896931fc1d)
![image_2024-10-22_082014159](https://github.com/user-attachments/assets/a604e437-da27-4e86-8859-e91582322872)
![image_2024-10-22_082023293](https://github.com/user-attachments/assets/c7820182-31e6-4e8f-92df-b59f20a86d89)
Hello i play on the modpack Mystic horizon but all the caves in the Alex cave mod are badly generated : some mobs and structures don't appear because of the Tectonic mod. I tried removing Tectonic but the problem persisted.

**Comment by AlexModGuy** [comment]
dupe #794
