### ISSUE TITLE
Radiant Essence crashes the game the moment the mouse hovers over it

### ISSUE THREAD

**Issue by RRG2** [AlexModGuy/AlexsCaves#1339]
![2024-10-22_12 13 53](https://github.com/user-attachments/assets/e79e2deb-8a9d-40e8-b162-cb5f618d2e13)
That's literally it. I have many other mods but the problem came with the last update patch and it only happens with radiant essence. When I hover over it in JEI, it states that the ingredient crashed while getting its tooltip. I have the crash log here as well. Thanks for your tremendous efforts in the mod!

[message.txt](https://github.com/user-attachments/files/17474095/message.txt)

**Comment by hexagonelle** [comment]
I am also having this issue.
Forge 47.3.0
Minecraft 1.20.1
Alex's Caves 2.0.1
