### ISSUE TITLE
friend crashes after a minute

### ISSUE THREAD

**Issue by thecatking9274** [AlexModGuy/AlexsCaves#1343]
im playing with a friend and after a minute it crashes for him and I have no idea why

\
[crash-2024-10-22_15.44.56-client.txt](https://github.com/user-attachments/files/17476432/crash-2024-10-22_15.44.56-client.txt)
[latest (3).log](https://github.com/user-attachments/files/17476433/latest.3.log)

**Comment by AlexModGuy** [comment]
both of you need to use 2.0.1
