### ISSUE TITLE
Sack of Sating Crash on Multiplayer Server

### ISSUE THREAD

**Issue by CyberRat7** [AlexModGuy/AlexsCaves#1346]
[crash-2024-10-22_19.03.43-client.txt](https://github.com/user-attachments/files/17479817/crash-2024-10-22_19.03.43-client.txt)

**Comment by AlexModGuy** [comment]
> 		alexscaves-2.0.0.jar                              |Alex's Caves                  |alexscaves                    |2.0.0               |DONE      |Manifest: NOSIGNATURE

update to 2.0.1
