### ISSUE TITLE
caves biome not generated

### ISSUE THREAD

**Issue by Azterio** [AlexModGuy/AlexsCaves#135]
cave biomes are not found with either the /locate command or the cave biome map
![photo_2023-10-20_00-41-46](https://github.com/AlexModGuy/AlexsCaves/assets/83926059/d20202eb-dbc8-47b8-a23f-340b29be3d00)

[latest.log](https://github.com/AlexModGuy/AlexsCaves/files/13049710/latest.log)

**Comment by melvinczyk** [comment]
Same problem I've gone 10,000  20,000  30,000 blocks away from spawn with the same message, even configured the alexscaves-general.toml to make them more common.
