### ISSUE TITLE
Irradiated effect causes black screen other than the irradiated thing.

### ISSUE THREAD

**Issue by MajorBeaver** [AlexModGuy/AlexsCaves#1352]
![Screenshot 2024-10-22 212812](https://github.com/user-attachments/assets/532a278e-9034-42d6-8d3a-fc2d8248de07)

Every time I've tried this mod in minecraft after not too long it's started to cause my screen to go black every time I see an irradiated mob and the only way to fix that problem is to turn off the effect all around and I don't really like doing that as it kinda ruins the mod.

**Comment by AlexModGuy** [comment]
dupe #1190
