### ISSUE TITLE
Gingerbread Armor unobtainable

### ISSUE THREAD

**Issue by DaNecroa** [AlexModGuy/AlexsCaves#1355]
The issue is simple. When the Gingerbarrel is full of stolen ANY rare candy mentioned, nothing happens. Nothing is crafted. The Gingerbread Men don't do anything. No armor is made. You can test this right now. Have an inventory full of candy and let them steal it. I have NEVER even gotten 1 single piece. All barrels were full, up to 9 of any rare candy, yet nothing.

So it's busted, bugged? Or am I doing something wrong? Either way, if I need to upload a picture or anything then let me know. Nobody has said anything about this so I have absolutely no idea. If I find any other issues I'll report it but there's no way that this isn't a bug. And I did NOT put anything into the barrels, they put it themselves. Again if a picture is needed I can do that.

**Comment by Zer0-Rei** [comment]
That is not a bug. If my understanding is correct, Gingerbread Armor is crafted when the Gingerbarrel is filled with "9 types" of items that meet the criteria, rather than just when it is filled with items that meet the criteria.

**Comment by DaNecroa** [comment]
I understand what your saying but the problem is that I have already done that. Still nothing. The barrel has been filled with 9 or higher rare candy, nothing happens. Full? Has been completely full too. 9 types of candy your saying? I don't understand, I've done that too. It just doesn't work. I've already tried everything. Maybe it's a problem of mine then? I have no idea, also I should mention, getting 9 different types of candy into a Gingerbarrel is very difficult and time consuming, especially if they have to do it all by themselves, because sometimes they just stack items or don't take em at all.

**Comment by Zer0-Rei** [comment]
Gingerbread Armor is crafted when the Gingerbarrel contains 9 specific types of items, and I believe this process occurs every time Gingerbread Men add items. It does not happen when the player adds items. Additionally, if there are no empty slots when removing one of each of the 9 types of items, it is possible that Gingerbread Armor will not be crafted.
[video](https://d.kuku.lu/6axpzayd6)

**Comment by DaNecroa** [comment]
I think it works but man that description is so complicated, thanks for explaining it. Given that it worked once its probably an issue of mine or I did it wrong. Thanks for actually making it logical, I'll close this now
