### ISSUE TITLE
Tipped arrow of sugar rush isnt in the candy cavity creative menu

### ISSUE THREAD

**Issue by Nightfigure** [AlexModGuy/AlexsCaves#1359]
as the title states, the tipped arrow of sugar rush isnt in the candy cavity creative menu

**Comment by Zer0-Rei** [comment]
Intentional

**Comment by DaNecroa** [comment]
> Intentional

Definitely not. The potion exists in creative

**Comment by Zer0-Rei** [comment]
Please check if Tipped Arrows are present in the Magnetic Caves tab under Magnetizing, the Abyssal Chasm tab under Deepsight, and the Forlorn Hollows tab under Haste. They should not be there.

Tipped Arrows are classified under the Combat tab, so this is an intentional behavior and not a problem.

**Comment by DaNecroa** [comment]
Ah I thought they didn't exist at all. If they're in the combat section then yeah it makes sense. I just have never checked
