### ISSUE TITLE
Caves appearing on surface when using william wythers expanded ecosphere

### ISSUE THREAD

**Issue by gobies21** [AlexModGuy/AlexsCaves#1377]
caves are generating visible to the surface, sometimes even some blocks from the caves can be found on the surface as well.
![image](https://github.com/user-attachments/assets/dce138ea-65f9-491e-b62c-a0f67fbf8d94)
![image](https://github.com/user-attachments/assets/30405868-6d24-4551-b7e4-69c1e9e8105d)

**Comment by AlexModGuy** [comment]
fully intentional, you have to adjust the AC biome configuration limits in the mod's config when yo adjust how biomes generate
