### ISSUE TITLE
Biome Candy Only Works When Starving.

### ISSUE THREAD

**Issue by Cerinox** [AlexModGuy/AlexsCaves#1409]
I am unsure if someone else has already noted this here, but I have overheard it in the discord, and tested it myself, and the rumor is true.
Consuming a biome treat while not starving (with zero hunger points) in survival mode, will not give you any attuned biome treat whatsoever. 
However, it still does work, in the case you are starving, with exactly zero hunger points, or in creative.
I doubt this is intended, but if it is, please disregard this report.
Thank you for your time.

**Comment by X66Herobrine66X** [comment]
It's intended, unfortunately. They didn't even make Hunger V craftable to compensate, so we're all stuck slowly running down our hunger by punching and jumping like idiots.

**Comment by AlexModGuy** [comment]
intended
