### ISSUE TITLE
[Suggestion] All Hunger Potions (1, 2, 3, 4, not just 5)

### ISSUE THREAD

**Issue by DaNecroa** [AlexModGuy/AlexsCaves#1412]
Is this intentional? If so then it would be nice to add the other hunger potions. So this is more of a suggestion (modded recipes for how to get it)

**Comment by YocyCraft** [comment]
It's intentional. Licowitch throws hunger 5 potion, it's can't be crafted in brewing stand, so there's no need for hunger 1-4.

**Comment by DaNecroa** [comment]
Well thats the thing. If 1-4 existed, people could make modded recipes for it. But it's not happening?? If not, I'll just close this then

**Comment by X66Herobrine66X** [comment]
> It's intentional. Licowitch throws hunger 5 potion, it's can't be crafted in brewing stand, so there's no need for hunger 1-4.

It should be able to be crafted with licoroot to making using the biome treats easier.

**Comment by AlexModGuy** [comment]
no bloat suggestions
