### ISSUE TITLE
Siren sound issue

### ISSUE THREAD

**Issue by Rowan0001** [AlexModGuy/AlexsCaves#144]
If a nuclear bomb is detonated then a siren is placed before it goes off the audio will loop even when the siren is destroyed. In the same world I flew far away to avoid the noise and placed a new siren before detonating another nuke which resulted in a crash.
here is the crash report:
[crash-2023-10-20_17.01.34-client.txt](https://github.com/AlexModGuy/AlexsCaves/files/13050565/crash-2023-10-20_17.01.34-client.txt)

**Comment by KarolOfGutovo** [comment]
Similar issue happens when a siren is powered by redstone and then destroyed.

**Comment by AlexModGuy** [comment]
dupe same crash as #158
