### ISSUE TITLE
Mob spawning crashing, Book crashing, Worldgen crashing

### ISSUE THREAD

**Issue by ThyHeroBro** [AlexModGuy/AlexsCaves#145]
Raycat: crashes the game after being spawned and the world it has spawned in is unplayable because it crashes on loading. Error message: The game crashed whilst rendering entity in world
Error: java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.Object2IntMap.getInt(Object)" because "this.uniformCache" is null
Ferrouslime: crashes the game after being spawned and the world it has spawned in is unplayable because it crashes on loading. Error message: The game crashed whilst rendering entity in world
Error: java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.Object2IntMap.getInt(Object)" because "this.uniformCache" is null
Nucleeper: crashes the game after being spawned and the world it has spawned in is left unplayable due to crashing on loading. Error message: The game crashed whilst rendering entity in world
Error: java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.Object2IntMap.getInt(Object)" because "this.uniformCache" is null

Generating a world sometimes just doesn't work for unknown reasons, it either gets stuck on 100% or crashes when actually loading into the world

The biome compendium guide book crashes when being opened. Error message: The game crashed whilst rendering screen
Error: java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.Object2IntMap.getInt(Object)" because "this.uniformCache" is null

I can provide a list of mods i am using along side alex's caves, hope you can fix this soon

**Comment by AlexModGuy** [comment]
stop using old version of rubidium
