### ISSUE TITLE
Add Atroxolossus

### ISSUE THREAD

**Issue by mZiyadhbinismail** [AlexModGuy/AlexsCaves#1450]
![IMG_20241130_192821](https://github.com/user-attachments/assets/840af5bc-1b45-4645-b9b1-618074767532)
Atroxolossus is one of the most ancient mobsters in time.

**Comment by X66Herobrine66X** [comment]
As many people will tell you, Alex and his dev team do not take suggestions. Most suggestions have already been pitched multiple times, and they get repetitive and annoying. I recommend you close this to avoid wasting Alex's time, which is very limited as he spends it developing these mods.

**Comment by mZiyadhbinismail** [comment]
of my bad

**Comment by PlummetStudios** [comment]
Please stop.
