### ISSUE TITLE
Incorrect coordinates

### ISSUE THREAD

**Issue by Mrzmoony** [AlexModGuy/AlexsCaves#1453]
Candy Cabity map takes me to Forlorn Hollows, i was on a server with a friend and we walked more than 3000 blocks and it turns out that the map took us where it was not, we opened the map in creative and generated another map and it kept taking us where it was not
Minecraft: 1.20.1
Forge:1.20.1 47.3.12
Alex's Caves: 2.0.2

**Comment by PlummetStudios** [comment]
Unfortunately known issue
