### ISSUE TITLE
After adding alexs caves biomes in other dimensions structures do not spawn

### ISSUE THREAD

**Issue by norbertmyrta98** [AlexModGuy/AlexsCaves#1459]
After adding alexs cave biomes in other dimensions in the configuration files the structures and flora from AC do not spawn, also in spectator mode the mobs do not spawn.
![obraz](https://github.com/user-attachments/assets/cca2dc43-570e-4e94-a1e6-d6b420203746)

alex caves 2.0.2
citadel 2.6.0

**Comment by PlummetStudios** [comment]
Works as intended, the structures/mobs are designed to spawn within certain dimensions
