### ISSUE TITLE
What does depth mean in the config file.

### ISSUE THREAD

**Issue by BuzzyB3E** [AlexModGuy/AlexsCaves#1465]
I have seen a single person or anyone else ask what depth means in the config files. I need an answer, does 1 mean like 100 blocks or something? Or does 1 mean  at the very bottom of the world? Im using the mod with a mod the increases the world depth and i want some of the biomes to be near the bottom of the world. **TLDR**: what does depth mean in the config file?

**Comment by BuzzyB3E** [comment]
Okay now im even more confused. 1 does not equal bottom of the world or something i checked the depths of the rest of the biomes and some of them have 1.5 so now im just even more confused :(

**Comment by PlummetStudios** [comment]
Not the place for this question, this is for bugs.
