### ISSUE TITLE
Mobs turning invisible - Client mod incompatibility [?]

### ISSUE THREAD

**Issue by Crazy-Elipsis** [AlexModGuy/AlexsCaves#148]
**Mod:** Fusz' "Paper Doll" mod
https://www.curseforge.com/minecraft/mc-mods/new-paper-doll

**Mod description:** _"Paper Doll shows a small little display of yourself in a corner of the screen while you are performing certain actions, just like on the Bedrock Edition of Minecraft. The doll is shown for actions such as: sprinting, swimming, crouching, crawling, flying, and gliding. Many more actions are available in the config along with many display setting for the paper doll."_

**Issue:** Enemies turn invisible once the players is irradiated. However, this only happens when the paper doll's player animation shows on screen.

![image](https://github.com/AlexModGuy/AlexsCaves/assets/148471848/7804b62c-841b-4437-a59a-21e055ff23db)
![image](https://github.com/AlexModGuy/AlexsCaves/assets/148471848/a90b6d31-3efa-4982-a393-8af46c152624)

**Comment by AlexModGuy** [comment]
dupe #49
