### ISSUE TITLE
My game doesn't launch, it crashes instantly

### ISSUE THREAD

**Issue by imklio** [AlexModGuy/AlexsCaves#151]
I don't have any other mod with it, it's just Alex Cave's Mod.

**Comment by AlexModGuy** [comment]
any log?

**Comment by yoopgim** [comment]
have the exact same issue, game opens up, loads a bit on the loading screen, then crashes without a log

**Comment by imklio** [comment]
> any log?
![image](https://github.com/AlexModGuy/AlexsCaves/assets/148546473/820eb817-a914-423a-a160-c200529af133)

**Comment by imklio** [comment]
literaly, error code: 1

**Comment by yoopgim** [comment]
i think i figured it out: whatever it is is because of citadel, i only have citadel enabled and it crashes

**Comment by imklio** [comment]
> i think i figured it out: whatever it is is because of citadel, i only have citadel enabled and it crashes

what's citadel?

**Comment by yoopgim** [comment]
the core mod for rats, ice and fire, alex's mobs, alex's caves, and more of alex's mods

**Comment by imklio** [comment]
> the core mod for rats, ice and fire, alex's mobs, alex's caves, and more of alex's mods

oh, didn't know i had to have it on

**Comment by yoopgim** [comment]
yeah, but the issue is that citadel is causing the crash by the looks of it, so its impossible to play alex's cave for some reason

**Comment by Gwen-digo** [comment]
having the same issue, posted it in other forms but here's my crash report

[alexcavecrash.txt](https://github.com/AlexModGuy/AlexsCaves/files/13061478/alexcavecrash.txt)

**Comment by AlexModGuy** [comment]
dupe #229
