### ISSUE TITLE
Alex Caves 1.0.3 biomes not generating? due to BetterX world type/Dawn API?

### ISSUE THREAD

**Issue by HaizUber** [AlexModGuy/AlexsCaves#155]
Forge: 47.1.3
Embeddium 0.2.2
Oculus 1.6.9

If this helps, I have Sinytra Connector (https://modrinth.com/mod/connector) installed and a bunch of fabric mods

No matter how far away I TP away from spawn (tried 10k blocks - 20k blocks away) can't seem to /locate biome the new alex's caves biomes, also tried to start new worlds but still cant find them, always says can't find within reasonable distance. I have Biomes o Plenty, Biome Makeover and Regions Unexplored Installed and since I have Sinytra Connector installed, Promenade, Better Nether&End. Could this be due to the world type set to BetterX (since i have Better Nether& End installed) or due to the Biome mods such as Biomes o Plenty, Biome Makeover and Regions Unexplored?

My modlist if it helps: https://gist.github.com/HaizUber/3bce28c588d8e921987408b76dc8b522

**Comment by A00826925** [comment]
i have tried without bop, terralith, terrablender and no luck. it might just be betterX

**Comment by HaizUber** [comment]
From looking at other reports, seems to be an issue with Dawn API, a dependency mod required by Promenade

**Comment by AlexModGuy** [comment]
update citadel to 2.4.7
