### ISSUE TITLE
Biomes not generating when using other mods.

### ISSUE THREAD

**Issue by Roseanne-Pierre** [AlexModGuy/AlexsCaves#161]
I was trying to create a modpack using Alex's Caves and 20 other mods. However, when I did the /locate biome command to find the biomes in the world. It didn't work. It tried in multiple places for away from each other and all 5 of them but to no success.
![the bug](https://github.com/AlexModGuy/AlexsCaves/assets/134646630/c21feb01-347d-44e4-a1c6-6693d18f3e2f)

**Comment by AlexModGuy** [comment]
dupe issue
