### ISSUE TITLE
Huge fps drop 

### ISSUE THREAD

**Issue by JSPater** [AlexModGuy/AlexsCaves#168]
I've played the mod for some time and i think that when looking at the Ray Cats, the fps drops to 90 to 20/15. I changed some visual settings but nothing works, maybe it's the mob's glow.

Thanks for reading.

**Comment by DonorKrovi** [comment]
> I've played the mod for some time and i think that when looking at the Ray Cats, the fps drops to 90 to 20/15. I changed some visual settings but nothing works, maybe it's the mob's glow.
> 
> Thanks for reading.

https://youtu.be/lnqNm8YDw9Y

**Comment by Skiafray** [comment]
I've also noticed that Fps drops in the toxic caves happen while in spectator mode. going from 70-90 to 20fps is awful.

**Comment by BreadieSB** [comment]
I have the same thing with any instance of the irradiated effect plus the ray gun's beam, though strangely only when my game is in fullscreen, presumably due to the higher resolution.

**Comment by AlexModGuy** [comment]
dupe
