### ISSUE TITLE
Game Crashes when launching

### ISSUE THREAD

**Issue by thetheJ** [AlexModGuy/AlexsCaves#170]
its exit code 1, no crash report, im using forge 47.2.1, and the newest version of alex's caves

**Comment by AlexModGuy** [comment]
theres got to be a crash report

**Comment by thetheJ** [comment]
> theres got to be a crash report

idk i cant find it

**Comment by Gwen-digo** [comment]
having the same issue, put it in a different thread already but here's my crash report

[alexcavecrash.txt](https://github.com/AlexModGuy/AlexsCaves/files/13061414/alexcavecrash.txt)

**Comment by thetheJ** [comment]
NVM I FORGOT TO DOWNLOAD A DEPENDENCY

**Comment by thetheJ** [comment]
I THINK
