### ISSUE TITLE
mod crashes

### ISSUE THREAD

**Issue by KnotZero** [AlexModGuy/AlexsCaves#172]
[crash-2023-10-20_19.46.51-client.txt](https://github.com/AlexModGuy/AlexsCaves/files/13056571/crash-2023-10-20_19.46.51-client.txt)
List of mods: 
![image](https://github.com/AlexModGuy/AlexsCaves/assets/144356897/716465f6-e9d1-4af5-af82-f05d6ce5a29b)
![image](https://github.com/AlexModGuy/AlexsCaves/assets/144356897/de89f123-07b0-4f7f-979d-572cb0d2ccb8)

randomly crashes in-game

**Comment by AlexModGuy** [comment]
bug with latest rubidium see #78

**Comment by KnotZero** [comment]
> bug with latest rubidium see #78

Nope, still doesnt fix it, created a new world and all that, here's the crash report
[crash-2023-10-20_20.27.06-client.txt](https://github.com/AlexModGuy/AlexsCaves/files/13056798/crash-2023-10-20_20.27.06-client.txt)

**Comment by KnotZero** [comment]
Yeah, 100% positive this doesnt fix my issue.
[crash-2023-10-20_20.37.39-client.txt](https://github.com/AlexModGuy/AlexsCaves/files/13057009/crash-2023-10-20_20.37.39-client.txt)
