### ISSUE TITLE
Game Crashes

### ISSUE THREAD

**Issue by Idislike** [AlexModGuy/AlexsCaves#18]
[hs_err_pid5040.log](https://github.com/AlexModGuy/AlexsCaves/files/13043095/hs_err_pid5040.log)
Ive only got alex's caves and citadel installed yet minecraft crashes. I am on 1.20.1 forge.

**Comment by minifoca** [comment]
i'm having the same problem pls someone help :C

**Comment by AlexModGuy** [comment]
Use forge 47.1.3 or later
looks like youy might need to add more memory too
