### ISSUE TITLE
Server crash when trying to load Primordial Caves

### ISSUE THREAD

**Issue by Chloethecat** [AlexModGuy/AlexsCaves#187]
I am having server crashes when trying to load a Primordial Caves biome the console will say Timed out waiting for world statistics am currently using the prominence 2 modpack with a few extra mods
[crash-2023-10-20_01.42.19-server.txt](https://github.com/AlexModGuy/AlexsCaves/files/13058293/crash-2023-10-20_01.42.19-server.txt)

**Comment by Eletoast** [comment]
Server crash is due to incompatibility with Twigs mod.

**Comment by AlexModGuy** [comment]
dupe #84
