### ISSUE TITLE
Targeting entities with Nucleepers crashes the game

### ISSUE THREAD

**Issue by epiktechno** [AlexModGuy/AlexsCaves#194]
using the totem of possession on nucleepers and targeting a entity will *always* crash the game when they begin to arm (when their head is closing)

discovered it by messing around with the totem and wanted to see how nucleepers reacted, causing this crash which always occurs when you hold the totem on the targeted entity

**Comment by AlexModGuy** [comment]
crash log?

**Comment by epiktechno** [comment]
> crash log?

"java.util.ConcurrentModificationException: null"



[crash-2023-10-20_18.40.30-client.txt](https://github.com/AlexModGuy/AlexsCaves/files/13061463/crash-2023-10-20_18.40.30-client.txt)
