### ISSUE TITLE
all alex caves mobs despawn when entering spectator

### ISSUE THREAD

**Issue by greztrez** [AlexModGuy/AlexsCaves#197]
makes it a tad hard when recording/editing together a video and trying to get good angles on the mobs. switching from creative to spectator mode. happens to all alex cave's mobs, and strangely enough, glowsquids as well. latest build of AC

edit: lol can't upload a video cause of the dogshit 10 MB limit.

**Comment by PlummetStudios** [comment]
This is how the default minecraft spawning/unspawning system works
