### ISSUE TITLE
Alex Caves Crash with my modpack

### ISSUE THREAD

**Issue by jgame38** [AlexModGuy/AlexsCaves#2]
I have downloaded the last version of citadel and I use Forge 47.2.0, but I can't launch minecraft with Alex cave,
Here is my crash report.
[crash-2023-10-19_10.02.21-client.txt](https://github.com/AlexModGuy/AlexsCaves/files/13039747/crash-2023-10-19_10.02.21-client.txt)

**Comment by AlexModGuy** [comment]
dupe #1
