### ISSUE TITLE
Occasionally, Caves May Be Too Small

### ISSUE THREAD

**Issue by ChrisLTheNerd** [AlexModGuy/AlexsCaves#201]
With the default configs (and maybe other internal terrain gen settings), caves like the Foglorn Hollows can be really small and basically split apart by a hundred blocks. It also happens with Toxic caves, but it's issue is mostly that it's to split apart to travel through and not it's size. With how rare the caves are, I think it would be more fair to have bigger and more traversable ones. I haven't really seen the issue with the other caves, especially the primordial caves.
![2023-10-20_19 47 03](https://github.com/AlexModGuy/AlexsCaves/assets/50182206/6b0a44df-df6e-4b25-ac04-c1561f7fe0c6)
![2023-10-20_19 48 28](https://github.com/AlexModGuy/AlexsCaves/assets/50182206/e928e8d6-458b-49a3-8553-dd2175328246)
![2023-10-20_19 49 38](https://github.com/AlexModGuy/AlexsCaves/assets/50182206/587d36a0-971f-4f3e-ae85-4337dd06529d)
Most of the time it's fine and spawns very decently sized caves.
![2023-10-20_20 19 51](https://github.com/AlexModGuy/AlexsCaves/assets/50182206/dd07fdd6-5fed-4c87-9bf0-d9d27089f201)

**Comment by AlexModGuy** [comment]
dupe

**Comment by ChrisLTheNerd** [comment]
Yup, just noticed and it was about to close it myself.
