### ISSUE TITLE
Biomes are unnecessarily rare

### ISSUE THREAD

**Issue by Brodend1** [AlexModGuy/AlexsCaves#203]
While I understand the need for the biome rarity, assuming it's intended, there are many issues this rarity does not accommodate. I searched for around 10,000 blocks, IN CREATIVE, and even the locate biome or maps didn't find many biomes. Not only that, but I found a toxic cave and forlorn hollows, they were tiny, with only a few open spaces and the the majority was just solid ground. Imagine spending all the resources and time to find these biomes in survival, to get a solid rock of a biome without any actual caves. If any casual players play this mod in survival, they will likely never see the majority of its features, as finding one biome that happens to generate properly, in a reasonable distance, and has enough open space is too much to ask for a normal player. Either add smaller more frequent biomes to fill in the gaps between finding these exceedingly rare biomes,  make the biomes more common so players can actually find them, or at least make sure they generate big and open enough to accommodate for the effort of the player.

**Comment by Eletoast** [comment]
There is a config that allows you to tweak the sizes and spacing of the caves. I'd recommend taking a look at it as its pretty straight forward and simple.

**Comment by kekis1234** [comment]
uhh...what do you mean you locate biome can't find many biomes, every time i use it i have a new one, plus it would be too boring if you would find all these caves in couple of minutes

**Comment by Brodend1** [comment]
> uhh...what do you mean locate biome can't find many biomes, every time i use it i have a new one, plus it would be too boring if you would find all these caves in couple of minutes

I teleported across almost 10,000 blocks in all axis, and the locate biome or maps could barely find any biomes, with exceptions of the super small forlorn hollows and toxic caves.

**Comment by Eletoast** [comment]
The caves are intended to be rare, encouraging cave exploration to find underground cabins. The spacing of caves can be changed in the mod config, so if you struggle to find biomes, tone down the spacing.
