### ISSUE TITLE
Issues with rubidium and alex caves

### ISSUE THREAD

**Issue by Tookyyy** [AlexModGuy/AlexsCaves#205]
When i open the book cave compendium. the game crashes. I removed rubidium and the game stoped crashing when i open it. I dont know if is rubidium or alex caves

[crash-2023-10-20_22.42.47-client.txt](https://github.com/AlexModGuy/AlexsCaves/files/13059578/crash-2023-10-20_22.42.47-client.txt)

**Comment by Eletoast** [comment]
I recommend using embeddium, as its virtually the same as rubidium but with some extra enhancements that make the game perform better.

**Comment by AlexModGuy** [comment]
dupe
