### ISSUE TITLE
Chance to obtain Sea Glass Shards from Muck isn't increased with Fortune Enchantment

### ISSUE THREAD

**Issue by Inonedn** [AlexModGuy/AlexsCaves#209]
in Vanilla, Gravel has a higher chance of giving Flint when mined with a Fortune tool, with the chance being guaranteed when Fortune 3 is used.

**Comment by PlummetStudios** [comment]
Fortune does increase chance of obtaining sea glass shards, just not a guarantee/as much as flint from gravel.
