### ISSUE TITLE
Doesnt work with Big Modpacks past a certain amount

### ISSUE THREAD

**Issue by rainysux** [AlexModGuy/AlexsCaves#210]
Update: I tried these mods by themselves and it seems to work, it is probably another mod that it is conflicting ALL THESE MODS, I am now switching my focus to finding whats causing it
In my modpack it causes the caves unable to be found through /locate. However from what I can see it still seems to generate? 
(I would prefer Ad Astra to be fixed first :3 
Also doesnt work with ad astra giselle mod
https://www.curseforge.com/minecraft/mc-mods/ad-astra-giselle-addon
Bookshelf: https://www.curseforge.com/minecraft/mc-mods/bookshelf
Bartering station https://www.curseforge.com/minecraft/mc-mods/bartering-station
Now found that its incompat with BagusLib
https://www.curseforge.com/minecraft/mc-mods/bagus-lib
Creeper Overhauled https://www.curseforge.com/minecraft/mc-mods/creeper-overhaul
Cristel Lib: https://www.curseforge.com/minecraft/mc-mods/cristel-lib/files?page=1&pageSize=20&version=1.20.1
Controlling: https://www.curseforge.com/minecraft/mc-mods/controlling
Corpse: https://www.curseforge.com/minecraft/mc-mods/corpse
Creative Core https://www.curseforge.com/minecraft/mc-mods/creativecore
Craterlib https://modrinth.com/mod/craterlib
Cosmetic Armor Reworked https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked/files?page=1&pageSize=20&version=1.20.1
Collective
Cluttered
(They all cause the same issue and I think more as well)

**Comment by rainysux** [comment]
![2023-10-20_21 07 57](https://github.com/AlexModGuy/AlexsCaves/assets/113203852/2e84283c-c7ff-4416-b351-8190d9eecd15)
Or its possible it stops generation but doesnt delete the caves that generated.

**Comment by rainysux** [comment]
I tp'd to the cave without bartering station and got to the cave, and then removed it and took the previous screenshot I showed and this 
![2023-10-20_21 11 30](https://github.com/AlexModGuy/AlexsCaves/assets/113203852/31076086-7de5-4360-bfce-32e484a9e7f7)
![2023-10-20_21 12 06](https://github.com/AlexModGuy/AlexsCaves/assets/113203852/5629e3d4-6fce-4b25-bd1b-10afb1c64b75)

**Comment by rainysux** [comment]
Also doesnt work with Ad astra/ad astra giselle mod

**Comment by rainysux** [comment]
Now found that its incompat with BagusLib 
https://www.curseforge.com/minecraft/mc-mods/bagus-lib

**Comment by rainysux** [comment]
Okay nevermind, its just a Duplicate of https://github.com/AlexModGuy/AlexsCaves/issues/141

**Comment by Hadryan505** [comment]
Did u find the mod that was causing conflict?

**Comment by rainysux** [comment]
It turned out to be just once your modpack reaches 358 mods in game. No matter what you turn on or off, it will be unable ti generate them. However I do know if you were using cinderscape/promenade with connector. That would stop it as well but it was passed to Alex as a citadel issue which he hopefully will fix
