### ISSUE TITLE
Frame drop when the glowing effect is applied

### ISSUE THREAD

**Issue by GloriousCouchPotato** [AlexModGuy/AlexsCaves#216]
So when in game there's a large frame drop from around 126 frames to 26 and below, it happens when the glowing green effect is applied to any entity in the world, the ray gun causes entities to temporarily disappear.

**Comment by tonypraf** [comment]
yeah same

**Comment by JSPater** [comment]
I got 90 fps to 20/15 because of this, i Even made my base above a toxic cave and just looking down is horrible

**Comment by AlexModGuy** [comment]
dupe #214
