### ISSUE TITLE
Crash near the Forlorn Hollows.

### ISSUE THREAD

**Issue by prsonne33** [AlexModGuy/AlexsCaves#220]
When im near a Forlorn Hollows cave i crash and i get this crash reporte :

The game crashed whilst encountered exception while building chunk meshes
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.client.renderer.texture.TextureAtlasSprite.m_118367_(double)" because "sprite" is null

**Comment by AlexModGuy** [comment]
dupe #78
