### ISSUE TITLE
when in spesific place in toxic caves game crashes

### ISSUE THREAD

**Issue by HOMSONM** [AlexModGuy/AlexsCaves#225]
when in spesific place/area in toxic caves game crashes
I added more memory and it still crashes ,aslo I cheked if any viruses still nothing
I use curse forge luncher maby this is the thing 
 
Crash report:
exit code -805306369

more info 
https://bugs.mojang.com/browse/MC-23484

**Comment by AlexModGuy** [comment]
send the crashr eport
