### ISSUE TITLE
Random air blocks in water

### ISSUE THREAD

**Issue by ItsOreoIsEatable** [AlexModGuy/AlexsCaves#227]
![2023-10-21_17 26 10](https://github.com/AlexModGuy/AlexsCaves/assets/148640898/40776c99-308e-4b23-a5ab-d40c71a4c034)

seed: -2422483150380552603 at /execute in minecraft:overworld run tp @s -4728.08 -38.40 -808061.47 -212.65 39.59. Im in an abyssal chasm btw

**Comment by AlexModGuy** [comment]
dupe
