### ISSUE TITLE
Alex's Caves is incompatible with Deeper Caves ( previously Caves & Depths )

### ISSUE THREAD

**Issue by theplayerthatexists** [AlexModGuy/AlexsCaves#232]
Whenever I load up a world with this mod enabled, none of the caves from alex's caves will generate within any spot in the world. The maps will not load, saying that you need to travel farther and /locate biome commands won't detect the caves.

**Comment by peepeepoopoocaca** [comment]
Is there any chance that you're using Terrablender or a mod similar to it? Terrablender seems to be the root of the caves not spawning. Disabling Deeper Caves doesn't seem to fix this issue for me.

**Comment by theplayerthatexists** [comment]
I am using terrablender, but it seems that this mod is the cause of the issue. When I disabled it, alex's caves seems to have started generating in the world again. I even tried this mod without terrablender and the same issue arose.

**Comment by peepeepoopoocaca** [comment]
That's odd. It seems to be the other way around for me. Do you have any other mods that affect terrain generation?

**Comment by AlexModGuy** [comment]
update citadel to 2.4.7
