### ISSUE TITLE
Game Crash upon a player hearing multiple nuclear sirens

### ISSUE THREAD

**Issue by NRH2007** [AlexModGuy/AlexsCaves#234]
I was intending to use multiple nuclear sirens to create that overlapping effect you sometimes hear, and it worked once before the game crashed with a sound engine error. I got the crash once again, but when the game does not crash it simply refuses to play the nuclear siren SFX for the other sirens, and even sometimes registers extra sirens that dont exist, playing the SFX infinitly from a point in the world (recording attached)

Crash happened on 1.20.1, forge version 47.2.1
To replicate:
1: Place down two or more nuclear sirens nearby each other
2: connect them all to one lever, with one or more connected via a redstone repeater to create a delay
3: Activate the lever and experience one of these effects. I cannot provide any more help as the bug is VERY finicky.

Logs are from an instance where all 3 bugs happened at once, recording is from some initial testing in a modpack i had built. I had attempted to blow up the offended blocks with TNT, but this did not help.
[latest.log](https://github.com/AlexModGuy/AlexsCaves/files/13061556/latest.log)
[crash-2023-10-21_14.01.13-client.txt](https://github.com/AlexModGuy/AlexsCaves/files/13061557/crash-2023-10-21_14.01.13-client.txt)

https://github.com/AlexModGuy/AlexsCaves/assets/109614266/68fde48f-c80c-494b-8457-9fb62a2cc1b4

(apoligies for the watermark, i had to compress this video 3 goddamn times to get it small enough for github) (I probably shouldve used imgur or something lol)

**Comment by AlexModGuy** [comment]
fixed in 1.0.4

**Comment by NRH2007** [comment]
ah, guess it hasnt quite dropped on curseforge yet lol, thanks for letting me know,.
