### ISSUE TITLE
mod causes shader skies to appear white 24/7

### ISSUE THREAD

**Issue by Frroqqy** [AlexModGuy/AlexsCaves#239]
i had to do a whole process of elimination for this to find it was alexs caves </3 basically the sky turns white when i use alexs caves and nothing i can do (except turn off my shader) will fix it - im using astralex by lexboost btw

**Comment by Frroqqy** [comment]
i went to the config and toggled anything that said "may conflict with shaders" to false and it still didnt help

**Comment by DarkPuppet74** [comment]
I have the same problem man, and another this is that when in primordial cave and folorn hollow all the blocks become transparent
