### ISSUE TITLE
Toxic Caves biome map not working

### ISSUE THREAD

**Issue by StrangerSon71** [AlexModGuy/AlexsCaves#240]
I crafted a biome map to the Toxic Caves, and went to where it said. There were no Toxic Caves, and /locate confirmed this. I tested again in a different Creative world, and every map except Toxic Caves led me where it was supposed to. After I had gone a fair distance from spawn, I tried another Toxic Caves map, and it did successfully bring me to a Toxic Cave. I did have some other mods including Galosphere, if that's relevant. I don't have time to test without Galosphere right now, I could possibly test later but there's no guarantee.

**Comment by AlexModGuy** [comment]
update citadel to 2.4.7
