### ISSUE TITLE
Armor Stand Issues

### ISSUE THREAD

**Issue by Jacktastic09** [AlexModGuy/AlexsCaves#249]
Placing the hood/cloak of darkness on an armor stand causes the limbs of all armor stands to disappear. a method to fix the issue is to reloading resources and exiting a world doesn't fix it.
![2023-10-22_13 38 04](https://github.com/AlexModGuy/AlexsCaves/assets/148667265/7f8da392-fd8d-4be3-a823-f934d6361f19)
![2023-10-22_13 38 16](https://github.com/AlexModGuy/AlexsCaves/assets/148667265/86c204b5-2624-4810-a2cd-53999d366053)
![2023-10-22_13 38 28](https://github.com/AlexModGuy/AlexsCaves/assets/148667265/8e98a0ff-e301-4945-8c9b-72ee96c4a6be)

**Comment by AlexModGuy** [comment]
dupe #98
