### ISSUE TITLE
Burrowing arrow Grief don't fixed

### ISSUE THREAD

**Issue by DonorKrovi** [AlexModGuy/AlexsCaves#254]
https://github.com/AlexModGuy/AlexsCaves/issues/166

Unfortunately this fix doesn't work, I suggest adding the ability to disable terrain for servers

Even if the entity was fired from a bow

**Comment by AlexModGuy** [comment]
the arrow has to dig, it's a tool/weapon.

it only wont dig if a mob, like a skeleton, shoots it from a bow
