### ISSUE TITLE
Hazmat Helmet is covered by the outer layer of the player's skin

### ISSUE THREAD

**Issue by ghost** [AlexModGuy/AlexsCaves#256]
![image](https://github.com/AlexModGuy/AlexsCaves/assets/54410635/ea3d5172-e26d-4143-8249-90c0142f229c)
My hair on the outer layer is visible over the helmet's overlay. Given most people use the 2nd layer on their skins, especially for their heads, this seems like an issue to me.

**Comment by AlexModGuy** [comment]
fixed
