### ISSUE TITLE
The Cave Tablets for primordial caves and toxic caves are too similar for me to tell apart

### ISSUE THREAD

**Issue by TomatoSoupter** [AlexModGuy/AlexsCaves#257]
For context. I have a hard time telling apart greens from yellows and blues and purples. The toxic and primordial cave tablets are colored too similary for me to tell them apart at first glance. In fact I have to look at them side-to-side to tell them apart, and even then I have to squint to see it. It would be nice if the toxic caves tablet colors were more of a brighter green, to make it similar to the glowing acid present in that biome. I feel this would help colorblind people like myself.

**Comment by AlexModGuy** [comment]
they tell you what they are when you translate them into codices

**Comment by TomatoSoupter** [comment]
Yes but I'm not referring to that. I am referring to the coloration of those items being too similar for primordial caves and toxic caves, when the other tablets are easy to distinguish from one another.
