### ISSUE TITLE
bugs i found 

### ISSUE THREAD

**Issue by IJMUNDI** [AlexModGuy/AlexsCaves#259]
I have the ram available for minecraft set to 10gb and even then i crashed while being in the abbysal depths, there's a chance it was caused by the hullbreaker since i saw it and i crashed but i spawned it in creative and it didn't crash at all 

(sorry if there's bad english)

https://github.com/AlexModGuy/AlexsCaves/assets/148695604/d5ee0862-7eb1-4699-8037-ba39dfca9e8e

**Comment by IJMUNDI** [comment]
checked in creative, the mob i saw is a hullbreaker but it doesn't crash when o spawn it in a super flat world (i tested with the other mobs that were nearby and it didn't crash neither)

**Comment by IJMUNDI** [comment]
when you spawn the raycat (idk if this is a bug or feature) all mobs (except the brainiac) and the UI dissapear including health armor hot bar and item you're holding

**Comment by AlexModGuy** [comment]
dupe

**Comment by IJMUNDI** [comment]
shit sorry :(
