### ISSUE TITLE
Relicheirus Tree Chopping

### ISSUE THREAD

**Issue by EnderKill101117** [AlexModGuy/AlexsCaves#263]
When a Relicheirus chops down a tree, the logs are Jungle instead of Pewen.

**Comment by DoctorWafflePhD** [comment]
I haven't had this issue. Are you sure that it's not breaking the Jungle trees that spawn within the biome? Some of the trees are made of Jungle Logs and Ancient Leaves. The Pewen trees are the tall ones with branches and no leaf blocks.
