### ISSUE TITLE
underground cabin maps often dont have an X to mark the location of the cabin on the map making them useless

### ISSUE THREAD

**Issue by dudeguy57** [AlexModGuy/AlexsCaves#272]

**Comment by Driestcombee** [comment]
this happens to me too
![image](https://github.com/AlexModGuy/AlexsCaves/assets/142123085/2ee485ad-cadf-4962-aa67-6663576bd9c9)

**Comment by Driestcombee** [comment]
![image](https://github.com/AlexModGuy/AlexsCaves/assets/142123085/8d47efef-d4bf-4d36-a905-897b751e9461)
another example
