### ISSUE TITLE
[1.20.1 Forge] Missing various tag entries for better mod compat

### ISSUE THREAD

**Issue by TelepathicGrunt** [AlexModGuy/AlexsCaves#274]
In addition to the missing [cave tags](https://github.com/AlexModGuy/AlexsCaves/issues/104) and [overworld tags](https://github.com/AlexModGuy/AlexsCaves/issues/107), there are more missing tags or at least, tags I feel should be populated with Alex's Caves stuff.

- Ancient Sapling, Thornwood Sapling, and Pewen Sapling to `minecraft:saplings` tag.

- Bone Worms, Underweed, Tree Star, Fiddlehead, Curly Fern, and Pewen Pines to `minecraft:replaceable` tag so other mods know they can replace these blocks safely like they do for grass.

- Underweed, Tree Star, Fiddlehead, Curly Fern, and Pewen Pines to `minecraft:replaceable_by_trees` tag so trees can grow and not be blocked by these blocks.

- Primordial Caves to `forge:is_lush`.

- Forlorn Hollows to `[forge:is_spooky](https://github.com/TelepathicGrunt/TACT)`.

- Magnetic Caves to `forge:is_sparse/overworld` to signal no vegetation spawns here.

- Toxic Caves to `forge:is_wasteland`.

**Comment by AlexModGuy** [comment]
not sure on the use case for forge:is_lush. is this only for biomes similar enough to the lush caves? since I don't think the primordial caves would fall under that.

**Comment by TelepathicGrunt** [comment]
My understanding is forge:is_lush is for high dense underground vegetation caves that are conductive to life. It would explain why lush caves are in it but not jungle.

Since Primordial Caves are dense in plant life and has water, etc, I felt it made sense to add Primordial Caves to the tag. It would be ideal if mods that are adding mobs like Glare to lush caves are using the is_lush tag. So that Glare can spawn in Primordial Caves and become dino food lol
