### ISSUE TITLE
when my game tries to load the primordial cave biome, the game stops loading stuff

### ISSUE THREAD

**Issue by broz21** [AlexModGuy/AlexsCaves#277]
i was exploring around to go in a primordial cave but when i arrived, the game stopped loading chunks, mobs cannot move and blocks don't drop

**Comment by AlexModGuy** [comment]
dupe #187

**Comment by broz21** [comment]
Wait, you fixed it?


Le dim. 22 oct. 2023, 5 h 38 p.m., Alexthe668 ***@***.***> a
écrit :
