### ISSUE TITLE
Crash caused by (I believe) the sound from the siren when you activate a nuke

### ISSUE THREAD

**Issue by SireOfTheQuags** [AlexModGuy/AlexsCaves#278]
[crash-2023-10-23_00.51.06-client.txt](https://github.com/AlexModGuy/AlexsCaves/files/13064764/crash-2023-10-23_00.51.06-client.txt)

Using the latest 1.04 version.

**Comment by AlexModGuy** [comment]
try and disable nuclear_bomb_muffles_sounds in the alexscaves-client.toml config file and see if the issue persists. It will help me narrow down the issue.

**Comment by AlexModGuy** [comment]
let us know if the issue persists in 1.0.5

**Comment by EfrenB** [comment]
> try and disable nuclear_bomb_muffles_sounds in the alexscaves-client.toml config file and see if the issue persists. It will help me narrow down the issue.

The game still crashes in 1.0.5, I tried turning off the nuke sounds and fixed it, but I found another problem: the ambient sound of the toxic caves is now in the overworld after dying from a nuclear creeper lol.

**Comment by SireOfTheQuags** [comment]
I'm no longer crashing in the latest version even without disabling that config setting. Might still mean the bug exists, though. I just haven't encountered it since.

**Comment by Ladocterus** [comment]
[crash-2023-10-24_15.23.04-client.txt](https://github.com/AlexModGuy/AlexsCaves/files/13127991/crash-2023-10-24_15.23.04-client.txt)
I disabled the nuclear_bomb_muffles_sounds and still doesn't fix it
not sure if it's the same issue, mine's caused by a primed nucleaper & Siren

**Comment by kaboom24** [comment]
its happening to me too at first it stopped in the latest version but then when I tried it it my main world it crashed it seems like it usually happens when the siren sound plays when there are no sirens nearby I wound up having to delete the world :(
