### ISSUE TITLE
Hullbreaker no longer glows

### ISSUE THREAD

**Issue by StrangerDanger5811** [AlexModGuy/AlexsCaves#280]
The hullbreaker no longer glows, even during the looking animation. Worked in 1.0.3.
![image](https://github.com/AlexModGuy/AlexsCaves/assets/66227851/1aa15c3c-5912-461a-8d1e-cf8776c81b9d)

**Comment by AlexModGuy** [comment]
![2023-10-25_12 08 20](https://github.com/AlexModGuy/AlexsCaves/assets/8662109/d38f1a2c-5620-444f-b04a-62eaad521565)
still glows as of today. must be an incompatibility on your end with mods such as oculus, rubidium etc.
