### ISSUE TITLE
The new biomes aren't spawning

### ISSUE THREAD

**Issue by Hadryan505** [AlexModGuy/AlexsCaves#281]
I walked 40k blocks constantly using three different cave maps but none worked, it just said i needed to get further.
Tested it in other worlds and it didn't work either, also /locate didn't work too
My mod list:
![Screenshot_6](https://github.com/AlexModGuy/AlexsCaves/assets/144624610/ff46b208-d319-4121-a9d0-3345c12d37f3)

I also tried removing these mods but it didn't change anything

![Screenshot_5](https://github.com/AlexModGuy/AlexsCaves/assets/144624610/e278d66f-ca36-411e-b18e-5fff79bbd702)

**Comment by AlexModGuy** [comment]
update citadel to 2.4.7

**Comment by Hadryan505** [comment]
It doesn't work either :(
