### ISSUE TITLE
Datapack support for Nuclear Furnace Blasting

### ISSUE THREAD

**Issue by MichaelBrad** [AlexModGuy/AlexsCaves#284]
Less of an issue, but a really nice feature for modpack developers. Reason I bring it up is because Create, which I'm using in a modpack of mine with Alex's caves makes this multiblock obsolete, which is a shame cause it seems really cool.

**Comment by AlexModGuy** [comment]
it uses the data of the blasting furnace. any blasting furnace recipe should work out the box.

**Comment by MichaelBrad** [comment]
I mean adding a way to add a Nuclear Blast Furnace recipe separate from the Blast furnace
For example, if you wanted a modpack where you only could smelt ancient debris in the nuclear blast furnace, they could make a datapack that does just that, removing the blast furnace recipe for it, then adding a recipe exclusive to the nuclear blast furnace
I hope that makes sense lmao
