### ISSUE TITLE
Deep Ones are kinda dickheads honestly

### ISSUE THREAD

**Issue by ImpulsiveLad** [AlexModGuy/AlexsCaves#285]
From what I gather they are meant to be more elusive and possibly scared of players until they start to trade (or are attacked) but I'm noticing deeps ones just being completly hostile and not wanting to trade even when they were never once hit by the player
https://streamable.com/8fuqm8

**Comment by SireOfTheQuags** [comment]
They also attack when you get too close

**Comment by PeglinX** [comment]
That is an intended behavior. It sounds like you try to trade while being next to the altar. You need to stay away. 

Being near them agros them which is on purpose except for when you max reputation.

**Comment by BiggestBruhMoment** [comment]
Whats the required range for them to be aggroed? if im not mistaken when im playing around in creative and turn into survival they still attack you even if youre not being close to them.

I might misremember it and can check it again to make sure

**Comment by kaboom24** [comment]
aren't they supposed to run and throw ink bombs if you get near them while they are "cautious"
