### ISSUE TITLE
Various visual incompatibilities ?

### ISSUE THREAD

**Issue by LeKripiY** [AlexModGuy/AlexsCaves#287]
Alex's caves v1.0.4
Hello, I have some visual issues using your mod with I think rubidium or oculus.
First the neodymium particles follow the player's screen and aren't locked to the block, so it leads to this happening:
![image](https://github.com/AlexModGuy/AlexsCaves/assets/77859121/78ca3f9c-8b53-4701-9b0b-f1f8684fe481)

And then, there is also a glitch with the Peering Coprolith, the isinde glowing eyes aren't showing.
![image](https://github.com/AlexModGuy/AlexsCaves/assets/77859121/228ce4ca-bc40-4c7d-adb0-259493f99c6a)

Here is the mods that i'm using:
![image](https://github.com/AlexModGuy/AlexsCaves/assets/77859121/7a08548d-4148-49f3-ba82-a83a8ad37bce)
![image](https://github.com/AlexModGuy/AlexsCaves/assets/77859121/79ba46f6-18b8-400a-9928-0f3590fea85d)
![image](https://github.com/AlexModGuy/AlexsCaves/assets/77859121/7da561dc-21a0-4e2f-b31b-4e276e0ab2c8)
![image](https://github.com/AlexModGuy/AlexsCaves/assets/77859121/4199cd47-6f15-4e5f-bcdc-7a58f319a448)

**Comment by ErakAcheron** [comment]
I've experienced this issue with Embeddium + Occulus, but additionally I've noticed the lightning bolt particles from tesla bulbs, magnetic quarry markers and activated resistor shields are also missing.

**Comment by Sluggasaurus** [comment]
The peering coprolith specifically doesn't seem to want to work with embeddium at all.

**Comment by PeglinX** [comment]
The peering coprolith does work as an item but when placed it’s bugged

**Comment by Matteibu** [comment]
did anyone find a fix? I tried removing embeddium and replacing it with rubidium since it used to work, but no luck.

**Comment by Bvtterbean** [comment]
I'm also using Embeddium and Embeddium Extra with Oculus and I'm getting similar issues but with the lights in the ceiling in the Primordial Caves.

**Comment by BugmanBugman** [comment]
Anyone try reporting this to the embedding devs?
