### ISSUE TITLE
My game crashes when I go into the Toxic Caves when Rubidium is installed

### ISSUE THREAD

**Issue by RippAlex** [AlexModGuy/AlexsCaves#29]
My game crashes when I go into the Toxic Caves when Rubidium is installed, I went into spectator and as soon as I went into the biome it crashed and with Not Enough Crashes it said that Rubidium was the reason of the crash.

**Comment by RippAlex** [comment]
Without Rubidium my game is unplayable.

**Comment by RippAlex** [comment]
I saw you labeled it as closed, can I ask did you fix it?

**Comment by BugmanBugman** [comment]
try embeddium
