### ISSUE TITLE
Incompatibility with Ect.

### ISSUE THREAD

**Issue by Ladocterus** [AlexModGuy/AlexsCaves#295]
Etcetera (the mod) causes game freeze when generating certain caves, particularly Primordial and Abyss. 
Thought it seems that it's only generating the biomes are what freeze the game, and if the biomes were generated before Ect was installed it won't freeze the game.

**Comment by TheWitherlord** [comment]
Has anybody figured out why this is? What in the world???

**Comment by Ladocterus** [comment]
> Has anybody figured out why this is? What in the world???

are you asking technical reasons? or what mod causes it? I've narrowed it down to Etcetera  by Ninnih, the mod Twigs by the same creator is also reported to be incompatible.

**Comment by AlexModGuy** [comment]
dupe #84

**Comment by TheWitherlord** [comment]
> > Has anybody figured out why this is? What in the world???
> 
> are you asking technical reasons? or what mod causes it? I've narrowed it down to Etcetera by Ninnih, the mod Twigs by the same creator is also reported to be incompatible.

Technical, what in those two mods is causing this.
