### ISSUE TITLE
ForgifiedFabricAPI Support?

### ISSUE THREAD

**Issue by DonorKrovi** [AlexModGuy/AlexsCaves#3]
![image](https://github.com/AlexModGuy/AlexsCaves/assets/60231586/d3c3c8ee-d253-416f-9735-d5a40a2476dd)

![image](https://github.com/AlexModGuy/AlexsCaves/assets/60231586/78dc87d8-048f-4f58-bb0c-18a9019611da)

**Comment by Ryuco** [comment]
what a legend for fixing this right away
