### ISSUE TITLE
Game crashes when nuclear furnace reaches criticality. around its yellow and shaking phase

### ISSUE THREAD

**Issue by EmeraldGoose7** [AlexModGuy/AlexsCaves#307]
was given crash code -1 or something.

I wanted to let my world burn with cool unmaintained nuclear powerplants. however, as I went into my testing world, I was consistently being kicked from my game when each furnace becomes critical. The launcher for MC opens saying the game crashed. Hope this gets fixed soon so I can start oppenheiming

**Comment by AlexModGuy** [comment]
dupe #237
