### ISSUE TITLE
crash when using panda's falling trees

### ISSUE THREAD

**Issue by chamops** [AlexModGuy/AlexsCaves#314]
Crash when using PFT and AC and mining a tree in primordial caves. No crash when using a different "tree chop" mod that functions differently but is the same general concept, HTs treechop, however the ht's treechop function does not work w/ AC trees. Overall not a huge deal since Ht's Tree chop doesn't cause a crash, just thought I should mention it as a lot of people do use tree-chop type mods. PFT does seem to work off the bat with every single other modded tree I've used it with, including many that operate differently/have separate features added to them that are entirely different from vanilla trees (ie adding things like branches or having trunks that aren't made of full blocks). It's entirely possible this is an issue on their end, so if so I can report it there; the reason I believe it is one on AC's end is the point I made before about PFT working on trees that are not made in the same way as vanilla trees, specifically because I'm nearly positive Panda isn't directly adding compatibility to every individual mod that adds trees that function differently from vanilla trees as one of those mods I had downloaded just minutes after an update adding said features was released & did not need to update PFT. It is certainly possible the coder of the mod i'm referencing (regions unexplored) made them compatible before releasing though. Let me know if crash report is needed and I can recreate the crash I just lost the initial one lol

**Comment by AlexModGuy** [comment]
crash log?

**Comment by chamops** [comment]
Uhhhh this is awkward. When attempting to recreate the issue there is no crash now. Still no direct compatibility but that's fine, the crash was the only thing that impacted gameplay. I'll make a new issue if it arises again but maybe the citadel update fixed it, also possible the AC update released before the one that was released a few minutes ago fixed it and I just forgot to test before reporting. I probably should have checked that again before reporting, my bad boss have a good day.
