### ISSUE TITLE
Nucleeper Crash - 1.0.5 build.

### ISSUE THREAD

**Issue by ExquisiteGoose** [AlexModGuy/AlexsCaves#323]
If a nucleeper begins its detonation timer in the most recent build (1.0.5) the game crashes. Went back to 1.0.4 as this bug does not seem to exist there.

**Comment by AlexModGuy** [comment]
crash log?

**Comment by ExquisiteGoose** [comment]
[crash-2023-10-24_22.58.01-client.txt](https://github.com/AlexModGuy/AlexsCaves/files/13168446/crash-2023-10-24_22.58.01-client.txt)

Here you go

**Comment by AlexModGuy** [comment]
could you turn nuclear_bomb_muffles_sounds to false in the alexscaves-client.toml config and see if that adresses the issue? would help me narrow down the cause

**Comment by ExquisiteGoose** [comment]
Just tried this, still crashes. Here's the crash report.
[crash-2023-10-25_17.47.49-client.txt](https://github.com/AlexModGuy/AlexsCaves/files/13168602/crash-2023-10-25_17.47.49-client.txt)

A little more info. I just tested this in a flat world and there was no crash, both before and after changing the config. Both in my main survival world and the test world I just used for this the nucleeper was in the toxic cave biome when the crash occured.

**Comment by AlexModGuy** [comment]
just to make sure. is the sound causing the crash the "siren" (https://www.youtube.com/watch?v=HHLERpO4HuI ) or the "beep" of the nucleeper as it activates, or the actual nuke exploding sound?

**Comment by ExquisiteGoose** [comment]
Unsure between the beep or the siren. In my test on a flat world (which I also included a siren for), there was no crash. Siren and beeps were all fine. 

The game crashes before the nucleeper can actually detonate, so I don't believe it's the actual nuke exploding sound.

**Comment by ExquisiteGoose** [comment]
I should also note that, when I went back a version (which fixed the crashing) on my main world, I killed the nucleeper but the Siren was caught on a loop until I restarted the game again.

**Comment by AlexModGuy** [comment]
if you;d like i can send you a test jar and see if the problem is fixed, send me a message on our discord server.

**Comment by ExquisiteGoose** [comment]
Sure, happy to give it a go. I'll shoot you a message.

**Comment by ExquisiteGoose** [comment]
What channel should I message you in?
