### ISSUE TITLE
sulfur crystals become acid source block on contact with flowing

### ISSUE THREAD

**Issue by lechkingofdead** [AlexModGuy/AlexsCaves#324]
![2023-10-24_18 30 24](https://github.com/AlexModGuy/AlexsCaves/assets/91407466/894e059b-8fee-4833-bad2-dc9e4ff06f68)
![2023-10-24_18 30 35](https://github.com/AlexModGuy/AlexsCaves/assets/91407466/745d3d8b-64f0-4981-955e-1f0c205dcbb4)
this also happens with rebar too unless its intended for both to become acid source blocks
![2023-10-24_18 32 43](https://github.com/AlexModGuy/AlexsCaves/assets/91407466/cf2a93ed-ffdb-4c9d-99dc-aeb34cb8708b)

**Comment by AlexModGuy** [comment]
dupe #485
