### ISSUE TITLE
Ferrouslimes crashes the server/essentially the whole game

### ISSUE THREAD

**Issue by Lambda-System** [AlexModGuy/AlexsCaves#328]
Sup again. It appears that the Ferrouslimes from the Magnetic Caves causes the whole world's TPS to freeze; essentially crashing the server/soft locking the whole game. Why? I'd have a better idea on how to figure out taxes then figure out why these dudes soft lock my game

The moment AT LEAST ONE Ferrouslime even fathoms to exist, the game freezes. Im half thinking its a mod conflict with another library mod, but, i am hoping maybe there could be some sort of work-around 

The list of library mods i have are as shown below, if it helps with anything lol. Thanks :3

- Balm
- Bookshelf
- Citadel (duh)
- Collective
- Creative Core
- Cupboard
- Gecko Lib(?? ill include this anyways)
- Insane Lib
- Puzzles Lib
- Resourceful Lib
- Terra Blender
- YungsAPI

**Comment by JustAnotherBugReporter** [comment]
Any rendering mods? (Rubidium, Embeddium, etc.)

**Comment by Lambda-System** [comment]
i wasnt able to find the /modlist command- but as for rendering/performance mods? i think these mods here are what classifies as those

- Does Potato Tick
- Entity Culling
- Ferrite Core
- Modern Fix
- Server Core
- Smooth Chunk

we also have Optifine enabled, but we tested if the Ferrouslimes would work by taking Optifine off, it didnt lol

**Comment by JustAnotherBugReporter** [comment]
Forge version?
I'm really just grasping at straws here, hoping something would work.

**Comment by Lambda-System** [comment]
so sorry for being late to this. life exists lol
im running on Forge 47.1.29

updating Forge is usually a hassle since i use Essential but i can look into doing that. 
still, people may like sticking to older versions of Forge for one reason or another, so. hopefully this will get figured out for those people maybe? thanks :]
