### ISSUE TITLE
When Irradiated and in the survival inventory, the nuclear furnace and most entities turn invisible.

### ISSUE THREAD

**Issue by DaySwagisLife** [AlexModGuy/AlexsCaves#329]
![2023-10-23_19 39 08](https://github.com/AlexModGuy/AlexsCaves/assets/121995597/7fee4f9c-962c-4dc4-a9e9-c968898dca6d)
![2023-10-24_19 14 34](https://github.com/AlexModGuy/AlexsCaves/assets/121995597/a8d47692-9a3c-4ca4-9eee-a36169d2e822)
![2023-10-24_19 25 31](https://github.com/AlexModGuy/AlexsCaves/assets/121995597/16ec9e37-de4f-42fe-b322-b78ab22df643)
With any level of irradiated, if the player opens their inventory in survival, or the survival tab in creative mode, the nuclear furnace and any other entity and block entity(including players and excluding raycats) will turn invisible, with only particles visible. If any entity(includes player in f5) that has the glow is visible on screen, then other entities not glowing will once again be visible, until the glowing one leaves the screen.

**Comment by AlexModGuy** [comment]
dupe #49
