### ISSUE TITLE
map

### ISSUE THREAD

**Issue by flaqqye** [AlexModGuy/AlexsCaves#330]
when left clicking with your cave map out it will crash you
Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Payload may not be larger than 32767 bytes

**Comment by AlexModGuy** [comment]
full crash log?

**Comment by ComeMyChild** [comment]
> full crash log?

it's a server side kick, here is the server log:
[latest.log](https://github.com/AlexModGuy/AlexsCaves/files/13183472/latest.log)
