### ISSUE TITLE
Biomes Not Generating

### ISSUE THREAD

**Issue by drmilk240** [AlexModGuy/AlexsCaves#335]
I've been trying to figure out why the Alex's Caves biomes aren't generating. I have very few worldgen mods (William Wythers & Spelunkery) and there's only one cave biome added by those mods. I'm not sure how that would stop all of the modded cave biomes from spawning, but you should definitely look into it.

**Comment by Eletoast** [comment]
If you can provide a full list of mods, it could give a lead on what could be causing them to not generate. I will say that Spelunkery doesn't affect cave generation and is not a mod of concern.

**Comment by drmilk240** [comment]
I'll send over the modlist when I get home!

**Comment by drmilk240** [comment]
Forge 1.20.1, 47.2.1

_No Library Mods Included_

**Just Worldgen (That could possibly affect caves):**

Alex's Caves
Better Archeology
Deeper Caves
Volcanic Caverns
William Wyther's Expanded Ecosphere
William Wyther's Overhauled Overworld
Spelunkery

**Full Modlist:**

Dustrial Decor
Let's Do Vinery
Alex's Caves
Alex's Mobs
All Bark, All Bite
Alternate Current
Ambient Sounds 5
Appleskin
Better Archeology
Better Block Sounds
Better FPS - Render Distance
Better Smithing Table
Biome Music
Botany Pots
Bridging Mod
Chimes
Chunk Sending
Clumps
Cluttered
Combat Roll
Connectivity
Controlling
Corpse
Crafting Automat
Curios API
Decorative Blocks
Deeper Caves
Diagonal Fences
Diagonal Windows
Dynamic Crosshair
Easy Anvil
Effect Descriptions
Eidolon: Repraised
Enchantment Descriptions
Enchantment Transfer
Entity Culling
ESSENTIAL Mod
Every Compat (Wood Good)
Falling Leaves
Farmer's Delight
Farsight
Fastload
FastSuite
Ferritecore
FPS Reducer
Guide API - Village & Pillage
Handcrafted
HT's Treechop
Immersive Paintings
Inventory Sorter
JEI
Krypton Reforged
Little Logistics
Login Protection
Lootr
Rubidium Dynamic Lights
Rubidium Extras
ManyIdeas Core
ManyIdeas Doors
Mouse Tweaks
Nature's Compass
Nether's Delight
Not Enough Animations
Overflowing Bars
Passable Foliage
Polymorph
Radium Reforged
Rubidium
Saturn
Server Performance - Smooth Chunk Save
Shield Expansion
Smooth Boot
Sound Physics Remastered
Spelunkery
Starlight
Stoneworks
Supplementaries
Supplementaries Squared
Toast Control
Tool Stats
Vampires Need Umbrellas
Vampirism
Visuality: Reforged
Volcanic Caverns
We Live, We Love, We Lie
William Wyther's Expanded Ecosphere
William Wyther's Overhauled Overworld
Xaero's Maps
You've Goat To Be Kidding Me
Most of the YUNG's Suite

**Comment by AlexModGuy** [comment]
few reports in the past with " Deeper Caves" ( a mod which I cant seem to find on 1.20.1 on google at all...) so id start with removing that

**Comment by drmilk240** [comment]
Alright, I'll try removing that and let you know! (To be fair, it's an MCreator mod that adds biomes, not a huge surprise that it might not be the most compatible)

**Comment by AlexModGuy** [comment]
oh, well there you go. MCreator = code that never ever plays nice with other mods, especially with such finicky things as rare underground biomes.

**Comment by AlexModGuy** [comment]
also nigh impossible for me to fix/work around because the code is illegible and unavailable.

**Comment by drmilk240** [comment]
So things seem to be generating now, although abyssal trenches still aren't working. I'm assuming that's Wythers ocean biomes messing it up, but whatever. Is there a way to increase the biome spawns so I can just force abyssal trenches to spawn more?

**Comment by AlexModGuy** [comment]
increase cave_biome_mean_width and decrease cave_biome_mean_separation
