### ISSUE TITLE
Incorrect NBT data for toxic ruins cave tablet

### ISSUE THREAD

**Issue by FusionSwarly** [AlexModGuy/AlexsCaves#337]
The cave tablet that spawns in toxic ruins loot tables has incorrect NBT data. Instead of CaveBiome being set to "alexscaves:toxic_caves" it's set to "alexscaves:toxic_ruins". When trying to use this tablet on a spelunkery table it causes the client to crash.

**Comment by AlexModGuy** [comment]
fixed
