### ISSUE TITLE
When you activate the submarine's lights every block turns invisible

### ISSUE THREAD

**Issue by AlesTheGreat** [AlexModGuy/AlexsCaves#34]
When i try to use the lights of the submarine in first person every block turns invisible (except for liquids and entities) and the game starts lagging.

**Comment by AlexModGuy** [comment]
log?

**Comment by AlesTheGreat** [comment]
Here, Sorry for the wait

[2023-10-19-4.log](https://github.com/AlexModGuy/AlexsCaves/files/13045306/2023-10-19-4.log)
