### ISSUE TITLE
Deep One neutrality and aggro issue

### ISSUE THREAD

**Issue by BiggestBruhMoment** [AlexModGuy/AlexsCaves#340]
I may not understand how deep ones work very clearly.But from what i know theyre naturally only stalk and run away from player.But it seems like when i test it out, theyre somehow started attacking me rather than running away from me when i didnt even do anything to them.This only stop when theyre reaching the friendly status.

Theres also a bug where deep ones still attacking player when theyre changing to creative mode.

**Comment by judecubed** [comment]
I also have this issue, they are way too aggressive when "cautious" actively following and attacking the player and still aggressive when neutral.

**Comment by Atmarsde** [comment]
this is my problem as well, while they just ignore my friend. Do you play in multiplayer or single-player? For me and one other guy on Discord, this occurred when we were using essential to play together

**Comment by PlummetStudios** [comment]
Dupe #285
