### ISSUE TITLE
Cave Biome map infinitely loading

### ISSUE THREAD

**Issue by slest002** [AlexModGuy/AlexsCaves#346]
As the title says, when I finally completed the puzzle to craft the map, when trying to interact with the map to locate the nearest cave biome, it is stuck in an infinite loading animation and never shows where the cave is. I was able to get one map to work for primordial caves, but after loading creative, I can't get any other maps to get past the loading stage.

**Comment by Mastaaa** [comment]
It takes some time for it to find a biome sometimes, and it will only keep looking while you're holding the map in your hand- having it in your hotbar seems to pause the search.

**Comment by slest002** [comment]
How long can it take? I was waiting for ~10 minutes

> It takes some time for it to find a biome sometimes, and it will only keep looking while you're holding the map in your hand- having it in your hotbar seems to pause the search.

**Comment by Driestcombee** [comment]
> How long can it take? I was waiting for ~10 minutes
> 
> > It takes some time for it to find a biome sometimes, and it will only keep looking while you're holding the map in your hand- having it in your hotbar seems to pause the search.

I waited for 2 hours and it doesn't load. It probably doesn't load when you save & quit and rejoin
