### ISSUE TITLE
Biome Barrels Spawn Blank Cave Tablets

### ISSUE THREAD

**Issue by Mastaaa** [AlexModGuy/AlexsCaves#347]
Was exploring a Toxic Caves biome and discovered a barrel in a shelter containing a blank Cave Tablet- that is, one not assigned to any actual biome. Assuming this is an issue with yesterday's 1.0.5 patch.

Attempting to place the blank Cave Tablet in the Spelunkery Table to decipher it causes the game to crash, and for the world to become unplayable thereafter- but I'm creating a separate Issue for this.

**Comment by AlexModGuy** [comment]
will be fixed
