### ISSUE TITLE
LightTex takes up almost all of the pie chart

### ISSUE THREAD

**Issue by Inonedn** [AlexModGuy/AlexsCaves#35]
![image](https://github.com/AlexModGuy/AlexsCaves/assets/36087299/9e941f82-14a0-49b7-9bb6-999c5ab64751)

**Comment by AlexModGuy** [comment]
![2023-10-19_09 33 31](https://github.com/AlexModGuy/AlexsCaves/assets/8662109/c4463949-96b0-4283-855a-f3688a2ca76e)
should be amended in the next build
