### ISSUE TITLE
everytig freze

### ISSUE THREAD

**Issue by phvfrancisco** [AlexModGuy/AlexsCaves#350]
after some time of playance (like 3 or 4 days in real life) all the mobs frezze in place, you cant open containers, you dont take damage and wen you break a block it dont drop
![Captura de tela de 2023-10-25 21-03-09](https://github.com/AlexModGuy/AlexsCaves/assets/147777446/8e655946-eeac-43d2-a387-eb4e9b1f0176)
.only hapens whith this modpack and Alex`s Caves version 1.0.4 (1.0.5 just crash wen you open minecraft)

**Comment by AlexModGuy** [comment]
whats the crash in 1.0.5

**Comment by phvfrancisco** [comment]
I realy dont know, it just crash right after open the game


Em qui, 26 de out de 2023 13:55, Alexthe668 ***@***.***>
escreveu:

**Comment by phvfrancisco** [comment]
atualy i noticed that is a bug whit magnetic caves, only hapens wen i enter a magnetic cave

**Comment by AlexModGuy** [comment]
dupe #328
