### ISSUE TITLE
Crash with Rubidium

### ISSUE THREAD

**Issue by this-ssia** [AlexModGuy/AlexsCaves#352]
The game crash when trying to render the ferrouslime and all entitites from the toxic caves, the rest seems to work fine

[crash-2023-10-26_00.19.10-client.txt](https://github.com/AlexModGuy/AlexsCaves/files/13172640/crash-2023-10-26_00.19.10-client.txt)

**Comment by RoomAlex68** [comment]
Am using Rubidium 0.6.5 and it hasn't crashed for me

**Comment by DonorKrovi** [comment]
Use Embeddium
