### ISSUE TITLE
Visual problem with magnet effects

### ISSUE THREAD

**Issue by RegularUser917** [AlexModGuy/AlexsCaves#357]
![image](https://github.com/AlexModGuy/AlexsCaves/assets/118590843/47d072cf-532f-46b1-9c7b-86e4f9134ad6)

**Comment by RegularUser917** [comment]
the effect isnt where it should be, switches between magnet and air

**Comment by AlexModGuy** [comment]
conflict with oculus

**Comment by Learwin** [comment]
> conflict with oculus

Ah that's sad to hear I guess I have to drop shaders for now until there might be a fix for this.
