### ISSUE TITLE
Game stops loading chunks/freezes on singleplayer and crashes when on a server when nearing Abyssal Chasm.

### ISSUE THREAD

**Issue by derevien** [AlexModGuy/AlexsCaves#362]
I play on a modpack called Prominence II, it might be relevant

[crash log](https://mclo.gs/oVxepeH)

**Comment by AlexModGuy** [comment]
if you would like to test some code on this please send me a message on our discord server.

**Comment by AlexModGuy** [comment]
dupe #84
