### ISSUE TITLE
No biomes are genenated with 'DeeperCaves' and-/or 'Silver Birch' Mod.

### ISSUE THREAD

**Issue by Maruhl** [AlexModGuy/AlexsCaves#363]
Hi, I have installed relatively many mods (120). After quite a while I was able to figure out that these 2 mods cause that no biomes are generated.

I have tested both mods separately.
If one of these mods is installed, no biomes are generated.

I have tested it several times with the command "/locate biome #alex..".

DeeperCaves (tested with "DeeperCaves-1.20.1-1.2.2.jar"):
[Mod Link](https://www.curseforge.com/minecraft/mc-mods/deeper-caves)

Silver Birch (tested with"silver-birch-1.1.1-1.20.1.jar"):
[Mod Link](https://www.curseforge.com/minecraft/mc-mods/silverbirch)

**Comment by AlexModGuy** [comment]
its deeper caves

**Comment by Maruhl** [comment]
@AlexModGuy 
Ok, but with the "silver birch" mod no biomes are created either.
