### ISSUE TITLE
Acid / Glass

### ISSUE THREAD

**Issue by MasterSkiwalker** [AlexModGuy/AlexsCaves#364]
When Acid and Glass Come in contact and the game just crashes

**Comment by AlexModGuy** [comment]
![2023-10-26_10 18 26](https://github.com/AlexModGuy/AlexsCaves/assets/8662109/8a408367-036a-428c-afee-4bbdf6e616c6)
going to need that crashlog

**Comment by Stormalisk** [comment]
Seems to be something with Rubidium maybe. I just had a crash to deal with the Toxic caves, in a certain area, myself. Ran a test to see and sure enough Acid/Glass caused a crash.
[crash-2023-10-26_22.02.26-client.txt](https://github.com/AlexModGuy/AlexsCaves/files/13184294/crash-2023-10-26_22.02.26-client.txt)

**Comment by AlexModGuy** [comment]
dupe #78
