### ISSUE TITLE
Server crash whenever near magnetic cave

### ISSUE THREAD

**Issue by Hiklorte** [AlexModGuy/AlexsCaves#370]
Crash report:
[https://pastebin.com/iRfnujp8](url)
Download:
[crash-2023-10-26_19.44.40-server.txt](https://github.com/AlexModGuy/AlexsCaves/files/13183651/crash-2023-10-26_19.44.40-server.txt)

**Comment by VictorHenrique317** [comment]
Same

**Comment by AlexModGuy** [comment]
dupe #328
