### ISSUE TITLE
Exit Code: 1 Keeps happening whenever i try to launch it, have tied liek EVERYTHING

### ISSUE THREAD

**Issue by Slabman-Idiot** [AlexModGuy/AlexsCaves#372]
Im updated my drivers, unitstalled both curseforge and java/minecaft. Have repaired the folders, made sure citidal was installed. made sure my amd drivers were good but nothing works.

Heres the exact log summary
---------------  S U M M A R Y ------------

Command Line: -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Djava.library.path=C:\Users\jetj1\curseforge\minecraft\Install\bin\4d9dc561d8316cc393408848f89614dc8fa67022 -Djna.tmpdir=C:\Users\jetj1\curseforge\minecraft\Install\bin\4d9dc561d8316cc393408848f89614dc8fa67022 -Dorg.lwjgl.system.SharedLibraryExtractPath=C:\Users\jetj1\curseforge\minecraft\Install\bin\4d9dc561d8316cc393408848f89614dc8fa67022 -Dio.netty.native.workdir=C:\Users\jetj1\curseforge\minecraft\Install\bin\4d9dc561d8316cc393408848f89614dc8fa67022 -Dminecraft.launcher.brand=minecraft-launcher -Dminecraft.launcher.version=2.12.17 -Djava.net.preferIPv6Addresses=system -DignoreList=bootstraplauncher,securejarhandler,asm-commons,asm-util,asm-analysis,asm-tree,asm,JarJarFileSystems,client-extra,fmlcore,javafmllanguage,lowcodelanguage,mclanguage,forge-,forge-47.2.1.jar,forge-47.2.1 -DmergeModules=jna-5.10.0.jar,jna-platform-5.10.0.jar -DlibraryDirectory=C:\Users\jetj1\curseforge\minecraft\Install\libraries --module-path=C:\Users\jetj1\curseforge\minecraft\Install\libraries/cpw/mods/bootstraplauncher/1.1.2/bootstraplauncher-1.1.2.jar;C:\Users\jetj1\curseforge\minecraft\Install\libraries/cpw/mods/securejarhandler/2.1.10/securejarhandler-2.1.10.jar;C:\Users\jetj1\curseforge\minecraft\Install\libraries/org/ow2/asm/asm-commons/9.5/asm-commons-9.5.jar;C:\Users\jetj1\curseforge\minecraft\Install\libraries/org/ow2/asm/asm-util/9.5/asm-util-9.5.jar;C:\Users\jetj1\curseforge\minecraft\Install\libraries/org/ow2/asm/asm-analysis/9.5/asm-analysis-9.5.jar;C:\Users\jetj1\curseforge\minecraft\Install\libraries/org/ow2/asm/asm-tree/9.5/asm-tree-9.5.jar;C:\Users\jetj1\curseforge\minecraft\Install\libraries/org/ow2/asm/asm/9.5/asm-9.5.jar;C:\Users\jetj1\curseforge\minecraft\Install\libraries/net/minecraftforge/JarJarFileSystems/0.3.19/JarJarFileSystems-0.3.19.jar --add-modules=ALL-MODULE-PATH --add-opens=java.base/java.util.jar=cpw.mods.securejarhandler --add-opens=java.base/java.lang.invoke=cpw.mods.securejarhandler --add-exports=java.base/sun.security.util=cpw.mods.securejarhandler --add-exports=jdk.naming.dns/com.sun.jndi.dns=java.naming -Xmx4096m -Xms256m -Dminecraft.applet.TargetDirectory=C:\Users\jetj1\curseforge\minecraft\Instances\a cave -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -Duser.language=en -Duser.country=US -Dlog4j.configurationFile=C:\Users\jetj1\curseforge\minecraft\Install\assets\log_configs\client-1.12.xml cpw.mods.bootstraplauncher.BootstrapLauncher --username Thy_RatKing --version forge-47.2.1 --gameDir C:\Users\jetj1\curseforge\minecraft\Instances\a cave --assetsDir C:\Users\jetj1\curseforge\minecraft\Install\assets --assetIndex 5 --uuid dc975802a3194fe58fd0bae55556e89a --clientId MzIwYmFmYmUtNjM3YS00Nzk5LTg3OWMtM2M1YmExMzk2MzFh --xuid 2535462360380467 --userType msa --versionType release --width 1024 --height 768 --quickPlayPath C:\Users\jetj1\curseforge\minecraft\Install\quickPlay\java\1698366704294.json --launchTarget forgeclient --fml.forgeVersion 47.2.1 --fml.mcVersion 1.20.1 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20230612.114412

Host: AMD Ryzen 5 3600 6-Core Processor              , 12 cores, 7G,  Windows 10 , 64 bit Build 19041 (10.0.19041.3570)
Time: Thu Oct 26 19:31:48 2023 Central Daylight Time elapsed time: 3.724473 seconds (0d 0h 0m 3s)

END.

help plz lol

**Comment by Wendigghost** [comment]
It's not Alex's Caves that's crashing your game. It's citadel. I know this because I also tried getting Alex's mobs for 1.20.1 as well, and It also kept crashing. So I tested a mod pack using just citadel for 1.20.1, for two different versions of citadel, and for both instances it would just crash instantly. While I don't know much about code and could be wrong, I do think that this is the issue.
