### ISSUE TITLE
Cave Biome Maps do not load in multiplayer (1.0.6)

### ISSUE THREAD

**Issue by ComeMyChild** [AlexModGuy/AlexsCaves#374]
Recently updated our server to 1.0.6, wanted to find an abyssal chasm so we made the map. 10 minutes later the map still hasn't loaded, whereas the /locate biome finds it only about 3000 blocks away. Back in 1.0.5 the maps loaded just fine, as we had visited a toxic caves the other day using the map. 

Steps to recreate:
On a server, load a biome map and wait as it doesn't load.

**Comment by DonorKrovi** [comment]
Same
