### ISSUE TITLE
Magnetic Caves stop chunk loading and freezes world

### ISSUE THREAD

**Issue by InsectBrain** [AlexModGuy/AlexsCaves#376]
Upon loading Magnetic Caves the world stops loading and everything freezes, the client can still open their inventory however it seems the world completely stops responding, blocks can be broken but do not drop their items, mobs stop moving and chunks do not load anymore. This happens both in a singleplayer world and in a multiplayer world, through the essentials launcher.

Entering Magnetic Caves or simply loading it doesnt seem to immediatly freeze the world, it seems to freeze the world when something specific renders in, unsure what though. Had a multiplayer world almost get softlock because a friend and i went to Magnetic Caves and first discovered the issue there, we ended up having to delete player data in order to un freeze the game then teleport us out of the area. Attached image is all the mods we have been using, disabeling some mods in a singeplayer world does not seem to fix the issue either.
![mod list](https://github.com/AlexModGuy/AlexsCaves/assets/149131739/60253f0b-665c-413f-b69c-640cad209a25)

**Comment by InsectBrain** [comment]
Turns out Essentials was causing all the issues friends and i were having, such as magnetic caves freezing world and stopping chunk loading, sirens not having sound to anyone but the host in multiplayer, submarines kicking you out if its above the surface and Deep One Mage's not being spawnable or spawning (and Deep One Mage book entry crashing game if opened). So the issue's still pursist but so far only with Essentials installed. If anyone else is having these issues, use e4mc as an alternative to Essentials, from what im told its "Essentials but better".

**Comment by AlexModGuy** [comment]
dupe #328
