### ISSUE TITLE
Dino Nuggets Variants

### ISSUE THREAD

**Issue by SuperStefan97** [AlexModGuy/AlexsCaves#380]
Hi! Not a big deal or game changing but guessed you would want to fix it. When picking dino nuggets or giving it to a player via commands, nuggets always appear as brachiosaurus. Also while trying to craft them they also are brachiosaurus. Sometimes when picking two dino nuggets they randomly change their form but when being in other form (for example stegasaur) and placed in an item frame, chest or similar... they revert back to brachio.
Again, not a big deal, but I guessed since you took the tinw to design many variants you might as well wanted them to be seeing in game. Thanks for reading!

**Comment by DoctorWafflePhD** [comment]
From what I can gather, the shape of dino nuggets depends on the stack size. A stack of 1 gives you a brachiosaurus, a stack of 2 gives you a stegosaurus, 3 gives a pterodactyl, 4 gives a pachycephalosaurus, and it loops from there (meaning shape can be determined with the equation (shape)=(stack)%4, where 1=brachio, 2=stego, 3=ptero, 0=pachy). As item frames only hold one item at a time, it will always be a brachiosaurus, and similarly the crafting recipe results in 12 nuggets, meaning it will always be a pachycephalosaurus as 12%4 = 0.

**Comment by PlummetStudios** [comment]
Works as intended.

**Comment by SuperStefan97** [comment]
Oh ok, thought it was a bug. Thank you
