### ISSUE TITLE
Deep ones are quite broken?

### ISSUE THREAD

**Issue by xelotex** [AlexModGuy/AlexsCaves#382]
So the first time i encounter them they approached and started attacking for no reason, so i thought they just where like any other hostile monster and i fought back, but then the game tells me that deep ones regard me with aggression? So i was supposed to not attack them? Then i read the compendium and it says they don't get too close and just stalk at a distance (which quite the opposite happened, they literally got right infront of my face and started attacking), and i need to gain their trust by trading them pearls, so i try to do just that (which was difficult since they wouldn't stop getting in my face and start attacking) and it worked for the first 30 seconds, but then none of the deep ones wouldn't trade me anything, they just ignore the altar.

So now i've been trying to progress in the abyssal chasm for hours but i just can't get the deep ones to trade me anything.

i'm playing in version 1.0.6

Here's a video:
https://www.youtube.com/watch?v=UBw9_GkS-88

**Comment by supertroopa** [comment]
this exact same thing happened to me as well

**Comment by xelotex** [comment]
Yeah, it can be very misleading, but you can actually trade with them, it just takes time, the more deep ones there is, the quicker they will accept trades, and eventually they will stop attacking, but you will need to tank a lot of damage.

**Comment by PlummetStudios** [comment]
#285
