### ISSUE TITLE
Beholder Xearo's Minimap Crash

### ISSUE THREAD

**Issue by VanilaBOI** [AlexModGuy/AlexsCaves#385]
I honestly don't know how to recreate this crash but when I tried to link a Occult Gem to a beholder, it didn't do anything at first and then after like 5 seconds the game caught up and I got the linked Occult Gem. When I went into the beholder view my game crashed and anytime I tried reloading the world with xearo's minimap it crashed before I could do anything.

The weird thing is when I tried to recreate it on another world this was never an issue so idk. Kinda niche. wanted to post it.

Initial Crash:
[crash-2023-10-27_04.24.31-client.txt](https://github.com/AlexModGuy/AlexsCaves/files/13190892/crash-2023-10-27_04.24.31-client.txt)

Trying to relog into the world Crashes:
[crash-2023-10-27_17.08.08-client.txt](https://github.com/AlexModGuy/AlexsCaves/files/13190902/crash-2023-10-27_17.08.08-client.txt)
[crash-2023-10-27_04.25.55-client.txt](https://github.com/AlexModGuy/AlexsCaves/files/13190903/crash-2023-10-27_04.25.55-client.txt)

**Comment by AlexModGuy** [comment]
Xearos issue. they shouldnt assume the camera entity is a player at all times, since even in vanilla it can be another mob in spectator mode. report it to them

**Comment by VOlD6** [comment]
How do you DM the Xaero creator/team?
Couldnt find any, could just use Journey map instead but its not as easy or likeable to me
