### ISSUE TITLE
Mod compatibility with cave map

### ISSUE THREAD

**Issue by undefined06855** [AlexModGuy/AlexsCaves#387]
Left clicking with a cave map while inventorio is installed kicks you from the server if youre not looking at a block.

Version is 1.0.5 but afaik has not been fixed in the latest update.

The video shows perspective from the user (left) and the server (right)

https://github.com/AlexModGuy/AlexsCaves/assets/98057141/a499c587-d138-4814-b0b7-b3440d16805d

64103376906/1167513829610115214/20231027-1717-17.9172926.mp4

**Comment by xelotex** [comment]
You sure inventorio is causing this? I use inventorio too and i don't have this issue. I play in 1.0.6 btw.

Here's a video:
https://youtu.be/ic2yCDt8yWA

**Comment by undefined06855** [comment]
> You sure inventorio is causing this? I use inventorio too and i don't have this issue. I play in 1.0.6 btw.
> 
> Here's a video:
> https://youtu.be/ic2yCDt8yWA

Alright then, could be some other mod but it'll be hard to debug which. It's not a game-breaking issue, so it's probably fine.

**Comment by undefined06855** [comment]
> You sure inventorio is causing this? I use inventorio too and i don't have this issue. I play in 1.0.6 btw.
> 
> Here's a video:
> https://youtu.be/ic2yCDt8yWA

Alright then, could be some other mod but it'll be hard to debug which. It's not a game-breaking issue, so it's probably fine.

**Comment by AlexModGuy** [comment]
fixed in 1.0.8
