### ISSUE TITLE
nbt problem

### ISSUE THREAD

**Issue by Willem07** [AlexModGuy/AlexsCaves#393]
In the modpack of 100+ mods, a problem arose on the server, with version 1.0.1 there were no problems with Cave Tablet Magnetic Caves, with version 1.0.5 it crashed when inserting the Cave Tablet into the slot, now in version 1.0.6 there is a problem as in the screenshot, although when creating a single world, the cave tablet works correctly. How to fix the error and save the old world on the server?
![2023-10-27_21 27 25](https://github.com/AlexModGuy/AlexsCaves/assets/51959206/e4b70ffc-7c8a-4143-8b7d-dab3e6cfa8df)

**Comment by DoctorWafflePhD** [comment]
I believe it's an error exclusive to a single loot table's cave tablet - it erroneously is tagged with the biome `toxic_ruins`, which should instead be `toxic_caves`. The loot table has been fixed IIRC, but any bugged tablets obtained before the hotfix will remain unusable.
