### ISSUE TITLE
Error code 1

### ISSUE THREAD

**Issue by javex412** [AlexModGuy/AlexsCaves#394]
I have only installed the mod and citadell, I'm currently playing on the latest forge, changed the resolution to the one on my pc and changed the jvm adjustments to suit my pc.
Here is the crash report
[hs_err_pid16088.log](https://github.com/AlexModGuy/AlexsCaves/files/13193481/hs_err_pid16088.log)

**Comment by AlexModGuy** [comment]
dupe #229
