### ISSUE TITLE
waste drum crashes the game when tossed into cactus

### ISSUE THREAD

**Issue by Decycle** [AlexModGuy/AlexsCaves#4]
issues persist when rejoining the game, immediately crashed again

**Comment by AlexModGuy** [comment]
crash log? cannot replicate

**Comment by thelegitdolt** [comment]
crashed for me too, but i was throwing it into lava. I will have crash report give me one sec

**Comment by thelegitdolt** [comment]
crash report: https://gist.github.com/thelegitdolt/cdfb717dc6ba8a049b18b57a2f3931d1
latest.lgo: https://gist.github.com/thelegitdolt/6aee911f4c90e32879b534a07a6fa2b3

**Comment by Decycle** [comment]
crash report: https://gist.github.com/Decycle/42625632d40fb655c5156e6bd33745d2

**Comment by Captaincookie72** [comment]
the waste drum isn't meant to be able to be destroyed so when it is thrown into fire, lava, or a cactus it explodes into particles, I threw a couple of them in a fire and it permanently locked the world into hardcrashing the game whenever I try to load it.
