### ISSUE TITLE
Request: difficulty scaling for mob's damage.

### ISSUE THREAD

**Issue by pantsguyapp** [AlexModGuy/AlexsCaves#402]
Not sure if the damage of mobs from this mod scale with different difficulties, but in case they don't, then I will just put this here.

**Comment by PlummetStudios** [comment]
You don't know if your suggestion is already in game?

**Comment by pantsguyapp** [comment]
No I don't for I had no idea how to, torohealth isnt on 1.20, so I just post it in case it hasnt been implemented.
