### ISSUE TITLE
I cant found any caves with mod terrablender and biome's o plenty installed

### ISSUE THREAD

**Issue by Yao0oooo** [AlexModGuy/AlexsCaves#41]
I have installed terralith, tectonic, biome o plenty and terrablender in my modpck and when i get into the world i couldnt found any caves within 25000 block radius, after i uninstall terrablender and biome o plenty and try again in a new generated world,  caves can be found now. Can you please fix the compatibility issues？

**Comment by A00826925** [comment]
what other mods do you have installed?

**Comment by Yao0oooo** [comment]
> what other mods do you have installed?

for world generation these are the only mods i have installed

**Comment by A00826925** [comment]
just tested with this combination of world gen mods and it worked, its gotta be something else, 
![image](https://github.com/AlexModGuy/AlexsCaves/assets/73501467/70d0fba9-f78e-4e68-ba81-43f08b0d2812)

**Comment by AlexModGuy** [comment]
update citadel to 2.4.7

**Comment by luisdacrash** [comment]
Still with 2.4.7 i have the same problem, the maps do not lead to a mod cave. Im using Rats, Caves & Cogwheels ( An Alex's Caves Modpack ) in 1.20.1 (Sorry for bad english)
