### ISSUE TITLE
Server/singleplayer game keeps crashing when generating cave chunks

### ISSUE THREAD

**Issue by snrtak** [AlexModGuy/AlexsCaves#410]
Aye, our server keeps crashing when trying to generate chunks that got the new caves. Tried it in singleplayer and it crashed the game as well. Dunno if it's a corrupted chunk or some mods overlapping or smth. Could you check it out and try to help us out please? Thanks. Also here's the [latest.log](https://github.com/AlexModGuy/AlexsCaves/files/13196073/latest.log)

**Comment by AlexModGuy** [comment]
>unknown structure 'dungeons_enhanced:deep_crypt' in chunk [25, 11], discarding
> unknown structure 'nova_structures:illager_camp' in chunk 

try removing these two mods

**Comment by snrtak** [comment]
tried that, crashed the exact same way, server crashed the second I got near the primordial cave

**Comment by AlexModGuy** [comment]
dupe #84
