### ISSUE TITLE
agressive deep ones

### ISSUE THREAD

**Issue by phvfrancisco** [AlexModGuy/AlexsCaves#422]
no mather of the reputation with the deep ones, they will alwais atack you

**Comment by xelotex** [comment]
You sure? They attack if you get too close in any other reputation, except when they consider you a friend.

But its true that some deep ones dont get their IA updated, or it takes some time and they still regard you with caution and can attack you. However, it wont be the case for new or recently spawned deep ones.

Check if they consider you a friend and try to get close to recently spawned ones, they shouldn't attack unless they're bugged or something.

**Comment by PlummetStudios** [comment]
Dupe #285
