### ISSUE TITLE
Forge crashes whenever Alex's Caves (in a modpack) loads on the curseforge launcher

### ISSUE THREAD

**Issue by Driestcombee** [AlexModGuy/AlexsCaves#425]
Steps to recreate:
1. Load the curseforge app
2. Make a custom modpack that contains Alex's Caves 1.0.6, Citadel 2.4.7, Rubidium 0.7.1
3.  Press Play on Curseforge
4.  Press Play on Minecraft
5. Watch the game crash

**Comment by Celks** [comment]
I'm having the same problem, but i didn't know which mod was crashing alex's caves. You helped me a lot hahahaha, but unfortunately i can't play without Rubidium :-:

**Comment by Driestcombee** [comment]
Rubidium surprisingly works on older versions of Alex's Caves

**Comment by RoomAlex68** [comment]
Have you tried Embeddium?
