### ISSUE TITLE
Crash when trying to create a world 1.0.6 1.20.1

### ISSUE THREAD

**Issue by SETHPROSYT** [AlexModGuy/AlexsCaves#429]
I tried to create a world with Alex's Caves and its dependencies and it crashed when trying to create a world, I tried all versions of forge, here is the error link
https://mclo.gs/Hslps8y

**Comment by Eletoast** [comment]
Seems like optifine could be the problem. Try deleting optifine and replacing it with another performance mod like Embeddium.

**Comment by SETHPROSYT** [comment]
it worked, thanks
