### ISSUE TITLE
[Softlock] Vallumraptor Crash

### ISSUE THREAD

**Issue by Slendernibble** [AlexModGuy/AlexsCaves#437]
After consulting people who actually know what they're doing **_(I am a fool)_**, they said it was the Vallumraptor causing crashes and that, it didn't appear to be the result of any conflicts. From testing, it seems to happen from even just being in the same chunk -- regardless of if I can see it or not. Tried spawning it in a creative world and the game crashed immediately.

**I hope this is useful !!!**

- [debug.log](https://github.com/AlexModGuy/AlexsCaves/files/13198150/debug.log)
- [crash-2023-10-29_12.56.43-client.txt](https://github.com/AlexModGuy/AlexsCaves/files/13198154/crash-2023-10-29_12.56.43-client.txt)
- [latest.log](https://github.com/AlexModGuy/AlexsCaves/files/13198155/latest.log)
- [simple mod list.txt](https://github.com/AlexModGuy/AlexsCaves/files/13198189/simple.mod.list.txt)

**Comment by AlexModGuy** [comment]
> mehvahdjukaar.dummmmmmy.common.ModEvents.onEntityHeal
issue is with the dummmmmmy mod

**Comment by Slendernibble** [comment]
OH?? I'm a dingbat- but I hope this wasn't a waste of time for you- thanks!!
