### ISSUE TITLE
World stop loading when Minecraft try to load the magnetic mobs

### ISSUE THREAD

**Issue by VODKAman115** [AlexModGuy/AlexsCaves#445]
When my world tries to load the mobs from de magnetic caves, it stops loading any new chunk and the mobs stay freezed.
![Captura de pantalla 2023-10-29 160623](https://github.com/AlexModGuy/AlexsCaves/assets/149328041/1655328b-6478-4355-b220-a92ea6d535fc)
These are the mods I have and idk which one is the problem.
(sorry if my english is bad)

**Comment by AlexModGuy** [comment]
dupe #328
