### ISSUE TITLE
Got banned from discord server and unable to appesl

### ISSUE THREAD

**Issue by Eevneon** [AlexModGuy/AlexsCaves#449]
I know its weird for me to do this here, but I think i was just banned from the Discord server, and im struggling to appeal, or even ask what made it that I had to be banned. Someone mightve warned me, but i was still typing, so I'm not sure. I would like it if I could get into contact with Alex or another admin on Discord to try and appeal my ban.

**Comment by PlummetStudios** [comment]
This isnt the place to talk about moderation decisions. From my understanding, you were banned from the server for asking/suggesting more features which a moderator was worried about causing more grief for Alex long term.

**Comment by PlummetStudios** [comment]
You also got onto a soapbox and were being annoying about your suggestions being rejected.

**Comment by Eevneon** [comment]
> You also got onto a soapbox and were being annoying about your suggestions being rejected.

I was respectfully having an argument. Yes I was being very defensive about my opinion, but i wasn't harrassing or making fun of anyone. The only one that got made fun of was me, so you can't accuse me of that.

**Comment by AlexModGuy** [comment]
you being banned from discord by our moderation team (that i am not a part of btw) isnt helped by you wasting my time by opening up a ticket on the bugtracker. its extremely annoying and only cements why the moderation team banned you in the first place.
