### ISSUE TITLE
Minecraft loading Crashe

### ISSUE THREAD

**Issue by Mad5keleton** [AlexModGuy/AlexsCaves#455]
After i click play it opens minecraft loading launcher then in max 3 seconds game loading launcher crashes.
I did a fresh install of minecraft and deleted .minecraft(in %appdata%) before installing it and still crashes.
I have 0 mods
I think i have given the corect crash log

[launcher_log.txt](https://github.com/AlexModGuy/AlexsCaves/files/13209252/launcher_log.txt)

**Comment by PlummetStudios** [comment]
You don't have the Citadel mod installed which is a needed library mod for Alexs Caves.
