### ISSUE TITLE
Crashed upon looking at a raycat

### ISSUE THREAD

**Issue by Petrus64** [AlexModGuy/AlexsCaves#459]
Take it with a grain of salt, as there are a ton of other mods running that could've contributed to this, but a friend of mine and I crashed when we ran into a raycat in the toxic cave.

[crash-2023-10-30_21.39.29-client.txt](https://github.com/AlexModGuy/AlexsCaves/files/13211485/crash-2023-10-30_21.39.29-client.txt)

**Comment by AlexModGuy** [comment]
update rubidium
