### ISSUE TITLE
[1.20.1] Alex's Caves Crash

### ISSUE THREAD

**Issue by TheTheo45** [AlexModGuy/AlexsCaves#469]
Forge: 47.2.1
OptiFine_1.20.1_HD_U_I5
citadel-2.4.7-1.20.1

Steps to Reproduce:

        Install Alex's Caves 1.0.6 with my current modlist

Crash-Report: 
        https://gist.github.com/TheTheo45/8bb3c9308bd56c271163f17e182a98fc

can provide additional information when needed

**Comment by AlexModGuy** [comment]
dupe #238
