### ISSUE TITLE
Alex's Caves biomes not being generated with Organics mod

### ISSUE THREAD

**Issue by Siphastar83** [AlexModGuy/AlexsCaves#474]
Hi,
Me and some friend created a server with a ton of mod.
And at the start we don't know why 'caves' from alexcave haven't been generated.
We found that it was glitched with organic.

If you have some suggestion to make it work, please tell me?

**Comment by Rasszusz221** [comment]
I have the same problem, but I don't have this mod. Do you think all mods like this are buggy?

**Comment by AlexModGuy** [comment]
dupe
