### ISSUE TITLE
World Freezing when trying to load any of the cave biomes

### ISSUE THREAD

**Issue by GamerTRW** [AlexModGuy/AlexsCaves#478]
My world will freeze and stop generating, i will be able to move and break/place blocks but nothing in the worlds responds, and when I try and exit I will be stuck on the saving world screen, so I can't get a crash report
Here is my modlist
(Sorry it's quite long)
Artifacts (by ochotonida)
Xaero's Minimap (by xaero96)
Structure Essentials[Forge/Fabric] (by someaddon)
Collective (by Serilum)
Chat Heads (by dzwdz)
Shoulder Surfing Reloaded (by _ForgeUser21552638)
Craftable Horse Armour & Saddle [CHA&S] (by EwyBoy)
[ETF] Entity Texture Features - [Fabric & Forge] (by traben_0)
Sound Physics Remastered (by henkelmax)
YUNG's Extras (Forge) (by YUNGNICKYOUNG)
Storage Drawers (by Texelsaur)
Drippy Loading Screen [Forge] (by Keksuccino)
YUNG's Better Mineshafts (Forge) (by YUNGNICKYOUNG)
Trading Post [Forge & Fabric] (by Fuzs)
Sophisticated Core (by P3pp3rF1y)
FTB Library (Forge) (by FTB)
XL Packets (by tfarecnim)
Comforts (Fabric/Forge/Quilt) (by TheIllusiveC4)
BetterF3 (by cominixo)
L_Ender 's Cataclysm (by mcl_ender)
Searchables (by Jaredlll08)
Create Crafts & Additions (by MRHminer)
Bountiful (Forge) (by Ejektaflex)
AmbientSounds 5 (by CreativeMD)
Resourceful Lib (by ThatGravyBoat)
All The Trims (by bawnorton)
Pehkui (by Virtuoel)
Kotlin for Forge (by thedarkcolour)
Combat Roll [Fabric & Forge] (by daedelus_dev)
Mouse Tweaks (by YaLTeR)
More Music Discs [Fabric/Forge] (by Mars)
Puzzles Lib [Forge & Fabric] (by Fuzs)
Better Combat [Fabric & Forge] (by daedelus_dev)
Oculus (by Asek3)
Bookshelf (by DarkhaxDev)
MES - Moog's End Structures (by finndog_123)
SeasonHUD (by IanAnderson)
Caelus API (Forge) (by TheIllusiveC4)
YUNG's Bridges (Forge) (by YUNGNICKYOUNG)
Medieval Origins Revival [Forge/Neo/Fabric] (by MuonR)
Resourceful Config (by ThatGravyBoat)
Polymorph (Fabric/Forge/Quilt) (by TheIllusiveC4)
AppleSkin (by squeek502)
Explorify – Dungeons & Structures (by bebebea_loste)
Bygone Nether (by izofar)
Konkrete [Forge] (by Keksuccino)
YUNG's Better Desert Temples (Forge) (by YUNGNICKYOUNG)
Epic Knights: Shields, Armor and Weapons [Fabric & Forge] (by magistu_)
YUNG's Better End Island (Forge) (by YUNGNICKYOUNG)
Controlling (by Jaredlll08)
Quests Additions (Forge) (by NaturaSpell)
Better chunk loading[Forge/Fabric] (by someaddon)
mutil (by mickelus)
Farmer's Delight (by vectorwing)
Amplified Nether (by Starmute)
Better Villages - Forge (by jtl_elisa)
Formations (Structure Library) (by SuperMartijn642)
Additional Structures (by XxRexRaptorxX)
Structory: Towers (by botanydev)
Dungeons and Taverns (by Nova_Wostra)
Create: Steam 'n' Rails (by mattentosh)
ChoiceTheorem's Overhauled Village (by ChoiceTheorem)
William Wythers' Expanded Ecosphere (by Cristelknight)
Cloth Config API (Fabric/Forge) (by shedaniel)
Xaero's World Map (by xaero96)
FancyMenu [Forge] (by Keksuccino)
Library Ferret - Forge (by jtl_elisa)
Just Enough Resources (JER) (by way2muchnoise)
playerAnimator (by KosmX)
Cupboard (by someaddon)
Origins (Forge) (by EdwinMindcraft)
Corn Delight[Forge] (by sz0999312)
Architectury API (Fabric/Forge) (by shedaniel)
Creeper Overhaul (by joosh_7889)
Paintings ++ (by AbsolemJackdaw)
Alex's Mobs (by sbom_xela)
FTB Teams (Forge) (by FTB)
Paragliders (by Tictim)
Xaero's Minimap & World Map - Waystones Compatibility [Forge] (by precisemodpacker)
Cristel Lib (by Cristelknight)
YUNG's API (Forge) (by YUNGNICKYOUNG)
Biomes O' Plenty (by Forstride)
Just Enough Items (JEI) (by mezz)
TerraBlender (Forge) (by TheAdubbz)
Friends&Foes (Forge) (Copper Golem, Glare, Moobloom, Iceologer, Barnacle, Wildfire, Illusioner, Rascal and Tuff Golem) (by Faboslav)
Ash API (by Trikzon)
Magnesium/Rubidium Dynamic Lights (by Anthxny)
Formations Nether (by SuperMartijn642)
Nether Skeletons (by GlitchedMastery)
Sophisticated Backpacks (by P3pp3rF1y)
Balm (Forge Edition) (by BlayTheNinth)
Twigs (by ninnih_)
Deeper and Darker (by KyaniteMods)
Alex's Caves (by sbom_xela)
Starter Kit (by Serilum)
Transparent (by Trikzon)
End's Delight (by foggyhillside)
Iron's Spells 'n Spellbooks (by Iron431)
Enderman Overhaul (by joosh_7889)
Chunk Sending[Forge/Fabric] (by someaddon)
Create: Structures (by FusionSwarly)
FTB Quests (Forge) (by FTB)
Create (by simibubi)
Framework (by MrCrayfish)
CreativeCore (by CreativeMD)
YUNG's Better Jungle Temples (Forge) (by YUNGNICKYOUNG)
YUNG's Better Witch Huts (Forge) (by YUNGNICKYOUNG)
AtomicStryker's Infernal Mobs (by atomicstrykergrumpy)
Origins++ (by QuantumXenon)
[EMF] Entity Model Features [Fabric & Forge] (by traben_0)
Server Performance - Smooth Chunk Save[Forge/Fabric] (by someaddon)
Structory (by botanydev)
Curios API (Forge) (by TheIllusiveC4)
Waystones (by BlayTheNinth)
Tetra (by mickelus)
YUNG's Better Ocean Monuments (Forge) (by YUNGNICKYOUNG)
TexTrue's Rubidium Options (by TexTrue)
Simply Swords [Fabric & Forge] (by sweenuss)
Magnesium/Rubidium Extras (by Anthxny)
Better Third Person (by Socolio)
HT's TreeChop (by hammertater)
Dark Paintings (by DarkhaxDev)
Jade 🔍 (by Snownee)
YDM's Custom Camera View (by YourDailyModderx)
Item Filters (by LatvianModder)
GeckoLib (by Gecko)
YUNG's Better Nether Fortresses (Forge) (by YUNGNICKYOUNG)
YUNG's Better Strongholds (Forge) (by YUNGNICKYOUNG)
Mysterious Mountain Lib (by sz0999312)
End Remastered (by jack_bagel)
Kambrik (by Ejektaflex)
Goblin Traders (by MrCrayfish)
Nether's Delight (by lumpazl)
Create Stuff & Additions (by Furti_Two)
Citadel (by sbom_xela)
Serene Seasons (by TheAdubbz)
YUNG's Better Dungeons (Forge) (by YUNGNICKYOUNG)
Callable Horses (by Tschipp)

**Comment by AlexModGuy** [comment]
dupe #48
