### ISSUE TITLE
Acid-logged blocks can used to generate infinite acid

### ISSUE THREAD

**Issue by YocyCraft** [AlexModGuy/AlexsCaves#485]
How to reproduce:

1. Dig 2 blocks on the groud, fill with Acid, and put a Acid-logable block (such as Sulfur Cluster) in it.

2. Give yourself a lot of buckets.

3. Switch to survival and use buckets on the Acid-logged block, your inventory will be filled with Acid buckets.
![2023-11-01_20 35 37](https://github.com/AlexModGuy/AlexsCaves/assets/80801884/676c7a98-a97e-48fd-8be3-555dc8e89bfc)

**Comment by YocyCraft** [comment]
An Infinite Acid farm by create using this bug
![Uploading 2023-11-01_20.49.53.png…]()

**Comment by YocyCraft** [comment]
??

**Comment by YocyCraft** [comment]
![2023-11-01_20 49 53](https://github.com/AlexModGuy/AlexsCaves/assets/80801884/476c1fb3-20e0-4392-8ca8-29e642130abe)

**Comment by AlexModGuy** [comment]
fixed
