### ISSUE TITLE
The chance for caves is too small

### ISSUE THREAD

**Issue by Keolass** [AlexModGuy/AlexsCaves#486]
It seems to 
![Screenshot_5](https://github.com/AlexModGuy/AlexsCaves/assets/62995410/155df90d-7219-4967-a67f-e8cc5c3f1853)
me that we still need to increase the chance of caves spawning, they are nowhere to be found

**Comment by Keolass** [comment]
I've already flown through hundreds of thousands of blocks, they're nowhere to be found

**Comment by AlexModGuy** [comment]
dupe

**Comment by Keolass** [comment]
> обмануть

man what I need help

**Comment by Keolass** [comment]
> обмануть

Is the problem that I took a map from creative mode just for testing the mod?
