### ISSUE TITLE
Cannot read field "f_19797_" because "entity" is null

### ISSUE THREAD

**Issue by lukiono** [AlexModGuy/AlexsCaves#499]
Greetings,

Crashing in the world. cant describe this better. i think if its in rendering range then it crashes?

Mod Version 1.0.6
Modpack in use: Medieval Minecraft 4 v19

Playing as Client in a private server

Crashlog:
https://mclo.gs/KPmWZyI

Kind regards

**Comment by AlexModGuy** [comment]
fixed
