### ISSUE TITLE
Possible incompatibility with Sound Physics Remastered

### ISSUE THREAD

**Issue by SireOfTheQuags** [AlexModGuy/AlexsCaves#50]
[crash-2023-10-19_19.57.11-server.txt](https://github.com/AlexModGuy/AlexsCaves/files/13046092/crash-2023-10-19_19.57.11-server.txt)

I think there might be an incompatibility with Sound Physics Remastered according to this crash log. While walking around it just randomly crashes.

**This is using the 1.01 version shared on the Discord.**

**Comment by AlexModGuy** [comment]
nope. mod is built against old forge now, not neoforge. so use that

**Comment by SireOfTheQuags** [comment]
I am using neoforge
