### ISSUE TITLE
absurdky low chance of the caves generating (NOT A BUG just an issue)

### ISSUE THREAD

**Issue by IJMUNDI** [AlexModGuy/AlexsCaves#503]
the caves have absudly low chance of generating.
I got fed up since i didint find any caves and tried the /locate biome command, it took some time for the command to find the biomes but i find it kinda crazy for a mod so hyped up to have almost no chance of spawning 
![image](https://github.com/AlexModGuy/AlexsCaves/assets/148695604/e5a1c85f-3a4e-4e56-a371-253457a56f8e)

**Comment by IJMUNDI** [comment]
![image](https://github.com/AlexModGuy/AlexsCaves/assets/148695604/7bcd47cd-bacb-4d5f-9e33-689e5dcd47c5)
 here the distances from my house

**Comment by jumble67** [comment]
please actually try to have common sense before clogging the already full issues list on here. for one configs for each cave exists to do with generation ( thats why configs are there) and two, the biomes are meant to be rare which is why they have maps ( i know right crazy.

**Comment by AlexModGuy** [comment]
use config
