### ISSUE TITLE
Incompatability - PokeFood

### ISSUE THREAD

**Issue by Ketrai** [AlexModGuy/AlexsCaves#506]
Tested in a large modpack by -JUST- disabling PokeFood.
Stops caves from generating at all, tested for each biome with the '/locate biome' command

PokeFood version : 1.2
Alexcaves version : 1.0.6

Forge version : 47.2.1 for minecraft 1.20.1

Mostly just opening an issue about it so that if others run into compatibility issues they might find this.

**Comment by AlexModGuy** [comment]
Most likely someting to do with this injection
https://github.com/HultraFox/PokeFood/blob/1.20.1-all-Mcreator-Files/src/main/java/net/pokefood/init/PokefoodModBiomes.java#L63
