### ISSUE TITLE
Water Logging Acid Issue

### ISSUE THREAD

**Issue by ExquisiteGoose** [AlexModGuy/AlexsCaves#508]
When acid water logs a block such as a metal rebar, it becomes a new source block. Means acid is A. infinitely renewable, and B. very frustrating to use to oxidase said metal rebars. 

Acid also seems to have issues with what blocks can be water logged, there are many objects that can't be water logged with acid (such as fences), though this may be intentional?

**Comment by AlexModGuy** [comment]
fixed
