### ISSUE TITLE
Entity and world lag

### ISSUE THREAD

**Issue by GlueConsumer** [AlexModGuy/AlexsCaves#510]
Until now the most of the problem has come with the magnetic caves, entities start lagging here and my world just stops working, i can open doors, walk around, but can't take damage in any way and can't interact with blocks like chests or furnaces etc. neither kill or attack any mob, they're all freezed, however getting away from the cave seems to reduce this kind of lag. The problem is occouring again with the primordial caves, but way less present now, mobs don't move smoothly and move jerkily. This problem doesn't occour in places like my base wich is far 1000+ blocks from the nearest cave (primordial cave).
Is it a problem of my pc? maybe it can't support too many entities? My other world was completely freezed and had to create a copy of this where i didn't go in the caves, thought it was a problem of the world, but yeah turns out its apparently a problem of the mod itself.
Also want to add that in my old wolrd I explored the toxic caves without any of these issues, this all occoured with the magnetic caves.

**Comment by GlueConsumer** [comment]
Installed mods are:
Alex's caves and citadel
Waystones
Xaero's world map
Jei
Explorer's compass
Deeper and darker
YUNG's better desert temple

**Comment by AlexModGuy** [comment]
dupe #328
