### ISSUE TITLE
Cave biome map not loading

### ISSUE THREAD

**Issue by Jelenir** [AlexModGuy/AlexsCaves#512]
Basically, i made myself a Cave biome map, excited to explore the magnetic caves. But when i right-clicked the map, it started loading and loading, I've been waiting a lot for something to happen but it just keeps doing this weird, moving-line animation.
Also i forgot to mention that beforehand, i made a different world and used the item. and it worked completely fine...

**Comment by ModifiedMC** [comment]
Are you running any additonal mods with it? Also currently trying to figure out why my cave maps arent loading.

**Comment by Jelenir** [comment]
> Are you running any additonal mods with it? Also currently trying to figure out why my cave maps arent loading.

No, I am not running any other mods. (unless you count Citadel which is required to run the mod)

**Comment by Driestcombee** [comment]
The map takes a while to load, maybe wait for 5 mins ish

**Comment by Driestcombee** [comment]
> > Are you running any additonal mods with it? Also currently trying to figure out why my cave maps arent loading.
> 
> No, I am not running any other mods. (unless you count Citadel which is required to run the mod)

Did you save and reload the game?

**Comment by ModifiedMC** [comment]
Yea I’m 100% certain the maps are bugged, I have left them loading for 10+
minutes to no avail.

**Comment by AlexModGuy** [comment]
dupe #511
