### ISSUE TITLE
[1.20.1] Suggestion: Add configs to set the max health and attack damage of each of Alex's Caves mobs

### ISSUE THREAD

**Issue by TelepathicGrunt** [AlexModGuy/AlexsCaves#516]
Some players asked for this and would be a good idea to add. There are mods out there that can set the max health attributes and stuff but in cases like Vallum Raptor, that resets the max health to 32 or 38 when becoming an elder raptor which will override other attribute modifying mods. So config options that directly set these attributes and handles edge cases like Vallum Raptor would be beneficial. Ferroslime and Magnetron both will need special handling as they dynamically change max health as well.

**Comment by AlexModGuy** [comment]
no
