### ISSUE TITLE
slight incompatibility with Aquamarine  

### ISSUE THREAD

**Issue by PatTheWizard** [AlexModGuy/AlexsCaves#52]
When an Abyssal Chasm spawns under the Aquamirae Biome. It will still generate, however. where the Aquamirae land spawns it will generate huge pillars of stone stretching all the way down going through generated structures and more. It makes the use of the submarine almost useless when trying to use it. 
![2023-10-19_14 02 47](https://github.com/AlexModGuy/AlexsCaves/assets/99378315/919daa79-889d-418b-8c61-4542819e594e)
![2023-10-19_14 03 04](https://github.com/AlexModGuy/AlexsCaves/assets/99378315/ce1eae64-521c-4fd0-b7f9-8705281120c7)

**Comment by AlexModGuy** [comment]
dupe #74
