### ISSUE TITLE
texturas bugeadas

### ISSUE THREAD

**Issue by FranKing278** [AlexModGuy/AlexsCaves#523]
No sé si será culpa de optifine, pero probando con rubidium este se crashea y con optifine aparece asi.
![2023-11-04_20 02 32](https://github.com/AlexModGuy/AlexsCaves/assets/64163531/465271f6-11d9-4915-bd6e-93b7cefaaedf)
![2023-11-04_20 02 33](https://github.com/AlexModGuy/AlexsCaves/assets/64163531/aa1e2278-f87e-4af8-90e2-0f247a047151)

**Comment by AlexModGuy** [comment]
not a AC issue, this is caused by using shaders on the integrated graphics card
