### ISSUE TITLE
Underzealots ritual being way too easy to stop

### ISSUE THREAD

**Issue by pantsguyapp** [AlexModGuy/AlexsCaves#524]
Kill the one in the center and bam, no more ritual, can it get more difficult please

**Comment by kaboom24** [comment]
agreed

**Comment by kaboom24** [comment]
they also stop the ritual if you even get close because they're AI to attack you overrides they're intention to complete the ritual

**Comment by kaboom24** [comment]
maybe add some sort of magical defense while casting a ritual that can only be breached by potions and prevents them from stopping the ritual to chase you for particle affects I was thinking a thin shroud of darkness

**Comment by pantsguyapp** [comment]
Could make it so that in order to stop the ritual, you must take down the "worshippers" first before the main ritualer can be damaged, and yes, even without the worshippers, the ritual is still going, making the players be hurried if they wnt to stop the ritual.

When damaged, worshippers will fight back, making it much harder to stop the ritual now.
