### ISSUE TITLE
It's not because caves are rare that they don't generate any caves in this mod!

### ISSUE THREAD

**Issue by fforepretty** [AlexModGuy/AlexsCaves#526]
There is a problem that I don't know how to solve. It may conflict with other mods, but it won't crash and It doesn't have a crash log
I used instructions, a natural compass, and the map in this mod, but I couldn't find any caves in the world!

It's not because caves are rare that they don't generate caves!

**Comment by fforepretty** [comment]
In addition, I can find and use any item in mod normally in creation mode

**Comment by Driestcombee** [comment]
try making a copy of the world in creative and use /locate to check if anything spawned

**Comment by fforepretty** [comment]
yes i told you i try in creative!
I used the locate command, but it immediately showed that it was not within this range.

In my Alex'cave configuration, I even expanded the map search range to 20000, but it still couldn't find it. I think it must be because the cave couldn't be generated!

I really like your module and hope you can solve this problem!

I initially thought that the formation or terrain module was preventing its generation, so I uninstalled terralith and BiomesOPlenty, but it was still useless and I couldn't find the cave

I can send you my module list. Do you have time to help me solve this problem?

**Comment by fforepretty** [comment]
I thought for a moment, maybe forget it. It's too tricky. I have 300 mods, too many, and it's a lot of trouble finding them

**Comment by AlexModGuy** [comment]
try updating citadel to 2.4.8 and try again

**Comment by Keolass** [comment]
> Я на мгновение подумал, может, забыть об этом. Это слишком сложно. У меня 300 модов, слишком много, и найти их очень проблематично.
> 
> Но мне нравится этот мод, очень не хочу от него отказываться!

Only mods for changing biomes cause problems

**Comment by fforepretty** [comment]
Oh my god!, He really worked, thank you! Updating Citadel to 2.4.8 can solve this problem!

**Comment by fforepretty** [comment]
> > Я на мгновение подумал, может, забыть об этом. Это слишком сложно. У меня 300 модов, слишком много, и найти их очень проблематично.
> > Но мне нравится этот мод, очень не хочу от него отказываться!
> 
> Only mods for changing biomes cause problems
Updating Citadel to 2.4.8 can solve this problem.
