### ISSUE TITLE
Mods cofnlict

### ISSUE THREAD

**Issue by Keolass** [AlexModGuy/AlexsCaves#530]
I don’t know where to turn.
I found a mod that conflicts and block spawn caves - voxelprint deserts

**Comment by AlexModGuy** [comment]
is there a crash log or what

**Comment by Keolass** [comment]
Oh, sorry, for some reason, I thought you could see my previous requests.

No, I'm referring to the fact that I had a conflict with a mod in my last two interactions with you, and my caves didn't spawn.
https://github.com/AlexModGuy/AlexsCaves/issues/486
https://github.com/AlexModGuy/AlexsCaves/issues/493

**Comment by fforepretty** [comment]
> 哦，抱歉，出于某种原因，我以为你可以看到我之前的请求。
> 
> 不，我的意思是我最近两次和你的互动中和模组发生了冲突，并且洞穴没有生成。 [第486章](https://github.com/AlexModGuy/AlexsCaves/issues/486) [第493章](https://github.com/AlexModGuy/AlexsCaves/issues/493)

So have you solved your problem? I have the same problem!

**Comment by AlexModGuy** [comment]
dupe #526

**Comment by Keolass** [comment]
> (#486) [第493章](https://github.com/AlexModGuy/AlexsCaves/issues/493)
> 
> So have you solved your problem? I have the same problem!

Yes, conflicted mod in my case - voxelprint desert
