### ISSUE TITLE
Cave map not working.

### ISSUE THREAD

**Issue by Pheonix5324** [AlexModGuy/AlexsCaves#535]
Whenever I use the cave map it goes left and right but it never goes forwards. I even added the most recent alex's caves and citadel and it didn't work. I also made a new world and it didn't work. But when I got to the cave and moved with the map in my hand, the map started moving. This happens with every cave btw.

**Comment by AlexModGuy** [comment]
can you record this? im afraid i dont understand what you mean

**Comment by Pheonix5324** [comment]
I'm sorry but the video is too big.

**Comment by Pheonix5324** [comment]
https://github.com/AlexModGuy/AlexsCaves/assets/149980045/958a0d4e-6586-4310-bf54-140d03d0b0a6

**Comment by Pheonix5324** [comment]
https://github.com/AlexModGuy/AlexsCaves/assets/149980045/78f2ba12-3522-4461-aad5-a4b1aba11907
