### ISSUE TITLE
Problem with spelunkery table and cave tablets

### ISSUE THREAD

**Issue by Theh3mperor** [AlexModGuy/AlexsCaves#537]
Love the mods but I'm having an issue with your caves mod where no matter how many cave tablets I decipher all I get are magnetic cave scrolls

**Comment by kaboom24** [comment]
maybe its because you are using magnetic cave tablets?

**Comment by Theh3mperor** [comment]
> maybe its because you are using magnetic cave tablets?

Is there a difference, how do I find different types of tablets? I also checked in jei and creative and only say a scroll for magnetic caves as well as a map for only magnetic caves, is there a way to identify other types of tablets?

**Comment by PeglinX** [comment]
Seems like the issue is solved
