### ISSUE TITLE
[suggestion] more control

### ISSUE THREAD

**Issue by kaboom24** [AlexModGuy/AlexsCaves#542]
I think that just in case that a player can still change items while possessed by a totem of possession that should be stopped (I am not sure if that is the case though) but two things I would like to see added are the ability to change a possessed players items around by pressing control your hotbar would change to the hotbar of the possessed player and you could use your number keys to change what they are holding without changing what you are holding also if you press command while looking at a block they will mine that block and maybe make it possible to adjust the order of the items in their inventory as well

**Comment by BiggestBruhMoment** [comment]
Possessed player still can change item is for the balance i think. So it would be more fair for the possessed one cause they still can change item and counter the ability by building a block or pearl away.Having player with totem have complete control of the possessed one could be annoying ngl
