### ISSUE TITLE
Sounds in primordial caves increases but never decreases

### ISSUE THREAD

**Issue by JustAnotherBugReporter** [AlexModGuy/AlexsCaves#548]
Sound in primordial caves seemingly keeps going up and never stops, slowly filling up the max amount of sound effects, however this process is slow.
Leftover sound can be isolated by turning off every sound slider except master volume.

![image](https://github.com/AlexModGuy/AlexsCaves/assets/150121011/472f97ba-4787-4e41-ae6e-42ce0f96b753)
This is with every sound slider off except master.

Tested with:
Alex's Caves
Alex's Mobs
Citadel

**Comment by JustAnotherBugReporter** [comment]
It appears Forlorn Hollows, Abyssal Chasm, and Toxic Caves doesn't have this problem, however Magnetic Caves possibly does.

**Comment by DigitalWendigo** [comment]
Update! 
I've managed to find a temporary workaround without having to relog. 
If you go to the sound settings, you can chose to pick a different sound system from the default one (if you have another choice), which in my case was my headphones. 
Switching between the two, even without closing the settings menu, it will reset the sound cap and fix the issue temporarily. 
However, eventually the cap will be reached again. 
This is tested in the Primordial Caves.

**Comment by DigitalWendigo** [comment]
I've managed to isolate the potential culprit, which seems to be the ambient sounds produced by the primordial cave biome. 
Turning those sounds off in the sound settings seems to stop the buildup of sounds, which previously led to the sound cap being maxed out.

**Comment by AlexModGuy** [comment]
which ambient sounds exactly?

**Comment by JustAnotherBugReporter** [comment]
After using the command /playsound, it seems one of the additions in "alexscaves:primordial_caves_ambience_additions" causes the eventual sound overload.

**Comment by AlexModGuy** [comment]
it was
> dinosaurs_0.ogg
> dinosaurs_1.ogg
> dinosaurs_2.ogg
> dinosaurs_3.ogg
> dinosaurs_4.ogg
> dinosaurs_5.ogg
> dinosaurs_13.ogg
> dinosaurs_14.ogg

looks like these oggs were compressed in the wrong format

**Comment by DigitalWendigo** [comment]
Sorry to poke a closed bug report, but will this also fix the sounds for the Abyssal Chasm? 
In that biome the sounds eventually reach the cap as well. 
Toxic caves seem to be perfectly fine though. 
Haven't tested the other caves yet, since I'm currently just enjoying survival, and am in the Chasm as of this message.
