### ISSUE TITLE
Server crash with 1.0.1

### ISSUE THREAD

**Issue by PlatypusOfHats** [AlexModGuy/AlexsCaves#55]
[crash-2023-10-19_12.15.44-server.txt](https://github.com/AlexModGuy/AlexsCaves/files/13046253/crash-2023-10-19_12.15.44-server.txt)
[latest.log](https://github.com/AlexModGuy/AlexsCaves/files/13046254/latest.log)
[debug.log](https://github.com/AlexModGuy/AlexsCaves/files/13046256/debug.log)

**Comment by AlexModGuy** [comment]
use forge until 1.0.2 is out which will be compatible wirth neoforge again

**Comment by PlatypusOfHats** [comment]
Alright
