### ISSUE TITLE
Game crashes when Deep Ones attack Drowned

### ISSUE THREAD

**Issue by jubdub12** [AlexModGuy/AlexsCaves#551]
Title. First had this problem when a drowned provoked a deep one knight and the game then immediately crashed. Happened again once I befriended the deep ones and defended me from some drowned.

Heres the log:
[crash-2023-11-07_20.43.41-server.txt](https://github.com/AlexModGuy/AlexsCaves/files/13292308/crash-2023-11-07_20.43.41-server.txt)

**Comment by AlexModGuy** [comment]
hotfixed this one https://modrinth.com/mod/alexs-caves/version/1.0.8
