### ISSUE TITLE
Cave Map endless loading time

### ISSUE THREAD

**Issue by ThariCorvy** [AlexModGuy/AlexsCaves#554]
Hello, I'm sure the issue has been reported multiple times already but I have the currently most recent versions of both Citadel and Alex's Caves, the maps have not finished loading for some reason. I'm playing on a multiplayer world hosted by a friend.

I'm not sure what exactly is the issue. Have any of these mods been previously reported incompatible?
![Screenshot 2023-11-08 030226](https://github.com/AlexModGuy/AlexsCaves/assets/139649594/c05922dd-0529-4958-a567-a2ddde18b8ae)

To clarify, that is the server's modpack. The mods shown are outdated.
The server is loading the most recent versions of Alex's Caves (1.0.8) and Citadel (2.4.9).

Update: The biomes are loading fine, we accidentally found the Primordial Caves, but the the cave maps are just not working on multiplayer at all, but they work fine in singleplayer.

**Comment by AlexModGuy** [comment]
dupe #511
