### ISSUE TITLE
Tremorsaurus Crash

### ISSUE THREAD

**Issue by FietDit** [AlexModGuy/AlexsCaves#555]
Whenever a tamed tremorsaurus is attacking any of the deep one mobs, it'll eventually crash the game.

Alex's Caves Version : latest [1.0.8]
Citadel Version : latest [2.4.9]

[this issue might be caused by the deep one mobs attempting a hit on tremor, but dunno if this works on other mobs or only for tremor]

Crash Log :
[Crashlog.txt](https://github.com/AlexModGuy/AlexsCaves/files/13295536/Crashlog.txt)

**Comment by AlexModGuy** [comment]
hotfixed this one. download https://modrinth.com/mod/alexs-caves/version/1.0.8
