### ISSUE TITLE
stored cave maps causing world corruption 

### ISSUE THREAD

**Issue by GoatlyHorisions** [AlexModGuy/AlexsCaves#558]
so as the title says, theres a issue in the 1.0.8 version of alex's caves in which cave maps that have been used have been put in chest's for x amount of time ends up causing the world to be corrupted once the player reopens the map later

its certainly a odd bug thats for sure, but i found this out when retrieving a abyssal chasm map i opened earlier from my storage, the world corrupted and the game crashed when i had it in hand.

**Comment by AlexModGuy** [comment]
https://modrinth.com/mod/alexs-caves/versions/1.0.8
> Curseforge is actively restricting me from uploading the latest build to the website because they have placed new file(s) under 'Manual Review' for multiple days now.
