### ISSUE TITLE
modpack crash

### ISSUE THREAD

**Issue by xp-7** [AlexModGuy/AlexsCaves#561]
i was rendering some faraway chunks and it simply started crashing from nothing.

crash log - https://gist.github.com/xp-7/83697d147e58519c3f336c968e7b667d

**Comment by xp-7** [comment]
looks like its something with the toxic caves biome from alex caves, but still looking for help solving the issue

**Comment by AlexModGuy** [comment]
https://modrinth.com/mod/alexs-caves/versions/1.0.8
> Curseforge is actively restricting me from uploading the latest build to the website because they have placed new file(s) under 'Manual Review' for multiple days now.
