### ISSUE TITLE
Registry Object not present: alexscaves:primal_magma

### ISSUE THREAD

**Issue by SilentStormLE** [AlexModGuy/AlexsCaves#562]
me and my brother play on a lan server and whenever it crashes I'm usually the one who fixes it and it works great, but as the title says it gave me a bizarre error and I cant find a thing about it on here or anything really, it only happens for me and some times just gives me a exit code 1 when it crashes so i haven't a clue what's going on so ill just post the crash log and pray someone can make sense of whats going on 

[crash-2023-11-08_15.07.05-client.txt](https://github.com/AlexModGuy/AlexsCaves/files/13302266/crash-2023-11-08_15.07.05-client.txt)

**Comment by AlexModGuy** [comment]
https://modrinth.com/mod/alexs-caves/versions/1.0.8
> Curseforge is actively restricting me from uploading the latest build to the website because they have placed new file(s) under 'Manual Review' for multiple days now.
