### ISSUE TITLE
Alex's Caves causes server to crash when loading chunks from cave biomes.

### ISSUE THREAD

**Issue by BetaKale** [AlexModGuy/AlexsCaves#563]
The moment anyone on my server get's near a alex's caves biome the server crashes. We're on the latest version, if it's some kind of mod conflict or something I can fix I'd really appreciate the knowledge on how to fix it. Thanks, I've attatched the crash log.

It should be noted that oddly the magnetic caves don't crash the game, but the other ones do. it's very confusing.

Also it looks like it's causing the server to time out, it's like it's getting stuck in some kind of loop while figuring out what should just be another normal game tick.

[crash-2023-11-09_00.41.17-server.txt](https://github.com/AlexModGuy/AlexsCaves/files/13304393/crash-2023-11-09_00.41.17-server.txt)

and here's the latest log from one of the crashes.

[latest.log](https://github.com/AlexModGuy/AlexsCaves/files/13304426/latest.log)

**Comment by BetaKale** [comment]
I'm pretty sure it's a mod compatibility error, but it's weird because it only happens server side, not on singleplayer.

**Comment by BetaKale** [comment]
After a bunch of troubleshooting me and friend found that twigs was definitely crashing it, not sure about the other mods we were using, leaving this open in the hopes that alex sees it

**Comment by VictorHenrique317** [comment]
Also happening with me. Server times out when getting near magnetic caves, but this did not happen when we got to a primordial cave.

**Comment by AlexModGuy** [comment]
dupe #84

**Comment by BetaKale** [comment]
Not a dupe alex you goober. I’m not trying to be rude, but has the exact opposite problem. We were able to go to the magnetic caves just fine, but we’re having trouble with the abyssal chasm, toxic caves, and primordial cave. But it is an incompatibility with twigs. Oh yeah that’s right not trying to be mean no this is annoying, I  like your mod broskito.
