### ISSUE TITLE
Ticking entity crash caused whenever Deep One melee attack is used

### ISSUE THREAD

**Issue by lepr3ch4un** [AlexModGuy/AlexsCaves#566]
Any time a deep one or a deep one knight attempts to hit another mob it causes a ticking entity crash.

**Comment by lepr3ch4un** [comment]
I should mention I'm on multiplayer, the issue doesn't seem to happen in singleplayer

**Comment by nosivaste** [comment]
can confirm this happens to me as well

**Comment by AlexModGuy** [comment]
https://modrinth.com/mod/alexs-caves/versions/1.0.8
> Curseforge is actively restricting me from uploading the latest build to the website because they have placed new file(s) under 'Manual Review' for multiple days now.
