### ISSUE TITLE
music/ambience keep playing after respawn if died in ales's caves

### ISSUE THREAD

**Issue by H2GamingTW** [AlexModGuy/AlexsCaves#57]
the ambience and music of the caves are amazing.  However if you die in one, the audio keeps playing after respawn

**Comment by AlexModGuy** [comment]
actually a bug with vanilla minecraft. test it out in a creative world

1. create a biome of soul sand delta in the overworld with fillbiome
2. stand in it, let the ambience play then do ./kill
3. when you respawn outside of this biome it will still play
