### ISSUE TITLE
Alex's Caves1.0.1 Crash with The Twilight Forest

### ISSUE THREAD

**Issue by MiracleBelief** [AlexModGuy/AlexsCaves#58]
Forge Version
47.2.1

Twilight Forest Version
4.3.1860

Alex's Caves  Version
1.0.1

Client Log
No response

Crash Report (if applicable)
https://gist.github.com/MiracleBelief/6681d491d7d3e5e9465fae10b88a6227

Steps to Reproduce
1 Enter the Naga Courtyard
2 Game crashing when Naga spawner

Additional Details
When i remove  Alex's Caves,the crash didnot happend again.

The Member of TeamTwilight think the problem mod is Alex's Caves.
https://github.com/AlexModGuy/AlexsCaves/blob/main/src/main/java/com/github/alexmodguy/alexscaves/mixin/EntityMixin.java#L208

 **And I like this mod ,  thank you for making it.**

**Comment by Blugori** [comment]
Was it fixed ?
