### ISSUE TITLE
Neodymium particles temporarily show up as green and can be seen through walls

### ISSUE THREAD

**Issue by dabomb6405** [AlexModGuy/AlexsCaves#581]
![2023-11-09_22 42 01](https://github.com/AlexModGuy/AlexsCaves/assets/66895105/f95a922a-8b4f-4940-ae31-805857544b6c)
Using latest Alex's Caves and Citadel, important to note that I did not have this issue before the latest update.

**Comment by dabomb6405** [comment]
Important note I just discovered, this is only happening with Azure Neodymium.

**Comment by kaboom24** [comment]
same
