### ISSUE TITLE
How to make deep ones friendly again?

### ISSUE THREAD

**Issue by dcc2123** [AlexModGuy/AlexsCaves#590]
Not a bug but I don't know where else to ask- is there any possible way to re-establish good relations with deep ones once they've become hostile? There is a huge abyssal chasm I'd love to explore but the entire area is off limits to me because I am instantly killed by deep ones whenever I get near.

**Comment by KalebMorton** [comment]
you can increase your relationship with the deep ones by trading with them. I would recommend barricading yourself in a place where the deep ones cant reach you, but where you still can access a trading pedestal.

**Comment by dcc2123** [comment]
> you can increase your relationship with the deep ones by trading with them. I would recommend barricading yourself in a place where the deep ones cant reach you, but where you can still access a trading pedestal.

Well you need pearls to trade, right? The thing is, I can't even get to the bottom of the chasm to collect pearls in the first place

**Comment by KalebMorton** [comment]
If you can get your hands on a mussel, then you can plant it on a log submerged in water to grow more. From there you can farm mussels to get pearls
