### ISSUE TITLE
Lumberjackosaurus, Cave Painting Advancements do not grant upon completeing the task required

### ISSUE THREAD

**Issue by ComeMyChild** [AlexModGuy/AlexsCaves#599]
On a server, the Lumberjackosaurus advancement does not grant upon feeding a relicheirus the primordial soup. The relicheirus still does what it's supposed to, but the advancement doesn't grant.

Similarly, right clicking smooth limestone with charcoal creates the cave painting, but the advancement doesn't grant either. Consequently, this means we cannot get the time of titans advancement either.

**Comment by emeryplyler** [comment]
I have this exact problem. I couldn't get the regular cave painting achievement, but I could get the one after it for painting the large unknown creature.
