### ISSUE TITLE
[1.20.1] Crash when entering Singleplayer world.

### ISSUE THREAD

**Issue by Gbergz** [AlexModGuy/AlexsCaves#60]
**What happened?**: 
Client crash to desktop when joining Singleplayer world.
Error:  `Exception initializing level`

**Versions**:
MC: 1.20.1
Forge: 47.1.3
Alex's Caves: 1.0.1
Citadel: 2.4.5

**Crash-Report**: 
Link: https://gist.githubusercontent.com/Gbergz/a008d373d965b854c77107aa68024b36/raw/71a03d209f92c7d4fb0701c060e48307d12e409d/gistfile1.txt

**Comment by AlexModGuy** [comment]
fixed in 1.0.2
