### ISSUE TITLE
primordial caves problems

### ISSUE THREAD

**Issue by kaboom24** [AlexModGuy/AlexsCaves#602]
1: the tremorsaurus bugs out when the raygun is used it just goes animation crazy
2: I have never been able to see a amber monolith spawn creatures even if I wait a while it might be a bug
3: sometimes in the primordial caves you cant move or even change the direction you are looking without ambersol rays glitching
this last is a question are you guys planning to ever add the creature from the mystery cave painting

**Comment by JustAnotherBugReporter** [comment]
If you are in creative, can you run the command "/data get block ~ ~ ~" replace the ~'s with the coordinates of the amber monoliths, it'll show you the next time it will spawn.

**Comment by jamesipod** [comment]
I'm having the same issue, it shows it won't spawn for 29000 ticks, or 25 minutes.

**Comment by JustAnotherBugReporter** [comment]
> I'm having the same issue, it shows it won't spawn for 29000 ticks, or 25 minutes.

If I recall, you can change the amount of ticks it takes for an amber monolith to spawn new mobs, the default time it takes a monolith to spawn is not really an issue.
