### ISSUE TITLE
Incompatibility issue with Nether Dungeons

### ISSUE THREAD

**Issue by PeglinX** [AlexModGuy/AlexsCaves#607]
### **When the Desolate Dagger entity kills anything the game crashes.** 
Should I report this issue to Nether Dungeons or is it from Alex's Caves end?

Mods: Citadel, Alex's Caves, Nether Dungeons
Version: 1.20.1

[https://mclo.gs/Ua9Me97](url)

**Comment by PeglinX** [comment]
If you need any more info I will be happy to provide.

**Comment by AlexModGuy** [comment]
> 	at com.teamdurt.netherdungeons.event.NDEventsHandler.applyVampirismEffect(NDEventsHandler.java:22) ~[netherdungeons-1.1.0-alpha2.jar#151!/:1.1.0-alpha2] {re:classloading}

not my crash report it to those devs

**Comment by PeglinX** [comment]
sure
