### ISSUE TITLE
Mine Guardians have a Literal Stroke if you Place it in the Right Amount of Water

### ISSUE THREAD

**Issue by Jasdernn** [AlexModGuy/AlexsCaves#608]
Don't really know how to explain this, but place a mine guardian in a like 3-4 block deep water and see
![2023-11-12_15 16 56](https://github.com/AlexModGuy/AlexsCaves/assets/148498785/6e583915-a9c8-41d2-a840-50c8f162cacf)
![2023-11-12_15 16 42](https://github.com/AlexModGuy/AlexsCaves/assets/148498785/b6cd9831-9785-4a6c-b60d-151f412ab4fc)
![2023-11-12_15 21 44](https://github.com/AlexModGuy/AlexsCaves/assets/148498785/5c6b5b14-7422-4ba9-a81f-9bbad7d643f9)

**Comment by PeglinX** [comment]
Have the same bug
