### ISSUE TITLE
error in translation of guide book

### ISSUE THREAD

**Issue by Vitinho3605** [AlexModGuy/AlexsCaves#612]
![error](https://github.com/AlexModGuy/AlexsCaves/assets/59752047/11e0438e-a116-4b69-84fb-4859b7a8aa46)
in the Brazilian Portuguese translation, the guide book ended up mixing the images with the words and as I'm not fluent in English, this makes it difficult for me to read. ficarei feliz caso vocês me notem

**Comment by AlexModGuy** [comment]
dupe #16
