### ISSUE TITLE
Make the caves more common

### ISSUE THREAD

**Issue by 31274685126** [AlexModGuy/AlexsCaves#615]
It isn't a bug but i need you to make the caves way larger and way more common, i can't walk 3856 blocks to find a mini toxic cave, and even if i don't want to walk the /locate biome ... commant isn't working either

**Comment by PeglinX** [comment]
you can change it on the config

**Comment by 31274685126** [comment]
oh wait fr? that would save me a bunch of time then, thx

**Comment by PeglinX** [comment]
Time to delete this post

**Comment by KingstoneMaxamose** [comment]
> you can change the size and rarity in the confit file.

Hey I'm new to doing stuff regarding changing this, but would you mind explaining the changes that would be needed to do this and/or linking a guide if one exists?

**Comment by PeglinX** [comment]
Yeah. There’s two main ways.


 First one. Have a config mod. (easy): 
Have either Create, [](https://www.curseforge.com/minecraft/mc-mods/config-menus-forge), or any other mod that offers in game config. 

> In the case you got Create just click the goggles button to open the mods config. Search for Alex’s Caves and there will be the config. Go to General/WorldGen
>In the case of Config Menus Forge click the menu button on the main menu or in the pause screen. Then search for Alex’s Caves. From ther it’s the same as Create’s route


Second One. The classic:
In your appdata (stored in your launcher), near your mod folder there should be a modconfig file. Inside look for Alex’s Caves and follow the same route as before.

**Comment by KingstoneMaxamose** [comment]
So I used create and I have only found that I can change the size and distance between them, is there a way to make them more common though as I have been unable to locate more than 1-2 of the biomes in a world at a time without going tens of thousands of blocks?

**Comment by PeglinX** [comment]
For me decreasing the distance between them did make them more common

**Comment by KingstoneMaxamose** [comment]
That is possible probably either Tectonic, Regions Unexplored, William Wythers's EE and/or William Wythers OO.

**Comment by PeglinX** [comment]
Doesn’t seem like others have problems with those mods (no documentation for William)

**Comment by KingstoneMaxamose** [comment]
Wacky.

**Comment by PeglinX** [comment]
You could crate an instance with just William, and Alex’s caves (obv with libraries). And test. If you find the biomes rarer than with only William then you got a bug.

**Comment by KingstoneMaxamose** [comment]
I uninstalled and reinstalled all the worldgen mods and now the cave generate how they should, this has furthered my belief that 90% of minecraft mods work off of literal magic.

**Comment by PeglinX** [comment]
I thought you already did that. Newest alec’s caves review said to delet config files as there were changes
