### ISSUE TITLE
if i look on ray cat, or on irritated mobs or players i have lags and fps drop

### ISSUE THREAD

**Issue by artemius00789** [AlexModGuy/AlexsCaves#616]
hey everyone if i look on ray cat, or on irritated mobs or players, i have fps drop
version of the alex caves 1.0.8
version of the citadel 2.4.9

**Comment by PeglinX** [comment]
sounds like a dupe of #157

**Comment by AlexModGuy** [comment]
dupe https://github.com/AlexModGuy/AlexsCaves/issues/157

**Comment by artemius00789** [comment]
Alex
i have lags if i on wide screen
