### ISSUE TITLE
Raycat Lag the game every time i look at him

### ISSUE THREAD

**Issue by SilvsLovesCapybaras** [AlexModGuy/AlexsCaves#619]
every time i look at a raycat my minecraft gets a fps drop, mabey its bescause the lighting effect

**Comment by PeglinX** [comment]
dupe of https://github.com/AlexModGuy/AlexsCaves/issues/157 It,s already worked on

**Comment by AlexModGuy** [comment]
check ou tthe radiation option in the client config
