### ISSUE TITLE
magnetic bug

### ISSUE THREAD

**Issue by phvfrancisco** [AlexModGuy/AlexsCaves#622]
the same bug i ve reported other day, the mobs freze, you dont take damage, when you breack blocks they dont drop, liquid dont fluid. ive noticed thet this hapens only wen i enter one magnetic caves (maybe because of the magnetic efect of neodoniun) this hanpens only in the area of the magnetic caves and need like 20 seconds to start

**Comment by AlexModGuy** [comment]
dupe #370
