### ISSUE TITLE
Deep Ones Attacking Drowned Crash

### ISSUE THREAD

**Issue by SiccoJO** [AlexModGuy/AlexsCaves#623]
Ive Recently Befriended The Deep Ones Within The Abyssal Chasm. as expected they defend me by attacking any drowned zombies that harm me, but whenever any of the Deep Ones attack said drowned, my game crashes. Im uncertain as to why this causes a crash. but heres the crash log.

The game crashed whilst ticking entity
Error: java.lang.ClassCastException: class net.minecraft.world.entity.monster.Drowned cannot be cast to class net.minecraft.world.entity.player.Player (net.minecraft.world.entity.monster.Drowned and net.minecraft.world.entity.player.Player are in module minecraft@1.20.1 of loader 'TRANSFORMER' @65bd19bf)

**Comment by AlexModGuy** [comment]
reinstall mod
