### ISSUE TITLE
Suggestion: Nerf Explorer's Compass

### ISSUE THREAD

**Issue by Vinzound** [AlexModGuy/AlexsCaves#624]
I seems like a good idea to prevent the Nature's Compass mod from being able to locate the caves in this mod, sadly with Explorer's Compass you can still locate the caves by searching for their respective structures. It would be great if you couldn't locate the Alex's Caves structures with Explorer's Compass either.

**Comment by Pheonix5324** [comment]
He already did. Alex showed it in the discord.
