### ISSUE TITLE
Bug involving lava and quarry

### ISSUE THREAD

**Issue by Ghillywhilly** [AlexModGuy/AlexsCaves#625]
Placing lava on quarry blocks causes the game to crash whenever those blocks are rendered in. Bug was discovered by my friend who placed the lava on the quarry blocks in order to burn it quick due to him being lazy.

**Comment by AlexModGuy** [comment]
![2024-03-02_10 02 20](https://github.com/AlexModGuy/AlexsCaves/assets/8662109/546f4977-f233-40e2-9fb3-a1f508f116e0)
not able to replicate
