### ISSUE TITLE
Toxic caves not generating (1.08)

### ISSUE THREAD

**Issue by LookLuke1** [AlexModGuy/AlexsCaves#628]
I reset the chunks of the toxic caves, but it still didn't generate. So I opened up my test world to see if it generates at all when I located the biome it still didn't generate but, the Forlorn Hollows cave generated near it which is weird because, on my way to the toxic caves in my world I came across a Forlorn Hollows cave. It just seems to be affecting older worlds as well and I currently have two other mods installed in my game: Alex's Mobs and the Essential Mod. I also reset my configs for Alex's caves when 1.08 came out.

**Comment by LookLuke1** [comment]
Note: it seems to be an issue with older worlds of mine

**Comment by AlexModGuy** [comment]
dupe #395
