### ISSUE TITLE
Can't step up on small blocks

### ISSUE THREAD

**Issue by Inonedn** [AlexModGuy/AlexsCaves#63]
https://github.com/AlexModGuy/AlexsCaves/assets/36087299/df37bc71-be76-4be1-a327-88dacd6c5794

**Comment by Mey-Ha-Zah** [comment]
You might want to provide a modlist.

**Comment by AlesTheGreat** [comment]
it happens to me too, the only additional mod that i have is Just Enough Items.

**Comment by Gbergz** [comment]
Still an issue on 1.0.2
