### ISSUE TITLE
Cave map not working

### ISSUE THREAD

**Issue by Pheonix5324** [AlexModGuy/AlexsCaves#632]
https://github.com/AlexModGuy/AlexsCaves/assets/149980045/ebd45bd8-43b3-4bdc-b76e-a9dbf11221ec

**Comment by Pheonix5324** [comment]
https://github.com/AlexModGuy/AlexsCaves/assets/149980045/363c43da-277c-44d7-95a9-75924d81424d

**Comment by AlexModGuy** [comment]
??? looks fine to me
