### ISSUE TITLE
Biomes don't generate on servers as of latest version

### ISSUE THREAD

**Issue by MrIcepackager** [AlexModGuy/AlexsCaves#635]
Hello I am experiencing an issue where cave biomes will not generate in multiplayer, but will in singleplayer. I am using Alexs Caves 1.0.8 and Citadel 2.4.9. 
This issue includes cave maps loading until a failure to locate biome message appears, and the /locate command not being able to find anything. Yes, I did try to teleport really far from spawn but even then it didn't work.
For some more information I am not using these two mods **by themselves** but instead they are included in a modpack
Any tips will help, thanks.

**Comment by AlexModGuy** [comment]
youre going to need to try and install mods one by one until you find out what is conflicting with AC

**Comment by MrIcepackager** [comment]
!Fixed!
-i deleted ALL config files, like the changelog said and it worked lol
