### ISSUE TITLE
game keeps crashing for no reason

### ISSUE THREAD

**Issue by balls43** [AlexModGuy/AlexsCaves#64]
The game crashed whilst encountered exception while building chunk meshes
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.client.renderer.texture.TextureAtlasSprite.m_118367_(double)" because "sprite" is null
it says

**Comment by balls43** [comment]
only mods ive got is old combat, alex's caves, citadel and  rubidium

**Comment by AlexModGuy** [comment]
seems to be an issue with rubidium

**Comment by AlexModGuy** [comment]
#78
