### ISSUE TITLE
Crash Submarine in Blue Skies mod's dimensions

### ISSUE THREAD

**Issue by SaraXianLin** [AlexModGuy/AlexsCaves#645]
Forge: 47.2.0
MC: 1.20.1
Mod version: 1.0.8
Modpack: Yes Nicer Minecraft Forge 1.1.6

Link to crash report: https://gist.github.com/SaraXianLin/37020c67b6655281bd5f182660d7a27a

Link to Latest logs: https://gist.github.com/SaraXianLin/129879e489e44ce60abdf8219ccc2e24

I am trying to use the submarine in the Everbright dimension from the mod "Blue skies" due there are huge oceans however it keeps crashing.

Thank you,
Regards,
Sarah

**Comment by AlexModGuy** [comment]
> at de.keksuccino.fancymenu.menu.fancy.music.AdvancedMusicTicker.m_120184_
not my mod. FancyMenu music crash
