### ISSUE TITLE
Abyssal Map lead me to no where

### ISSUE THREAD

**Issue by GauntAndreX8** [AlexModGuy/AlexsCaves#648]
![2023-11-19_19 34 50](https://github.com/AlexModGuy/AlexsCaves/assets/85809443/6d78aad7-a4c1-4bcb-89ca-611e58a565d3)
![2023-11-19_19 34 39](https://github.com/AlexModGuy/AlexsCaves/assets/85809443/d88f3861-9bee-4457-a43f-793d3a580666)
![2023-11-19_19 34 25](https://github.com/AlexModGuy/AlexsCaves/assets/85809443/32225681-f2ef-410c-a047-80b1c6977292)

Used the map that suppose to take me to the cave but there isn't one

**Comment by AlexModGuy** [comment]
dupe #507
