### ISSUE TITLE
[Client crash] Unexpected error - caused by Watcher

### ISSUE THREAD

**Issue by DevDyna** [AlexModGuy/AlexsCaves#652]
After summoned it send on crash [idk if was caused mainly by AlexCaves or Forcecraft]
[crash-2023-11-21_21.09.09-client.txt](https://github.com/AlexModGuy/AlexsCaves/files/13430600/crash-2023-11-21_21.09.09-client.txt)
[Exploration Fabrique-1.5.zip](https://github.com/AlexModGuy/AlexsCaves/files/13430612/Exploration.Fabrique-1.5.zip)

**Comment by JustAnotherBugReporter** [comment]
Watcher works fine on my part, it's probably forcecraft.
