### ISSUE TITLE
Hoppers don't work with the Nuclear Furnace

### ISSUE THREAD

**Issue by SiriFromPhotop** [AlexModGuy/AlexsCaves#653]
I wanted to make an automatic super smelter with the Nuclear Furnace, but couldn't because hoppers aren't compatible with it. If this is intentional, I am sorry for the inconvenience. A picture will be linked.

![image](https://github.com/AlexModGuy/AlexsCaves/assets/124091206/cd31beeb-9c11-4dd0-be09-078c70c1600e)

**Comment by ItsRandomPerson** [comment]
Hoppers are compatible with the Nuclear Furnace, it's just that each side of the nuclear furnace only takes a certain input.
Left side takes in Metal Barrels
Right side takes in Uranium Rods
Front and back sides takes in the input ingredients
Bottom side ejects both output and waste barrels

**Comment by AwesomeCaden73** [comment]
Ah, the possibilities with the Create mod...
