### ISSUE TITLE
Abyssal Chasm generates Strangely in Frozen Oceans

### ISSUE THREAD

**Issue by Jasdernn** [AlexModGuy/AlexsCaves#655]
I think I know the problem. It thinks icebergs are like islands and fill in the bottom of them to the bottom of the world, if that makes sense to you.
There are also these weird checkerboard things that generate as well.
![2023-11-21_22 50 37](https://github.com/AlexModGuy/AlexsCaves/assets/148498785/29157cad-48b8-405b-bf5b-461b824c926b)
![2023-11-21_22 51 00](https://github.com/AlexModGuy/AlexsCaves/assets/148498785/db0844da-cb4b-4d14-b627-604eaca3bcfd)
Also, there are no mods to my knowledge that would affect this (Like Aquamarine)

**Comment by AlexModGuy** [comment]
dupe #74
