### ISSUE TITLE
Game crashes after using the cave compendium with Rubidium.

### ISSUE THREAD

**Issue by Trizoft** [AlexModGuy/AlexsCaves#660]
The moment I right click while holding the cave compendium, the game crashes. I'm using the newest version. This happens every time I try to use the item. Citadel is installed. Found out the issue is only present when using Rubidium. (The unofficial forge version of sodium)

**Comment by Leviacan** [comment]
Try Embeddium instead of Rubidium.

**Comment by AlexModGuy** [comment]
crashlog?
