### ISSUE TITLE
Cave Maps don't lead to caves sometimes 

### ISSUE THREAD

**Issue by Nightrider183** [AlexModGuy/AlexsCaves#662]
Sometimes the cave map will load, but it will lead nowhere close to a cave of its type. recently it did this with abyssal chasm, I even did /locate and it only found a toxic cave 2000 blocks away.

**Comment by GauntAndreX8** [comment]
Yeah same thing as well

**Comment by AlexModGuy** [comment]
dupe #466

**Comment by nocturn9x** [comment]
> dupe #466

Are you just going to keep cross-linking issues and closing them without actually resolving them? LoL
