### ISSUE TITLE
Server crash when interact with Drowned

### ISSUE THREAD

**Issue by sirvellen** [AlexModGuy/AlexsCaves#668]
[crash-2023-11-25_18.04.50-server.txt](https://github.com/AlexModGuy/AlexsCaves/files/13465051/crash-2023-11-25_18.04.50-server.txt)

**Comment by sirvellen** [comment]
It seems like your Minecraft server encountered a `ClassCastException` while ticking an entity. The error is coming from the `DeepOneBaseEntity` class in the `alexscaves` mod. Here's a breakdown of the error:

```java
java.lang.ClassCastException: class net.minecraft.world.entity.monster.Drowned cannot be cast to class net.minecraft.world.entity.player.Player
```

This error indicates that somewhere in the `DeepOneBaseEntity` class, there is an attempt to cast an instance of `Drowned` (a type of monster entity) to `Player`, which is not allowed.

```java
at com.github.alexmodguy.alexscaves.server.entity.living.DeepOneBaseEntity.checkAndDealMeleeDamage(DeepOneBaseEntity.java:528)
```

The problematic code is in the `checkAndDealMeleeDamage` method of `DeepOneBaseEntity` at line 528.

```java
Caused by: java.lang.ClassCastException: class net.minecraft.world.entity.monster.Drowned cannot be cast to class net.minecraft.world.entity.player.Player (net.minecraft.world.entity.monster.Drowned and net.minecraft.world.entity.player.Player are in module minecraft@1.20.1 of loader 'TRANSFORMER' @72001c71)
```

The error traceback shows that the issue is causing the server to crash.

To fix this issue, you should look into the `DeepOneBaseEntity` class and find the code at line 528. Ensure that you are not trying to cast a `Drowned` entity to a `Player` entity, as this is causing the `ClassCastException`. Update the code to handle the entities appropriately.

Additionally, make sure that you are using the latest version of the `alexscaves` mod, as newer versions may have fixed this issue. If the problem persists, you may want to report the issue to the mod author or check for any open issues on the mod's GitHub repository.

**Comment by AlexModGuy** [comment]
update the mod

**Comment by sirvellen** [comment]
but I'm on 1.0.8 version

вс, 26 нояб. 2023 г., 03:19 Alexthe668 ***@***.***>:

**Comment by sirvellen** [comment]
![image](https://github.com/AlexModGuy/AlexsCaves/assets/54562128/1e29f194-b5af-440c-b53f-e7eff22426fa)
my crash report from the latest available version
