### ISSUE TITLE
[Permission Request] Backport to 1.19.2

### ISSUE THREAD

**Issue by min2222** [AlexModGuy/AlexsCaves#677]
hello. i'm a modder who mainly does porting/backporting of mods. since this mod is only available for 1.20.1, but 1.19.2 is still popular version. and lots of people still play the version. so i just backported the mod to 1.19.2, but i realized that i didn't ask permission to you. could i get permission for publishing it in github? (i'm not gonna upload it on curseforge or other mod site)
[link to the repository](https://github.com/min2222/AlexsCaves-Backport)

**Comment by BiggestBruhMoment** [comment]
wait, arent you the guy who port that one bedrock mod into java?

**Comment by AlexModGuy** [comment]
no. The mod depends on new 1.20 features and wouldnt be complete without them.

**Comment by proagaks1** [comment]
I REALLY liked this mod but unfortunately its on 1.20.1 only. I wish it will get a backport to 1.19.2. Props to the team.

**Comment by Sa1ZeR** [comment]
> hello. i'm a modder who mainly does porting/backporting of mods. since this mod is only available for 1.20.1, but 1.19.2 is still popular version. and lots of people still play the version. so i just backported the mod to 1.19.2, but i realized that i didn't ask permission to you. could i get permission for publishing it in github? (i'm not gonna upload it on curseforge or other mod site) [link to the repository](https://github.com/min2222/AlexsCaves-Backport)

Link is dead. Can you share the backport?

**Comment by kitovoi111** [comment]
> no. The mod depends on new 1.20 features and wouldnt be complete without them.

A real Jew! Greedy, vile, it's a shame to be like that!

**Comment by Enastr** [comment]
Link is dead. Can you share the backport?

**Comment by Spiderman22er** [comment]
I was able to find its port on 1.19.2
 I immediately say I was banned for making links to it, so I hope Google won't ban it, as well as github.
https://drive.google.com/drive/folders/1PGVBR805S0jw5U8DnonCrF7a6vk18r1l?usp=drive_link

**Comment by kitovoi111** [comment]
> I was able to find its port on 1.19.2 I immediately say I was banned for making links to it, so I hope Google won't ban it, as well as github. https://drive.google.com/drive/folders/1PGVBR805S0jw5U8DnonCrF7a6vk18r1l?usp=drive_link

this my port lol

**Comment by kitovoi111** [comment]
> I was able to find its port on 1.19.2 I immediately say I was banned for making links to it, so I hope Google won't ban it, as well as github. https://drive.google.com/drive/folders/1PGVBR805S0jw5U8DnonCrF7a6vk18r1l?usp=drive_link

Зачем ты мне кидаешь мой же порт? Сервер Cristalix там сделали его

**Comment by Spiderman22er** [comment]
> Many people also want to play on 1.19.2 with this mod, for example, many English people do not know cristalix and the Create mod itself and IC2, so I want many people to play with it + it has been changed and I understand that this can be considered theft, but I just want to leave this mod to other people

**Comment by Spiderman22er** [comment]
И вообще кракед ты же испортил сам себе же репутацию кто будет играть на сервере с 4 онлайном?

**Comment by Spiderman22er** [comment]
А хотя зачем тебе нужен был Alex Caves на 1.19.2 хотя сам же его удалял много раз

**Comment by ERROR-17** [comment]
;-;

**Comment by BJOFA** [comment]
@kitovoi101 у тебя остался Archeology API, просто нужен для разработки мода
