### ISSUE TITLE
1.20.1 Alex's caves server crash & not generating at all/crashing in singleplayer

### ISSUE THREAD

**Issue by Marus0** [AlexModGuy/AlexsCaves#680]
Forge 47.2.0

Steps to reproduce: 

1. Install my modlist and launch the game, generate a world
2. Locate and head to the nearest biome included in the mod (tested only with primordial caves)
3. Game crashes

Crash report: https://gist.github.com/Marus0/b695b0fd50959da68c0d40a479e25322

Will provide info about this if needed

**Comment by AlexModGuy** [comment]
uninstall twigs 
dupe #84
