### ISSUE TITLE
Deep Ones attacking warden causes crash

### ISSUE THREAD

**Issue by 29Raptors** [AlexModGuy/AlexsCaves#681]
I first encountered this bug while using a magic conch in an ancient city to help me kill wardens.
After further testing, I found that any type of deep one attacking the warden will cause the crash.

Crash Report:
[crash-2023-11-29_21.02.38-server.txt](https://github.com/AlexModGuy/AlexsCaves/files/13507523/crash-2023-11-29_21.02.38-server.txt)

**Comment by AlexModGuy** [comment]
Reinstall the mod
