### ISSUE TITLE
Quarrys

### ISSUE THREAD

**Issue by Megamonster333** [AlexModGuy/AlexsCaves#689]
The items just spewing out the top of the quarry is a bit of a pain with having to use hoppers around it to collect everything. Can it be made so a chest placed on top of the quarry can collect the items it spits out? Thanks. 

Also the fact when it's done mining and must be broken it doesn't drop itself, just the ingots, kinda sucks. Especially for how long it can take to make. Same with the quarry block itself not being able to be picked up again.

**Comment by AlexModGuy** [comment]
all intentional
