### ISSUE TITLE
weird spawning with alex's mobs

### ISSUE THREAD

**Issue by ashissilly** [AlexModGuy/AlexsCaves#692]
Tried entering the primordial caves in a server with my friends and all I found was a TON of cave centipedes and murmurs. no clue what is causing this, but it makes it nearly unplayable.

**Comment by BiggestBruhMoment** [comment]
> You probably have TACT, right? Since that mod puts all of the caves into the "#forge:is_cave" and "#minecraft:is_overworld", murmurs and cave centipedes spawn.

Yea, either you delete the tact mod or disable murmur and cave centipede spawn on primordial cave
