### ISSUE TITLE
[1.20.1] Potential Wandering Trader Issue

### ISSUE THREAD

**Issue by AetheriMC** [AlexModGuy/AlexsCaves#693]
Minecraft v1.20.1
Forge v.47.2.4
AlexsCaves v1.0.8

This may not be an issue derived from Alex's Caves but I'm starting here assuming that the trade is generated by this mod due to the items involved.

A wandering trader has appeared with the following trade:

- Netherite Ingots [x3]
- Infused Coins [x5] (Apotheosis)
- Selling an enchanted Desolate Dagger from Alex's Caves

![image](https://github.com/AlexModGuy/AlexsCaves/assets/64112227/8f848053-a84a-4c23-873d-b9f0ed0ebf5d)

While the coins are being accepted, the trader is refusing to take the netherite ingots I recently crafted. When looking at the trader's NBT data, I see that the ingots the trader is looking for have a {Damage:0} tag, which seems to be causing the mismatch issue.

![image](https://github.com/AlexModGuy/AlexsCaves/assets/64112227/355a6a02-3cd9-4629-b5b5-60a53da07d8c)

Is this trade something that AC inserts into the table for Wandering Traders? If it is, can the tag be removed? If not, could you help me understand where Minecraft derives its trades so I can look elsewhere?

**Comment by JustAnotherBugReporter** [comment]
This is not a Alex's Caves issue, the mod Apotheotic Additions appears to be the problem.

**Comment by AetheriMC** [comment]
Ah, ok thank you for letting me know! These things are hard to identify sometimes :)
