### ISSUE TITLE
The caves aren't generated on a new world.

### ISSUE THREAD

**Issue by Nicolaco08** [AlexModGuy/AlexsCaves#696]
Hey! Here is my issue: I have a forge server and, with the same mods, the original world doesn't have problems. I have then generated a new world by removing the /world folder, and now the caves are not found with /locate command. What to do?

**Comment by JustAnotherBugReporter** [comment]
I recommend using cave maps, if you updated from an earlier version to 1.0.8, you'll need to delete the configurations files.

**Comment by Nicolaco08** [comment]
Yes! I did it and it solved. Thank you.

Nicolò Castello

Sent from Proton Mail mobile

-------- Original Message --------
