### ISSUE TITLE
Crashing once hovering over pottery shards

### ISSUE THREAD

**Issue by pony-memes** [AlexModGuy/AlexsCaves#70]
Whenever I so much as hover my mouse over the pottery shards within the Abyssal Chasm tab the game freezes and then hard crashes to desktop with the error window displaying:

"The game crashed whilst rendering screen
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.client.resources.model.Material.m_119204_()" because the return value of "net.minecraft.client.renderer.Sheets.m_272280_(net.minecraft.resources.ResourceKey)" is null"

**Comment by AlexModGuy** [comment]
full crash log?

**Comment by pony-memes** [comment]
[crash-2023-10-19_23.26.19-client.txt](https://github.com/AlexModGuy/AlexsCaves/files/13047921/crash-2023-10-19_23.26.19-client.txt)
Is this it?

**Comment by AlexModGuy** [comment]
dupe, conflict with supplimentaries

**Comment by pony-memes** [comment]
Ah . .shit
