### ISSUE TITLE
AlexCaves & Vampirism mod

### ISSUE THREAD

**Issue by Moneido** [AlexModGuy/AlexsCaves#703]
With both mods installed (Alex's caves / Vampirism) whenever I visit a Vampire Forest, the fog generated in the biomes starts flickering very fast whenever I move inside the biome. Removing Alex's Caves resolves the issue.

(I am NOT using any shaders)

**Comment by AlexModGuy** [comment]
Issue with vamparism.
https://github.com/TeamLapen/Vampirism/blob/1.20/src/main/java/de/teamlapen/vampirism/client/renderer/RenderHandler.java#L177
dev should not make calls to render system... they should use the event.setFarPlaneDistance method as provided by the event
