### ISSUE TITLE
Weird green particles in magnetic caves

### ISSUE THREAD

**Issue by ChrisLTheNerd** [AlexModGuy/AlexsCaves#705]
I'm using alexscaves-1.0.8 with citadel-2.4.9-1.20.1 on forge-47.2.16 and I am getting some weird green particles in the Magnetic Caves. I tested it with no other mods installed apart from Citadel and reset the configs just in case.
![2023-12-11_20 41 40_2](https://github.com/AlexModGuy/AlexsCaves/assets/50182206/8d56510e-56da-49e3-8f7b-16f5549ed84e)

And sometimes they're not there.
![2023-12-11_20 41 50](https://github.com/AlexModGuy/AlexsCaves/assets/50182206/04904e0d-9c73-43b6-bb6b-e7e4fa9e045a)

**Comment by AlexModGuy** [comment]
dupe #705

**Comment by AlexModGuy** [comment]
* #581
