### ISSUE TITLE
[FeatureRequest] Add terra support

### ISSUE THREAD

**Issue by zeid0ne** [AlexModGuy/AlexsCaves#707]
Alexs Caves biomes doesnt generate with the world generation mod Terra https://github.com/PolyhedralDev/Terra

Please let me know if this is possible, thanks

I also asked to them, maybe thats easier to update their mod https://github.com/PolyhedralDev/Terra/issues/443

**Comment by AlexModGuy** [comment]
https://github.com/PolyhedralDev/Terra/issues/357

Mod isnt compatible with any other biome mods out the box. not our issue.
