### ISSUE TITLE
Loading magnetic caves chunks freezes game

### ISSUE THREAD

**Issue by PatrickShann0n** [AlexModGuy/AlexsCaves#708]
Whenever I go into any trunks with a magnetic cave the only thing that is able to move is my character no entities spawn if they already have they no longer move and chunks no longer load

**Comment by PatrickShann0n** [comment]
![Uploading 0a13174d-1563-419c-b605-1834d48b0481.jpg…]()

**Comment by JustAnotherBugReporter** [comment]
Do you have twigs or etcetera?

**Comment by AlexModGuy** [comment]
sounds like #328

**Comment by AlexModGuy** [comment]
@PatrickShann0n your image didnt upload; try posting it on imgur and link it here

**Comment by PatrickShann0n** [comment]
@AlexModGuy 
I checked that issue there's nothing in there that actually helps me solve it and that's what I'm trying to fix here is there anything I can do to solve it or does the mod just have to be updated?
