### ISSUE TITLE
Crash generating chunk / new world

### ISSUE THREAD

**Issue by A00826925** [AlexModGuy/AlexsCaves#71]
latest hotfix (1.0.2): [14:15:30] [Server thread/ERROR] [minecraft/BlockableEventLoop]: Error executing task on Chunk source main thread executor for minecraft:overworld
net.minecraft.ReportedException: Exception generating new chunk

Log: https://mclo.gs/kDpoWJR

**Comment by AlexModGuy** [comment]
dupe #68
