### ISSUE TITLE
Cave maps dont work with worldgen.

### ISSUE THREAD

**Issue by GreenForzeGaming** [AlexModGuy/AlexsCaves#714]
So me and a friend are playing on a serber together. I updated recently from alex caves 1.8 too 1.9 for 1.20.1. Now issues accured. We made a map too the poopoomole place and walked 6000 blocks away from spawn. This lead uss to a area with no such cave (used spectator too confirm this) could it be that i have too remove the configs again like with the 1.8 update?

**Comment by AlexModGuy** [comment]
dupe #507
