### ISSUE TITLE
Cave map doesn't work

### ISSUE THREAD

**Issue by normieplatypus** [AlexModGuy/AlexsCaves#716]
My primordial cave map didn't lead me to a primordial cave, I use a lot of mods so perhaps one of them is causing the issue.

![image_2023-12-18_173711934](https://github.com/AlexModGuy/AlexsCaves/assets/144736287/45ccbb52-a4b8-4b6f-bf5e-50323d7465d4)
![image_2023-12-18_173739511](https://github.com/AlexModGuy/AlexsCaves/assets/144736287/4273c781-8d3c-4bd2-9c05-6a0dfba215ad)

**Comment by AlexModGuy** [comment]
dupe #507
