### ISSUE TITLE
L_Ender's Cataclysm Incompatability

### ISSUE THREAD

**Issue by LeafMan201** [AlexModGuy/AlexsCaves#718]
Somehow, whenever Alex's Caves and L_Ender's Cataclysm are in the same modpack, my game crashes before I can fully start it up.

Can you please look into this and see if it's an issue with Cataclysm or something else?

**Comment by AlexModGuy** [comment]
no crash log?

**Comment by LeafMan201** [comment]
> no crash log?

My apologies. Here’s one of the Crash Logs I got from where Alex’s Caves and L_Ender’s Cataclysm were in the same modpack after Cataclysm got that new boss and update.

[crash-2023-12-18_18.18.01-client.txt](https://github.com/AlexModGuy/AlexsCaves/files/13727350/crash-2023-12-18_18.18.01-client.txt)

**Comment by B-Wither** [comment]
Do you have Archaeology API? Due to CurseForge issue, required mod only for 1.19 is also installed in 1.20 if you use CurseForge launcher.

**Comment by LeafMan201** [comment]
> Do you have Archaeology API? Due to CurseForge issue, required mod only for 1.19 is also installed in 1.20 if you use CurseForge launcher.

Not quite sure yet. Lemme check.

**Comment by LeafMan201** [comment]
> > Do you have Archaeology API? Due to CurseForge issue, required mod only for 1.19 is also installed in 1.20 if you use CurseForge launcher.
> 
> Not quite sure yet. Lemme check.

Ohp. Yes I do.

**Comment by LeafMan201** [comment]
> > no crash log?
> 
> My apologies. Here’s one of the Crash Logs I got from where Alex’s Caves and L_Ender’s Cataclysm were in the same modpack after Cataclysm got that new boss and update.
> 
> [crash-2023-12-18_18.18.01-client.txt](https://github.com/AlexModGuy/AlexsCaves/files/13727350/crash-2023-12-18_18.18.01-client.txt)

Also here are two more for if you're curious.
[
[crash-2023-12-21_19.31.42-client.txt](https://github.com/AlexModGuy/AlexsCaves/files/13748072/crash-2023-12-21_19.31.42-client.txt)
[crash-2023-12-21_19.27.48-client.txt](https://github.com/AlexModGuy/AlexsCaves/files/13748073/crash-2023-12-21_19.27.48-client.txt)
](url)

**Comment by B-Wither** [comment]
> > > Do you have Archaeology API? Due to CurseForge issue, required mod only for 1.19 is also installed in 1.20 if you use CurseForge launcher.
> > 
> > 
> > Not quite sure yet. Lemme check.
> 
> Ohp. Yes I do. What should I do with it?

Just remove that. 1.20 version does not need this API.

**Comment by LeafMan201** [comment]
> > > > Do you have Archaeology API? Due to CurseForge issue, required mod only for 1.19 is also installed in 1.20 if you use CurseForge launcher.
> > > 
> > > 
> > > Not quite sure yet. Lemme check.
> > 
> > 
> > Ohp. Yes I do. What should I do with it?
> 
> Just remove that. 1.20 version does not need this API.

Understood. Thank you for letting me know.

**Comment by AlexModGuy** [comment]
anyways this seems like an issue with 'sniffer plus' than AC/Cataclysm:
> at net.minecraft.client.color.block.BlockColors.handler$zid000$snifferplus_registerBlockColorProviders
