### ISSUE TITLE
Cave maps still don't lead to caves properly

### ISSUE THREAD

**Issue by GauntAndreX8** [AlexModGuy/AlexsCaves#719]
Even with the latest version im using it still sometimes lead me to locations where there isn't a cave biome there, and when i open a map in different area, it sometimes print out a map that doesn't show the cave biome location at all
Happened when i was using the forlorn hollows map and sometimes abyssal cavern as well not sure for other biome maps tho

**Comment by AlexModGuy** [comment]
dupe #507

**Comment by GauntAndreX8** [comment]
will this be fixed tho?
