### ISSUE TITLE
Invisible Siren around 0x 0y 0z

### ISSUE THREAD

**Issue by HoneyHiveUnderscore** [AlexModGuy/AlexsCaves#72]
Invisible, intangible siren going off at 0 0 0.  Unsure entirely what caused it, however I did blow up a nucleeper in proximity to a siren (automatically setting it off) so that may have something to do with it. Video linked below.

https://github.com/AlexModGuy/AlexsCaves/assets/148495018/a1361e74-4459-4620-9dbf-857ee15a72a8

**Comment by AlexModGuy** [comment]
what version is this on?
