### ISSUE TITLE
"Miss in Placed Armor Texture"

### ISSUE THREAD

**Issue by JJGoji73** [AlexModGuy/AlexsCaves#722]
I wear a armor and this happened how can i fix this?
![2023-12-20_17 23 24](https://github.com/AlexModGuy/AlexsCaves/assets/154297586/ab93414a-7dda-4f8e-8478-73fd1de38e8a)

![2023-12-20_17 23 48](https://github.com/AlexModGuy/AlexsCaves/assets/154297586/a799387e-a8f1-4ad8-8043-55bdd784570b)
![2023-12-20_17 24 16](https://github.com/AlexModGuy/AlexsCaves/assets/154297586/d2299f25-efc7-4a32-9c63-800cf3291d50)

**Comment by AlexModGuy** [comment]
uninstall optifine. it does this with every modded armor set with a custom model
