### ISSUE TITLE
Server Watchdog took 60 seconds for a single tick when approaching an Abyssal Chasm on a server

### ISSUE THREAD

**Issue by ComeMyChild** [AlexModGuy/AlexsCaves#725]
As the title suggests, we've been having this recurring issue on our server with 100+ mods. At first it could be hard to judge what's crashing it as the crash report linked below doesn't state anything specific apart from placing a feature, but the issue only ever happens when close to an Abyssal Chasm. Two separate instances of two different Abyssal Chasms yields the same result. Here is the crash report:
[crash-2023-12-22_22.47.01-server.txt](https://github.com/AlexModGuy/AlexsCaves/files/13760329/crash-2023-12-22_22.47.01-server.txt)

If it helps, other generation mods we have installed are Twigs, BOP, Regions Unexplored, Underground Jungle and Ender's Cataclysm.

**Comment by JustAnotherBugReporter** [comment]
Twigs is incompatible with AC, along side etcetera.

**Comment by AlexModGuy** [comment]
dupe #84
