### ISSUE TITLE
Missing textcher

### ISSUE THREAD

**Issue by Acat1234** [AlexModGuy/AlexsCaves#726]
If I use the magnet glove and a tool breaks it shows missing textcher A idea I have to fix it is add iron and netherright tags to the correct items and that tels what break partacols to use

**Comment by JustAnotherBugReporter** [comment]
We do not have those kinds of tags to my knowledge, only "#forge:tools/shovel" and the like.

**Comment by AlexModGuy** [comment]
cant replicate in 1.1.2
