### ISSUE TITLE
To many Mobs in Primordial Cave

### ISSUE THREAD

**Issue by JimmyNeutron69000** [AlexModGuy/AlexsCaves#727]
Got a issue with Primordial Cave spawning to many mobs when I change the chunkGenSpawnModifier in Citadel.
At 3 times the caves lag the game so much that everything stops generating before the caves become visible and at 2 times the mobs are lagging themself. I found 3 times quite nice for the rest of the world however as it seems much more alive.

**Comment by JustAnotherBugReporter** [comment]
thats.. what happens when you do that

**Comment by JimmyNeutron69000** [comment]
How about you try recreating the issue and tell me again if that is supposed to happen

**Comment by JustAnotherBugReporter** [comment]
chunkGenSpawnModifier makes chunk gen animals spawn more or less depending on how high or low you put it, which alex's caves relies upon. 

Primordial caves acts like the overworld surface, where chunk generation also spawns animals, thus setting "chunkGenSpawnModifier" to a different number multiplies animals by that rate.

**Comment by JimmyNeutron69000** [comment]
No shit and how many mobs spawn in a single chunk within the Primordial Caves on average? Compared to the overworld that is

**Comment by JustAnotherBugReporter** [comment]
Entity spawn in a single chunk
2-5 Grottoceratops
2 Subterranodons
1-6 Vallumraptors
1 Tremorsaurus
1 Relicheirus

Combine this with the high tps usage for every animal, and condensed space causes the low tps when loading into chunks.

**Comment by JimmyNeutron69000** [comment]
Modifier is 2 and they are incapable of moving since its lagging to much but sure keep trying to tell me this is ok when the rest of the world is basically empty.

![2023-12-28_23 29 16](https://github.com/AlexModGuy/AlexsCaves/assets/154764005/ad578ac9-691d-45ad-bb21-b3b5379e7a6e)
![2023-12-28_23 29 31](https://github.com/AlexModGuy/AlexsCaves/assets/154764005/f6b9af1d-208b-4428-ab48-6ea0030aa09e)
![2023-12-28_23 29 43](https://github.com/AlexModGuy/AlexsCaves/assets/154764005/0ec88cb3-f33a-4df0-9e31-256f7247358d)

**Comment by JustAnotherBugReporter** [comment]
Just reduce it man.

**Comment by JimmyNeutron69000** [comment]
I currently trying to figure out how to post pictures

**Comment by JimmyNeutron69000** [comment]
However I did try normal settings and it still lags as there are simply to many mobs spawning and besides the overworld is basically empty and that is the exact reason this setting exists so you can boost the amount

**Comment by BugmanBugman** [comment]
I got this issue too,but with respawning animals mod instead of messing with citadel
