### ISSUE TITLE
The Holocoder scans LITERALLY every entity

### ISSUE THREAD

**Issue by CacoCacoCaco** [AlexModGuy/AlexsCaves#728]
The Holocoder is meant to scan entities (like players and mobs), but it too scans literally everything the game considers an "entity", i will check about things like Boats and similars, but it scans Item Frames.

Meaning that you can't place Holocoders on Item Frames, and when it scans into an Item Frame and you place it into a Hologram Projector, it shows nothing at all.

**Comment by kaboom24** [comment]
scans boats
