### ISSUE TITLE
Alex's mobs in Alex's caves

### ISSUE THREAD

**Issue by uhloin** [AlexModGuy/AlexsCaves#734]
Giant centipede and Murmur are too dangerous and too frequent. There are enough other dangerous mobs native for primordial caves, those 2 just corrupt atmosphere. Also mobs from other mods should be banned, for example, mobs from Divine RPG make a mess.

**Comment by DENOBODY2** [comment]
remove TACT mod

**Comment by uhloin** [comment]
Thank you, this helped. Probably, that mod should be named not "tiny tweaks" but "tiny bugs" :) I installed it in attempt to fix issue when alex's caves do not generated at place on the map, but tact did not help with that issue too.

**Comment by PlummetStudios** [comment]
Mod compatibility issues
