### ISSUE TITLE
(1.0.9) Irradiated visual lagging server

### ISSUE THREAD

**Issue by CherryBella** [AlexModGuy/AlexsCaves#736]
This is an issue me and some others in my server have run into where the green irradiated visual given off by radiated entities and the raycat begins to heavily hamper the performance of Minecraft. We found out there's a config to remove the effect but it also makes raycats look really weird so I was wondering if there's a way to look into the green visual itself and try to make it so it's less heavy on the FPS.

**Comment by PeglinX** [comment]
this is adupe and already documented
