### ISSUE TITLE
[Config Option] radiation not effect specific mobs (Specifically the Ray Gun Radiation)

### ISSUE THREAD

**Issue by ZzamZ** [AlexModGuy/AlexsCaves#737]
Any shot there would be a way to add a config to make it so specific mobs or entities (Specifically some bosses) immune to the radiation effect? It's pretty easy to cheese bosses with the ray gun that are supposed to have a healing mechanic. Either way still my favorite mob ever! Keep up the amazing work

**Comment by PlummetStudios** [comment]
Already a thing.
![image](https://github.com/AlexModGuy/AlexsCaves/assets/71555408/4882cda8-dfd8-428e-8d8d-d01c1a12c2c7)
