### ISSUE TITLE
Abyssal Chasm under Frozen oceans leave huge pillars up to icebergs.

### ISSUE THREAD

**Issue by Keneoo** [AlexModGuy/AlexsCaves#74]
From every block of packed ice there goes a pillar all the way to the bottom of the chasm.
![image](https://github.com/AlexModGuy/AlexsCaves/assets/148497331/6908acda-c175-48ac-bd93-ccb4cd3a2816)

**Comment by ThatB0i** [comment]
ive was going to post this bug but seems like its already on github so now we just wait
