### ISSUE TITLE
Desolate dagger crashes the game

### ISSUE THREAD

**Issue by Ban-b** [AlexModGuy/AlexsCaves#741]
I tried to play with alex caves in my modpack, but when I use dagger, his projectile tries to hit mob and kicks you out of server(even in singleplayer), if you try to recconect it`s crashes the game.

crash-report:
[crash-2024-01-07_04.58.28-client.txt](https://github.com/AlexModGuy/AlexsCaves/files/13854796/crash-2024-01-07_04.58.28-client.txt)

**Comment by AlexModGuy** [comment]
bug is with lambdynlights DynamicLightSource not my mod
