### ISSUE TITLE
thornwood and pwen not picked up as a tree type

### ISSUE THREAD

**Issue by GoatlyHorisions** [AlexModGuy/AlexsCaves#750]
so, for some reason alot of tree related mods are not picking up pwen and thorn generation as a tree type, but its accepting ancient tree generation as a type of tree, so thorn and pwen needs some fixing

easiest form of testing this would be any treechop mod, sorry if its a lame source for testing but its the most common/ easiest way to test this

**Comment by AlexModGuy** [comment]
not a problem with AC: there is no registry for "tree types"
