### ISSUE TITLE
Coming into physcial contact with unrefined waste with any shader on causes a huge visual issue

### ISSUE THREAD

**Issue by Lordnerdious** [AlexModGuy/AlexsCaves#751]
Using seemingly any shader (I tested it with my three usual ones) when coming into contact with unrefined waste, it takes my entire screen and squeezes it down in the bottom left corner. I'm using forge with optifine. I hope this can be fixed!

Pics for reference
![Without Shaders](https://github.com/AlexModGuy/AlexsCaves/assets/49697740/45ba97e9-2718-4007-b79d-43c4d99634eb)

![With Shaders](https://github.com/AlexModGuy/AlexsCaves/assets/49697740/a6ce4e8b-d4ff-4710-be5a-32ad9e77b976)

**Comment by Mihaly1225** [comment]
same
![Captura de pantalla 2024-01-15 1330001](https://github.com/AlexModGuy/AlexsCaves/assets/156711318/66243adb-2856-46f7-b15c-9430d6ee7d94)

**Comment by Lordnerdious** [comment]
I figured it out a work around. Disable radiation making players and mobs glow in the configs. Though I hope an actual fix can be implemented, this worked for me.

**Comment by PlummetStudios** [comment]
Shaders are not supported.
