### ISSUE TITLE
Crash when deep ones attacks 

### ISSUE THREAD

**Issue by SireAwfulThe1st** [AlexModGuy/AlexsCaves#758]
Seems like there's a weird crash whenever the deep ones started attacking anything, not sure why but hope this crash log helps.
[crash-2024-01-18_15.32.07-server.txt](https://github.com/AlexModGuy/AlexsCaves/files/13974050/crash-2024-01-18_15.32.07-server.txt)

**Comment by zinerith** [comment]
I mean it's possible that there's a conflict with those mods you have that make changes to how mob ai functions?

**Comment by AlexModGuy** [comment]
bug was fixed in 1.0.9
