### ISSUE TITLE
[Suggestion] Compatibility with mod "Not Enough Animations" by tr7zw

### ISSUE THREAD

**Issue by Vinzound** [AlexModGuy/AlexsCaves#759]
https://github.com/tr7zw/NotEnoughAnimations/issues/169

It would be great if the maps provided by Alex's Caves were compatible with the Not Enough Animations mod, which would allow the maps to be viewed on the player's model as it is with vanilla maps. Sadly, it only shows the Alex's Caves map sprite, which prevents you from being able to use the two mods together when searching for a cave.

Without Not Enough Animation mod:
![image](https://github.com/AlexModGuy/AlexsCaves/assets/144878239/8c81b1a8-e781-46b0-b8d5-62ac76578dcf)

With Not Enough Animation and First-person Model mods:
![image](https://github.com/AlexModGuy/AlexsCaves/assets/144878239/40a61871-d6cc-45ee-b52e-37067f2986c7)

**Comment by BugmanBugman** [comment]
Please add this!

**Comment by AlexModGuy** [comment]
dupe #746
