### ISSUE TITLE
game crashes randomly 

### ISSUE THREAD

**Issue by KnotZero** [AlexModGuy/AlexsCaves#76]
[crash-2023-10-19_23.04.17-client.txt](https://github.com/AlexModGuy/AlexsCaves/files/13047613/crash-2023-10-19_23.04.17-client.txt)
![image](https://github.com/AlexModGuy/AlexsCaves/assets/144356897/1fcdc01e-0b47-4141-b851-cd4908f79d9b)
mods I have, game crashes randomly

**Comment by AlexModGuy** [comment]
#78
