### ISSUE TITLE
immense lag when inside toxic caves.

### ISSUE THREAD

**Issue by ashissilly** [AlexModGuy/AlexsCaves#760]
So I have been playing a lot on my modded survival world recently that includes Alex's Caves, and everything works perfectly normally. But when i entered the toxic caves my frames went from around 65-80 to a peak of 40. Leaving the cave stops all issues, although I brought a Raycat home with me and whenever I looked towards it my frames plummeted once more so it may just be them.
EDIT: did some testing and found out it is specifically the Raycat causing the lag. no clue why.
EDIT 2: so I think the issue is just the radiation glow effect in general. cause me and my friend were playing together and when he got irradiated it lagged just as much as when the Raycat is on screen.

**Comment by txb5334** [comment]
there's an option in the client config to disable the irradiated effect

**Comment by Wave6677** [comment]
Related to Issue #157

**Comment by Joinerarm** [comment]
can someone please tell me were exaclty in the client is the option to turn that off, I cant find any configuration to turn it off
