### ISSUE TITLE
Alex - you are a pathetic individual farmer and the devil!

### ISSUE THREAD

**Issue by kitovoi111** [AlexModGuy/AlexsCaves#762]
Alex - you are a pathetic individual farmer and the devil! You didn’t make Alex’s Caves for 1.19.2 Forge and you forbid other people to help port the mod, what a low and pathetic person you are.

**Comment by AzeznLadyofFloof** [comment]
Uh.. bruh are you stupid. Mods take a lot of work to maintain for all versions, just update ya big baby

**Comment by kitovoi111** [comment]
> Uh.. bruh are you stupid. Mods take a lot of work to maintain for all versions, just update ya big baby

One wonderful person has already done this, but Alex gave a shit and forbade him to do it, because of this we lost the port on 1.19.2

**Comment by AzeznLadyofFloof** [comment]
> > Uh.. bruh are you stupid. Mods take a lot of work to maintain for all versions, just update ya big baby
> 
> One wonderful person has already done this, but Alex gave a shit and forbade him to do it, because of this we lost the port on 1.19.2

Quick question, whose mod is it? It’s not his job to pander to the “update to x version! Or backdate to x version” Kids. I honestly think he’s fine to do what he wants, was only commenting because it’s funny that you wasted your time to write this
