### ISSUE TITLE
The alex's caves armors have visual bugs.

### ISSUE THREAD

**Issue by HexagonOFF** [AlexModGuy/AlexsCaves#770]
The textures are glitched whenever worn, or put on a armor stand, I don't know how to explain it so just look at this.

![Java-runtime-gamma Screenshot 2024 01 23 - 03 46 07 25](https://github.com/AlexModGuy/AlexsCaves/assets/157441484/d07e2b31-bf39-4366-a764-4c1f57020061)
![Java-runtime-gamma Screenshot 2024 01 23 - 03 46 18 42](https://github.com/AlexModGuy/AlexsCaves/assets/157441484/9f2e5bb6-73eb-4dea-8b95-7d9335338ac9)
![Java-runtime-gamma Screenshot 2024 01 23 - 03 46 31 47](https://github.com/AlexModGuy/AlexsCaves/assets/157441484/8dcde9dd-c6fd-4499-b4db-826f6677da20)

**Comment by KreloX** [comment]
this is an Optifine issue

**Comment by AlexModGuy** [comment]
uninstall optifine
