### ISSUE TITLE
Cannot Breed tremorsaurus

### ISSUE THREAD

**Issue by LaventaBreeze** [AlexModGuy/AlexsCaves#772]
Tamed two of them and neither will take a dino nugget. while standing I just mount it. While crouching it just changes its' status.

**Comment by Otja** [comment]
The Tremorsaurus is bred with Dino Chops, not Dino Nuggets.

**Comment by LaventaBreeze** [comment]
Thank you! The wiki lists it as dino nuggets and not chops, so I had no
idea. Ill be sure to request that be edited so nobody else gets confused.
