### ISSUE TITLE
Nuclear explosions causing chunks to bug and causing server lag

### ISSUE THREAD

**Issue by Joshua-1462** [AlexModGuy/AlexsCaves#778]
![Screenshot 2024-02-01 173100](https://github.com/AlexModGuy/AlexsCaves/assets/158116717/1c45d9df-1999-4ced-8ad6-e4c5bf2b6645)
I did some thorough testing and it seems that every time I set off a nuke I have to go to a previous backup on the server because performance will drop the ms goes from 12ms all the way to 89ms Which makes everything really laggy it takes forever to eat food and people get teleported back/rubber banding. as you can see in the photo even after there is no players in the area the chunk will still be loaded and this causes performance to drop. please come out with a fix as soon as you can this is a serious issue and can cause corruption of chunks and World files. I've had to reload many backups because of this. The server is on version forge-1.20.1-47.2.19 And I am using version alexscaves-1.0.9 of the mod

**Comment by AlexModGuy** [comment]
dupe #630
