### ISSUE TITLE
Structure compass cheese

### ISSUE THREAD

**Issue by pantsguyapp** [AlexModGuy/AlexsCaves#782]
The compass can find the structures tied to the biome and therefore the biomes.

**Comment by AlexModGuy** [comment]
link the mod used

**Comment by pantsguyapp** [comment]
https://www.curseforge.com/minecraft/mc-mods/structure-compass/files/all?page=1&pageSize=20&gameVersionTypeId=1

**Comment by Driestcombee** [comment]
Suggestion, don't use structure compass if you want to have a non cheese experience.

**Comment by AlexModGuy** [comment]
works as intended, compass breaks in survival mode with cheats disabled.
