### ISSUE TITLE
Abyssal Chasm Doesn't Want to Appear

### ISSUE THREAD

**Issue by cartooneric84** [AlexModGuy/AlexsCaves#786]
In this case what I mean by that is that I would use a map to locate an Abyssal Chasm biome, it actually locates the biome, I spend some time traveling to that biome, but when I supposedly arrive the biome is nowhere to be found.  I have two screenshots attached to present what I mean.

![2024-02-09_19 11 25](https://github.com/AlexModGuy/AlexsCaves/assets/86167550/52556d70-8ff9-44f1-8466-683562219bdf)
![2024-01-18_18 26 12](https://github.com/AlexModGuy/AlexsCaves/assets/86167550/54e49c44-a393-4b7b-8d45-2a6633fa7eab)

So I think something is wrong here.  Or maybe it's clashing with another possible mod.  I do not know.

**Comment by AlexModGuy** [comment]
is tectonic installed>? modlist?

**Comment by cartooneric84** [comment]
At the time of those screenshots, Tectonic was installed.

**Comment by AlexModGuy** [comment]
dupe #108
