### ISSUE TITLE
Entity Tick Triggers Watchdog Crash

### ISSUE THREAD

**Issue by MynxOne** [AlexModGuy/AlexsCaves#795]
Hello there!

**Issue:** A ticked entity is seemingly causing a server crash on player teleport to a normal area. It is random and causes the server watchdog to trigger a crash.
**Game Version:** 1.20.1
**Additional Note:** The link via issue tracker within the crash report below doesn't link to anywhere as well.
**Crash Log:**
[crash-2024-02-14_17.35.48-server.txt](https://github.com/AlexModGuy/AlexsCaves/files/14312513/crash-2024-02-14_17.35.48-server.txt)

**Comment by AlexModGuy** [comment]
dupe #682
