### ISSUE TITLE
Falling through the floor with the Magnets

### ISSUE THREAD

**Issue by PiousVolcano** [AlexModGuy/AlexsCaves#797]
https://github.com/AlexModGuy/AlexsCaves/assets/160350694/a0fc9389-ab37-496a-9a8c-6a56872a9088

**Comment by PiousVolcano** [comment]
And you also fall through the Magnetic blocks when you are going down with them.

**Comment by TheDeathSurgeon** [comment]
Just asking
How are you playing with shaders cuz i cant play with optifine cuz my armors don render correctly

**Comment by DigitalWendigo** [comment]
Happens on my end as well. 
Once you get stuck to the red nyodinium(sorry for the butchering of the word!), the screen just absolutely freaks out, and you start taking damage.

**Comment by PiousVolcano** [comment]
@TheDeathSurgeon I use oculus for shader support but only version 1.16.3 works for me

**Comment by AlexModGuy** [comment]
dupe #745
