### ISSUE TITLE
tool display error when using gloves and something else video expires 2 day

### ISSUE THREAD

**Issue by diznard** [AlexModGuy/AlexsCaves#798]
zdrastvuyte ya igrayu s vashim modom Alex caves na versiyu maynkrafta 1.20.1 u menya tak zhe ustanovle mod epic fight i kogda ispol'zuyesh' perchatku iz vashego moda vizual'nyy yeffekt bagayet'sya i instrument nevydemyy mozhno kak to eto ispravit' ili nikak? prosto epic fight ochen' krasivyy mod na oruzhiye i srazheniya i ya uzhe ochen' privyk k nemu i khotelos' by igrat' vmeste s etimi dvumya modami
Hello, I'm playing with your mod Alex caves for minecraft version 1.20.1, I also have the epic fight mod installed and when you use the glove from your mod the visual effect is buggy and the tool is invisible, can I somehow fix this or not? just epic fight is a very beautiful mod for weapons and battles and I’m already very used to it and would like to play together with these two mods

https://streamable.com/eux57o

I also wanted to ask if alex caves will work with other mods, such as ice and fire, because even though the mod has iron armor for the dragon, it does not react to magnets, the same applies to other mods such as simly swords, it adds new swords, spears, and so on but they also don’t react and it doesn’t look very good, and the vanilla iron horse armor doesn’t react to a magnet either

https://streamable.com/eqi6pt

https://streamable.com/d413w3

streamable say video expires 2 day

thank you for reading and paying attention, maybe this is intended, I don’t know, sorry if I wasted your time

**Comment by AlexModGuy** [comment]
dupe #784

**Comment by diznard** [comment]
yeah that a same error
