### ISSUE TITLE
Alex's Caves Incompatibilities So Far...

### ISSUE THREAD

**Issue by Ryu776** [AlexModGuy/AlexsCaves#8]
So far, I found that Valkyrien Skies + Eureka, and Radium are incompatible with Alex's Caves.

**Comment by cyco20** [comment]
I can't say for Valkyrien Skies or Eureka, but radium causes the game to crash on launch with exit code 1 without a log.

**Comment by AlexModGuy** [comment]
cant fix anything without a log

**Comment by valchiara** [comment]
There seems to be an issue with Twigs, causing the world to become unresponsive whenever I approach a Primordial or Abyssal Cave. When trying to exit the world, Minecraft gets stuck on the "Saving world" screen, and I have to forcefully shut down the Java process. Nothing is logged in the Logs.

Does not occur with: Toxic Caves
Not tested: Magnetic Caves, Forlorn Hollows

**Comment by Bondzberg** [comment]
[latest.log](https://github.com/AlexModGuy/AlexsCaves/files/13046148/latest.log)
For radium/Alex caves incompatibility. No other mods other than Radium, AC, and Citadel. Seems like a mixin issue.

**Comment by AlexModGuy** [comment]
fixed
