### ISSUE TITLE
Ice & Fire "Incompatability"

### ISSUE THREAD

**Issue by Eletoast** [AlexModGuy/AlexsCaves#802]
Since Alex's Caves 1.1.0 requires Citadel 2.5.3, this makes it impossible to play with Ice & Fire, since it still requires 2.4.9.
![image](https://github.com/AlexModGuy/AlexsCaves/assets/143987495/b079ff75-1947-43d6-b8dc-f2733c3c475d)

**Comment by BugmanBugman** [comment]
ohio

**Comment by Eletoast** [comment]
Seems to have been fixed. Closing.
