### ISSUE TITLE
Crashes/Conflicts with some structure mods

### ISSUE THREAD

**Issue by Eletoast** [AlexModGuy/AlexsCaves#805]
After updating Citadel and Alex's Caves, I've started noticing some stuttering before my game eventually crashes due to a "memory heap" error. States in the crash report that the suspected mods are ModernFix and Yung's Mods/API, but this issue hasn't happened within the past month I've been tinkering with my modpack.
[crash-2024-02-19_21.39.40-server.txt](https://github.com/AlexModGuy/AlexsCaves/files/14339085/crash-2024-02-19_21.39.40-server.txt)

**Comment by Eletoast** [comment]
Just realized I should've put this issue on the Citadel page, but will leave here as it still could be related to Alex's Caves.

**Comment by AlexModGuy** [comment]
seems to be a yung issue from this log
