### ISSUE TITLE
Subterranaodon failing to render

### ISSUE THREAD

**Issue by GoldenMaster8** [AlexModGuy/AlexsCaves#806]
[crash-2024-02-19_23.06.35-client.txt](https://github.com/AlexModGuy/AlexsCaves/files/14339278/crash-2024-02-19_23.06.35-client.txt)

This is on the newest version of the mod,
using Neoforge version 4.1.99

**Comment by AlexModGuy** [comment]
most certainly a mod conflict. one of those mods you installed is cancelling mob renders mid way causing pose stacks to be empty

**Comment by GoldenMaster8** [comment]
Could it possibly be entity culling?
Thats my theory anyways

**Comment by GoldenMaster8** [comment]
> Could it possibly be entity culling? Thats my theory anyways

its not entity culling
