### ISSUE TITLE
Luxtructosaurus and Atlatitan's JEI renders are broken

### ISSUE THREAD

**Issue by Inonedn** [AlexModGuy/AlexsCaves#812]
![image](https://github.com/AlexModGuy/AlexsCaves/assets/36087299/d2e6e549-27d1-4653-b292-adc9a67edd99)
![image](https://github.com/AlexModGuy/AlexsCaves/assets/36087299/ab096f91-a524-4406-9aa3-8933434ff595)

**Comment by GizmoTheMoonPig** [comment]
this is fixed with https://github.com/AlexModGuy/AlexsCaves/pull/807, which will most likely be in the next update
