### ISSUE TITLE
Game stops loading/freezes when entering cave biome with regions unexplored 

### ISSUE THREAD

**Issue by Ramentop** [AlexModGuy/AlexsCaves#824]
Upon traveling thousands of blocks and approaching the cave biome my game stops rendering new chunks, mobs freeze in place, I can’t eat or get hurt, and trying to exit the game puts in into an eternal state of “saving”. I am on Steam Deck utilizing the Prism Launcher. I do have about 50 mods in a kitchen sink modpack but have run into this error in both of my test survival worlds and cannot figure out how to resolve the issue. Trimming the chunks do not work, it seems the regions unexplored mod and Alexs caves are incompatible? Which is disappointing because I see these two mods as the foundation of my little pack. I am willing to provide and more information to try and resolve this bug. Hopefully it is solvable on your end. Otherwise I’ll just have to add to my list of bugs region unexplored experiences…

**Comment by Ramentop** [comment]
yes? twigs

**Comment by Ramentop** [comment]
Disregard error, it was a crash caused by a confliction of endbeddium and
rubidium files clashing with each other that was somehow caused by the
Alexs caves. Problem was solved by deleting proper files. Thanks for
attempting to help.

**Comment by AlexModGuy** [comment]
Yes. twigs right now breaks alexs caves generation.

**Comment by Ramentop** [comment]
Is there any known fix at the moment? Anyway I can disable the twig world
generating features to fix it or do I have to remove the mod outright?
