### ISSUE TITLE
LUXTRUCTOSAIRS DOESN'T SPAWN

### ISSUE THREAD

**Issue by DarkPuppet74** [AlexModGuy/AlexsCaves#829]
i ve tried in both creative and survival, even created a new world,  i ve trown a lot of that bone thing in the volcano , on the side too, but nothing happens..... :(

**Comment by JustAnotherBugReporter** [comment]
i also recommend putting all or most relevant mods in your description

**Comment by AlexModGuy** [comment]
try turning off peaceful mode
