### ISSUE TITLE
tremorzilla make the server crash

### ISSUE THREAD

**Issue by CardinalTuba907** [AlexModGuy/AlexsCaves#833]
each time i try to use the tremorzilla atomic beam my server crash
![image_2024-02-22_215033063](https://github.com/AlexModGuy/AlexsCaves/assets/147560078/1fa80c8e-eb2e-412a-8260-b0b2ccf8754e)

**Comment by AlexModGuy** [comment]
can we get a full crashlog?

**Comment by CountBlumiere** [comment]
this is also another issue i have with tremorzilla atomic beam as it disconnects you from multiplayer worlds when used i can try to post a latest.log to see if that provides any information for you

**Comment by Ethan4life84** [comment]
Was there a fix to this issue?
