### ISSUE TITLE
[Universal Enchants Mod Incompatible] No enchantment book

### ISSUE THREAD

**Issue by Keith2247** [AlexModGuy/AlexsCaves#836]
Hi guys!, I love all your mods, but recently in the newest mod, Alex caves 1.1.1, in the eruption update, I was looking for the new enchantment books for the weapons, but when I was looking for them, they weren’t there, I created a new world with commands and, the books just didn’t appear, I don’t know if it’s a bug or something, could you check it please?, thank you guys!!

**Comment by AlexModGuy** [comment]
![2024-02-23_12 43 30](https://github.com/AlexModGuy/AlexsCaves/assets/8662109/a3537e74-69da-4420-9677-dbcc335798e9)
do they not appear like this?

**Comment by Keith2247** [comment]
> ![2024-02-23_12 43 30](https://github.com/AlexModGuy/AlexsCaves/assets/8662109/a3537e74-69da-4420-9677-dbcc335798e9)
> 
> do they not appear like this?

No, they just don't appear, the enchantment books aren't on my inventory, even if I try to look for them word by word the don't appear

**Comment by Keith2247** [comment]
> ![2024-02-23_12 43 30](https://github.com/AlexModGuy/AlexsCaves/assets/8662109/a3537e74-69da-4420-9677-dbcc335798e9)
> 
> do they not appear like this?

Do u think it's a bug or something?, I can send screenshots

**Comment by AlexModGuy** [comment]
yes screenshots would help because im not sure what you mean

**Comment by Keith2247** [comment]
![image](https://github.com/AlexModGuy/AlexsCaves/assets/160978134/49a0ca83-5f15-41b2-9db5-59daca2c375e) that's what appears to me, is it a bug or something?

**Comment by AlexModGuy** [comment]
i'm going to need a modlist

**Comment by Keith2247** [comment]
All the mods I have?

**Comment by AlexModGuy** [comment]
Yes. thats what a modlist means.

**Comment by Keith2247** [comment]
I'll give it to u in a moment

**Comment by Keith2247** [comment]
![image](https://github.com/AlexModGuy/AlexsCaves/assets/160978134/fd9c3828-cd77-4fed-90f1-94cb64b747b7) ![image](https://github.com/AlexModGuy/AlexsCaves/assets/160978134/38ed200e-1a51-44ea-a7e5-c3fca454b9cb) ![image](https://github.com/AlexModGuy/AlexsCaves/assets/160978134/bf8fe76b-a565-47b4-8ec7-00e8951eab6e) ![image](https://github.com/AlexModGuy/AlexsCaves/assets/160978134/5cfc6ecc-f13c-4504-b9f9-7ab6e1a5d662) ![image](https://github.com/AlexModGuy/AlexsCaves/assets/160978134/b955690d-dadf-4e6d-bea3-4be984652b5f)![image](https://github.com/AlexModGuy/AlexsCaves/assets/160978134/f785e78e-11f9-4775-b13c-cdcbf9ed7db6) ![image](https://github.com/AlexModGuy/AlexsCaves/assets/160978134/82334ca2-6762-4b6b-a40e-92ecfc590d36)![image](https://github.com/AlexModGuy/AlexsCaves/assets/160978134/0ccf8886-3808-4bda-87e1-600f1078299e)![image](https://github.com/AlexModGuy/AlexsCaves/assets/160978134/8a4ba28f-b988-4d35-9a42-f9d8033f3bd0) ![image](https://github.com/AlexModGuy/AlexsCaves/assets/160978134/951cd5da-cc16-44c7-8796-a4963d664538) ![image](https://github.com/AlexModGuy/AlexsCaves/assets/160978134/05ee010a-feea-454f-93f6-5ba5328854af) ![image](https://github.com/AlexModGuy/AlexsCaves/assets/160978134/1bb66ee3-a107-49aa-8806-37852b94af62) ![image](https://github.com/AlexModGuy/AlexsCaves/assets/160978134/d5545b5d-8978-4ca2-99b7-5894adcb9970)![image](https://github.com/AlexModGuy/AlexsCaves/assets/160978134/8d2aa796-d86f-4c49-b826-92c666379eeb) ![image](https://github.com/AlexModGuy/AlexsCaves/assets/160978134/ed415e23-3864-4ef4-ad7e-e2a00c60886c)

**Comment by AlexModGuy** [comment]
this is too many for me to sift through myself. You'll need to do the tried-and-tested method of
1. remove half your mods
2. launch the game
3. if the enchantments dont appear, remove half the selection again
4. if they do appear, add half of the previously removed mods

do this until you can narrow down which other mod is messing with the enchantments, then return the name of that mod to me

**Comment by Keith2247** [comment]
I'll try it, I'll tell u if it worked or not

**Comment by Keith2247** [comment]
> This seems to happen when https://www.curseforge.com/minecraft/mc-mods/universal-enchants-forge is installed
> 
> Disabling it (and the library, not sure if that one is relevant) makes the enchantments visible again (in the creative menu and EMI)
> 
> 
> 
> Mods:
> 
> 
> 
> ![image](https://github.com/AlexModGuy/AlexsCaves/assets/22003703/3604d9a7-4d0a-4349-af0d-faccbcfbbbc0)
> 
> 

Thank u, I really appreciate the help and the patience

**Comment by AlexModGuy** [comment]
![image](https://github.com/AlexModGuy/AlexsCaves/assets/8662109/003e2bf1-2b89-4c28-a822-75f3dc49ce05)

Seems like intentional mod behavior from Universal Enchants Mod, as the mod description describes a similar issue with another mod's enchantable items. Either follow these steps, or report this issue to their bugtracker. Honestly this just seems like bad mod design on their part but it's up to you to fix it since the issue seems to be on them.
