### ISSUE TITLE
Dreadbow arrows and dinosaur spirits not rendering with shaders

### ISSUE THREAD

**Issue by IDonutKnowYT** [AlexModGuy/AlexsCaves#838]
Forge 47.1.3
Mods:
embeddium (0.3.4) 
oculus (1.6.15a) 
Alex's Caves (1.1.1)
Citadel (2.5.3)

Dreadbow arrows and dinosaur spirits summoned by the extinction spear do not render when shaders are enabled. I have tested this with multiple shaders.

**Comment by AlexModGuy** [comment]
read the mods description next time
