### ISSUE TITLE
Atlatitan attacks pigs unprovoked, every other (tested) mob is ignored

### ISSUE THREAD

**Issue by JustAnotherBugReporter** [AlexModGuy/AlexsCaves#839]
Title, tested mobs includes other surface mobs (Cows, Chickens, and Sheep)

**Comment by SiverDX** [comment]
https://github.com/AlexModGuy/AlexsCaves/blob/1f5b5127757eb6d37793dd0b90e8d6ddff956c46/src/main/java/com/github/alexmodguy/alexscaves/server/entity/living/AtlatitanEntity.java#L75 seems intentional

**Comment by pantsguyapp** [comment]
Why tho.

**Comment by JustAnotherBugReporter** [comment]
> 
![image](https://github.com/AlexModGuy/AlexsCaves/assets/150121011/19c956ac-51bd-4377-9b2a-6d24c932a25e)
