### ISSUE TITLE
Caves weapons missing weapon tags

### ISSUE THREAD

**Issue by rakkojima** [AlexModGuy/AlexsCaves#840]
Weapons missing tags include-
limestone spear
extinction spear
raygun
ortholance
seastaff
dreadbow
(desolate dagger is fine)
missing tags lead to incompatability with any additional mod that searches for these tags.
request sword tag for lances and spears, bow tag for bow staff and raygun
all armors have correct tags.

**Comment by 989onan** [comment]
Surprisingly enough, this is still an isssue. For some reason, mine and slash specifically has an issue finding the items and the only one that works is the desolate dagger is extending the minecraft sworditem class, which allows the item to be auto tagged with the tag "sword", but the other items that have been tagged using jsons may need to be tagged with "sword" and not "swords"

I have not done mods for minecraft for a year or two, but this seems logical to me (I am just a friend)

**Comment by rakkojima** [comment]
what the other mod is looking for is a "sword" tag
"weapon_type": {
    "can_dual_wield": true,
    "id": "sword",
    
a "bow" tag
 "weapon_type": {
    "can_dual_wield": false,
    "id": "bow",

or a "staff" tag
"weapon_type": {
    "can_dual_wield": false,
    "id": "staff",

this is all visible under mine and slash mod data>mmorpg>mmorpg_base_gear_types
https://github.com/RobertSkalko/Mine-And-Slash-Rework

(this may be generated upon compile)
