### ISSUE TITLE
incompatible with midnightlib

### ISSUE THREAD

**Issue by Justtakethissuffer** [AlexModGuy/AlexsCaves#841]
[crash-2024-02-23_14.46.55-fml.txt](https://github.com/AlexModGuy/AlexsCaves/files/14388800/crash-2024-02-23_14.46.55-fml.txt)

**Comment by AlexModGuy** [comment]
crashlog?

**Comment by AlexModGuy** [comment]
> 	Failure message: Mod iceandfire requires citadel between 2.4.1 and 2.4.99 (inclusive)
		Currently, citadel is 2.5.3
		
Update ice and fire. unrelated crash
