### ISSUE TITLE
Friend's server doesn't start in version 1.1.0 or 1.1.1

### ISSUE THREAD

**Issue by Zeldarraria** [AlexModGuy/AlexsCaves#845]
He clicks the run bat file and it presents a bunch of errors and closes. Works fine on older versions and not as a server. 
![Screenshot 2024-02-23 191120](https://github.com/AlexModGuy/AlexsCaves/assets/144371592/d5a5e1af-53bc-45c4-a360-5549d1138e89)

**Comment by AlexModGuy** [comment]
says right there that citadel is out of date

**Comment by Zeldarraria** [comment]
Ah thank you, guess my friend didn't read through that far (even though he said he did) and I only gave it a skim through when he sent me the screenshot
