### ISSUE TITLE
Shipwrecks spawn floating in the water in Abyssal Chasms

### ISSUE THREAD

**Issue by Jasdernn** [AlexModGuy/AlexsCaves#86]
![2023-10-19_17 43 05](https://github.com/AlexModGuy/AlexsCaves/assets/148498785/29f663ef-6d23-416d-ac75-c7c8843495fc)
![2023-10-19_17 45 20](https://github.com/AlexModGuy/AlexsCaves/assets/148498785/b85c5732-ab0e-47f3-a623-da44f074c234)

**Comment by Mey-Ha-Zah** [comment]
That looks pretty cool, reminds me of sea of thieves shipwrecks.
