### ISSUE TITLE
When doMobGreifing is false, Tremorzilla still destroys blocks with its beam

### ISSUE THREAD

**Issue by Jasdernn** [AlexModGuy/AlexsCaves#860]
How am I supposed to fight it in a cool huge arena if it just destroys the entire thing? Just a little suggestion for ya because I'm trying to make a map or whatever and Tremorzilla was supposed to be the boss of the "world", so I thought I'd just say to avoid the destruction of a cool arena.

**Comment by AlexModGuy** [comment]
fixed in 1.1.2
