### ISSUE TITLE
Error Code 1

### ISSUE THREAD

**Issue by SenForged** [AlexModGuy/AlexsCaves#869]
Having the same issue.
I'll send the notes here and please respond rapidly as I really want to play the mod with my friends.
I only have Alex's Caves and citadel downloaded. I repaired everything reinstalled java, and even Minecraft but i keep getting the same error code.

[hs_err_pid27688.log](https://github.com/AlexModGuy/AlexsCaves/files/14394902/hs_err_pid27688.log)
@AlexModGuy

**Comment by AlexModGuy** [comment]
dupe #229

**Comment by SenForged** [comment]
this doesn't fix the problem
I already checked #229 several times and theirs no solution as it seems that citadel is the problem making it impossible to play alex's caves

**Comment by SenForged** [comment]
I don't know tho im just assuming citadel is causing the problem

**Comment by JustAnotherBugReporter** [comment]
Update your AMD drivers on their website.
