### ISSUE TITLE
1.1.1 update does not included with tremorzilla, luxtructosaurus and atlatitans in cave compendium 

### ISSUE THREAD

**Issue by CurseForgeX11** [AlexModGuy/AlexsCaves#870]
idk is it just me or is it the update itself went buggy, whenever you open the cave compendium it doesn't shown out the luxtructosaurus and tremorzilla and the atlatitans in cave compendium it only just show the previous mobs 
![2024-02-25_12 38 40](https://github.com/AlexModGuy/AlexsCaves/assets/126997973/9093ee76-eb91-4e2d-94d9-2cf3fb88a502)

**Comment by JustAlvin123** [comment]
this isnt a bug, its intentional.

you can grab Toxic Caves and Primordial Caves Codex item in GMC then right clicking all of them until you gained "secret" content. after it done, then Tremorzilla, Lux, and Atlatitan will be shown

**Comment by JustAnotherBugReporter** [comment]
Use another codex.
