### ISSUE TITLE
Issue with forge

### ISSUE THREAD

**Issue by SpiderCola111111** [AlexModGuy/AlexsCaves#876]
i downloaded this mod and it said that i need forge 47.1.3 or above and that i currently i have forge 47.0.45

i downloaded forge 47.1.3 and it still says that i need it, and that i have 47.0.45.
i dont see 47.0.45 in mod folder

**Comment by AlexModGuy** [comment]
you need to run the game with 47.1.3.

**Comment by SpiderCola111111** [comment]
i did, it still says that i need 47.1.3.
