### ISSUE TITLE
I can't walk up slabs or stairs

### ISSUE THREAD

**Issue by LarkyMC** [AlexModGuy/AlexsCaves#88]
When i try to walk on stairs or slabs i have to jump instead of automatically moving me upwards, this also applies for when I'm in pathed grass and trying to walk on a normal block

**Comment by AlexModGuy** [comment]
fixed

**Comment by LarkyMC** [comment]
that fast???

**Comment by LarkyMC** [comment]
wow you guys are doing great work :)
