### ISSUE TITLE
Cave biome inconsistency/incorrect cave maps

### ISSUE THREAD

**Issue by emeraldragon10005** [AlexModGuy/AlexsCaves#882]
I'm using version **1.1.1** on Minecraft version **1.20.1**. I am looking for toxic caves right now and so far two different maps have led me to the incorrect cave biome. This could be a coincidence but the biome i found twice is biomesoplenty:spider_caves which is of course from Biomes o' Plenty. I know the mod is functioning properly and is installed because earlier i found a Primordial Cave completely by accident. I think there is some discrepancy concerning the system used for cave location

**Comment by AlexModGuy** [comment]
should be addressed with 1.1.3
