### ISSUE TITLE
Incompatible with Nostalgic Tweaks

### ISSUE THREAD

**Issue by MochiVN634** [AlexModGuy/AlexsCaves#89]
Disabling Nostalgic Tweaks doesn't crash my game anymore, here's the log:
[crash-2023-10-19_18.55.17-client.txt](https://github.com/AlexModGuy/AlexsCaves/files/13048060/crash-2023-10-19_18.55.17-client.txt)

**Comment by AlexModGuy** [comment]
update alexs caves
