### ISSUE TITLE
Way too many passive mob spawns around worldspawn

### ISSUE THREAD

**Issue by Natetromino** [AlexModGuy/AlexsCaves#891]
After updating Alex Caves to 1.1.1, players on my server began reporting ridiculous amounts of passive mobs spawning around their bases and worldspawn. I'm not sure what sort of data I'd provide from the server to help with the issue, but the only change I had made in our modpack prior to the issue coming about was updating your mod. I also tried the 1.1.2 patch, and the issue has persisted.

**Comment by Natetromino** [comment]
![2024-02-28_21 10 45](https://github.com/AlexModGuy/AlexsCaves/assets/151590918/aa123036-15ba-4232-bb8c-ab7c95396d7d)

**Comment by AlexModGuy** [comment]
Has anyone placed an amber monolith nearby? they spawn animals of whatever biome they are in.

**Comment by Natetromino** [comment]
I'll check with them and see, if it is the case then sorry for bothering you, lmao. If not I'll let you know, thank you :)

**Comment by Natetromino** [comment]
Ok so it does seem related to the monoliths, after removing them, the spawning seemed to calm down. However, the Dinosaur cave also seems to have this issue? It's just a constant blob of dinosaurs at all times. Maybe there is a bug causing the monoliths to have way too high of a spawn rate?
