### ISSUE TITLE
[Suggestion] Alex Caves compat to display rarities with Obscuria Tooltips

### ISSUE THREAD

**Issue by BugmanBugman** [AlexModGuy/AlexsCaves#892]
![image](https://github.com/AlexModGuy/AlexsCaves/assets/40730042/2dfc9369-2689-42d9-af5b-bafa14291fc9)
![image](https://github.com/AlexModGuy/AlexsCaves/assets/40730042/74c865e8-e604-49e5-919e-2f254ac273b0)
Notice how they're missing proper langer files. Obscuria tooltips with special items tend to look like this
![image](https://github.com/AlexModGuy/AlexsCaves/assets/40730042/ef363a09-8789-4da3-a5e4-d7aa56385233)
Here's what the dev suggests:
![image](https://github.com/AlexModGuy/AlexsCaves/assets/40730042/5346c1de-3c5d-4216-954e-41d73d609191)

**Comment by BugmanBugman** [comment]
rarity.alexscaves.nuclear.name
rarity.alexscaves.demonic.name
seems to be waht its asking for. And yeah i tried looking for a github but i think its entirely closed source lol

**Comment by Shibva** [comment]
@PiggyDr . commenting here, the registry is incorrect. Somewhere in the lang path a : got places in where a . should

meaning the correct key for Nuclear at the moment is rarity.alexscaves**:**nuclear.name when it should be rarity.alexscaves.nuclear.name

this is an issue on all three
