### ISSUE TITLE
[Question] MC 1.20.1, Alex's Caves 1.1.2. Hullbreaker spawn rates. 

### ISSUE THREAD

**Issue by DigitalWendigo** [AlexModGuy/AlexsCaves#893]
Sorry if this information is found somewhere and I just haven't been able to find it, but does the Hullbreaker have some special spawning conditions that need to be met, which are not mentioned in the mod's in-game book? 
I have been roaming around the abyssal caverns for several in-game days, and three real time days (spread out), but have not encountered a single Hullbreaker. Everything else spawns perfectly fine, there are no caves nearby where it could have spawned, and the ones that are nearby around the biome I have lit up with sea lanterns. 
Yes, I do have some other mods installed, but it looks like the hullbreaker is the only creature from alex's mobs that refuses to spawn naturally. 
All other cave biomes spawn their respective mobs perfectly fine too. 
There are no spawn weights to temper with for alex's caves, so I can't really change anything to increase the chances. 
But could spawn weights then become an eventual feature in the future? 

Amazing mod all things considered, really enjoying it so far. 
Great work!

**Comment by AlexModGuy** [comment]
spawn rates can be changed via datapack. replace
data/alexscaves/worldgen/biome/abyssal_chasm.json with a new copy, where
https://github.com/AlexModGuy/AlexsCaves/blob/main/src/main/resources/data/alexscaves/worldgen/biome/abyssal_chasm.json#L186
weight is set to something higher than 2, like 10 or 100, all depends on what you want.

**Comment by DigitalWendigo** [comment]
Found it! 
Thanks a bunch!
