### ISSUE TITLE
Tremorzilla big beam attack disconnects on multiplayer worlds

### ISSUE THREAD

**Issue by CountBlumiere** [AlexModGuy/AlexsCaves#895]
Big beam from tremorzilla makes server go boom.

not sure how to even post a log because the latest log just shows server disconnect, maybe posting the java code could help

![Screenshot 2024-02-29 160109](https://github.com/AlexModGuy/AlexsCaves/assets/161390979/5bd32df5-1b46-4303-9c5f-1530e611b2fa)

it does this whether or not we fire the laser or he does it himself, any fix for it?

**Comment by AlexModGuy** [comment]
post the debug log and the latest log

esp from the client

**Comment by CountBlumiere** [comment]
https://pastebin.pl/view/8fc495e2 heres the latest.log
https://pastebin.pl/view/0a541183 and heres the debug log both from client they both say the same thing

**Comment by AlexModGuy** [comment]
both of these logs are unbelievably tiny, even starting my game as a client produces a larger latest.log, filled with ModDiscoverer logs and other things being printed out. Are you using some sort of mod that truncates logging?

**Comment by CountBlumiere** [comment]
[latest.log](https://github.com/AlexModGuy/AlexsCaves/files/14463930/latest.log)

heres the latest.log i think the debug is too large
