### ISSUE TITLE
[Suggestion] Galena Gauntlet compatibility with modded weapons and tools. 

### ISSUE THREAD

**Issue by DigitalWendigo** [AlexModGuy/AlexsCaves#896]
There are some incompatibilities with modded weapons and tools. 
I'm not sure exactly what the issue may be, as I am neither a coder or modder, but if I had to guess, I'd say it might be something related to tags. 
The Galena Gauntlet works perfectly with vanilla weapons and tools, especially with the Crystal enchantment. 
But for modded weapons, even those made of a material like Steel, or for another example, Born In Chaos's Dark Metal, the galena gauntlet won't do anything with them. 
Currently tested with Mekanism's Steel, Refined Obsidian, and other materials, including Born In Chaos's various Dark Metal weapons, and the tools and weapons from the mod Gobber. (Because, 3x3 hammers are nice.) 
It would be quite useful to see some compatibility in the future. 
Again, since I'm neither a coder or modder, I have no idea how difficult this request might be, so I apologize if I'm asking the impossible. 

Once more, cheers for the amazing mod!

**Comment by AlexModGuy** [comment]
add metal items to the alexscaves:ferromagnetic_items tag and crystal items to alexscaves:galena_gauntlet_crystallization_items tag.

**Comment by DigitalWendigo** [comment]
May I ask what the order of folder locations should be? 
I've managed to make a data pack with correct item id's, for both the .json files you mentioned. (Found them in the Alex's caves .jar file). 
But, it does not seem to work.

**Comment by DigitalWendigo** [comment]
Currently added it in the following order of folders. 
[datapack name]->data->alexcaves->tags->items->

**Comment by DigitalWendigo** [comment]
[latest.log](https://github.com/AlexModGuy/AlexsCaves/files/14459893/latest.log)
Currently getting this in the log messages. 
I have no idea what I'm doing wrong. 

These are the edited files. 
[ferromagnetic_items.json](https://github.com/AlexModGuy/AlexsCaves/files/14459896/ferromagnetic_items.json)
[galena_gauntlet_crystallization_items.json](https://github.com/AlexModGuy/AlexsCaves/files/14459897/galena_gauntlet_crystallization_items.json)

**Comment by DigitalWendigo** [comment]
Nevermind! 
I am an actual idiot. 
Fixed it.
