### ISSUE TITLE
Hologram of players Causes Disconnects on Servers

### ISSUE THREAD

**Issue by MyUserNameIsVeryBad** [AlexModGuy/AlexsCaves#903]
Simply by having a hologramm of a player nearby to another causes a disconnect With a nbt error message

**Comment by MyUserNameIsVeryBad** [comment]
Something around the lines of "Nbt too large" and allocating bytes

**Comment by MyUserNameIsVeryBad** [comment]
"Internal Exeption: io.netty.handler.codec.decoderExeption: java.lang.runtimeExeption: Tried to read nbt tag that was too big: tried to allocate: 2097154bytes where max allowed:2097152" is the disconnect message

**Comment by AlexModGuy** [comment]
fix in the next update will require you destroying the current projectors, just fyi
