### ISSUE TITLE
Endermen spawns in Abyssal Caves causing massive fps drops and server crashes

### ISSUE THREAD

**Issue by Cent38jrjiawfiadfjidaf** [AlexModGuy/AlexsCaves#904]
[crash-2024-03-02_03.07.50-server.txt](https://github.com/AlexModGuy/AlexsCaves/files/14465536/crash-2024-03-02_03.07.50-server.txt)

This is a server me and my friends have set up and when trying to explore Abyssal Caves (we are still at the surface and haven't even attempted to go down) it would cause massive fps drops to everyone and would inevitably crash the server everytime. When we are far away from it or inside the other caves in the mod, the server runs very smooth, its just that the Abyssal Cave biome may possibly be causing this. I've tried locating and loading Abyssal Caves in a singleplayer creative world and something similar still happens.

**Comment by AlexModGuy** [comment]
server is being dragged by an Enderman (which cant move in water) stepping on an uknown block (logs stopped at block.stepOn). Given that the only blocks in Alex's Caves that implement this method are the dinosaur eggs and primal magma, I suspect this is a compatiblity issue with another mod, likely something adding more oceanic generation blocks

**Comment by Cent38jrjiawfiadfjidaf** [comment]
may I ask, if I use the InControl mod to totally disable Enderman spawns, would it solve the problem or I need to find that specific block that is causing the conflict?

**Comment by AlexModGuy** [comment]
I would say its more likely the block interaction consuming these ticks, but I can't be sure.

**Comment by Cent38jrjiawfiadfjidaf** [comment]
Making endermen not spawn anymore actually worked and the abyssal chasm is now smoothly working on our server. The block is probably the more sane and better choice as making an entity like Enderman be deleted from the overworld is a bit too extreme to do but we decided if we ever needed that mob, we will just go to either nether or end. Thanks for the help and we are loving the mod!

**Comment by AlexModGuy** [comment]
Yeah, I'll make sure to remove endermen spawn pools from this biome in the next update since it doesnt make much sense anyways.
