### ISSUE TITLE
Boats, Minecarts, Magnetic Quarry Smashers and Submarines can all be linked with a Holocoder.

### ISSUE THREAD

**Issue by KillyaSelf101** [AlexModGuy/AlexsCaves#905]
Despite armor stands and other unalive entities not being interactable with holocoders - boats, minecarts, magnetic quarry smashers and submarines can all be binded to a holocoder.

Their holograms on a hologram projector display nothing.

**Comment by AlexModGuy** [comment]
fixed in 1.1.3
