### ISSUE TITLE
Biome Maps not generating

### ISSUE THREAD

**Issue by TeaAxolotl** [AlexModGuy/AlexsCaves#909]
I've created three biome maps so far (Primordial, Abyssal & Toxic) and none of them have generated. They're stuck in the loading animation, and don't generate while in my inventory or in a chest. This has happened on multiple of my worlds, which forced me to either make a new world or just find the biomes by chance. Is this a known issue, or perhaps there's a conflict in my mod list? Thank you in advance.

**Comment by AlexModGuy** [comment]
dont put them in a chest. the entire system works by taking advantage of player ticking to find the map when it's all done.
If the maps arent working you should see if /locate works. If it isnt, checkout similar issues like #327

**Comment by AlexModGuy** [comment]
* delete configs if you updated from < 1.0.9. Also ensure that you arent using world gen mods like #108 that conflict with AC generation
