### ISSUE TITLE
Vallumraptors eat their own eggs

### ISSUE THREAD

**Issue by joebobthethird** [AlexModGuy/AlexsCaves#921]
If you happen to drop a vallumraptor egg near a vallumraptor, it will eat the egg. TBH this might not be a bug but i figured these guys weren't into cannibalism by default so I reported it.

**Comment by PCAwesomeness** [comment]
Vallumraptors are coded to steal and eat all eggs by default. Vallumraptor eggs are part of that registry (probably just to allow for better compatibility with other mods in general), so all that's left is putting two and two together.

Carnivorous dinosaurs engaged in plenty of cannibalism in their lives, anyway.
