### ISSUE TITLE
Tremorzilla has no food item to heal it.

### ISSUE THREAD

**Issue by pantsguyapp** [AlexModGuy/AlexsCaves#922]
I know this thing heal over time but I want to have a food item of some sort to instantly heal it. Feeding waste drums to tamed tremorzilla to heal it seems like a good idea.

**Comment by PCAwesomeness** [comment]
Shoot it with a raygun or blow it up with a nuke.

https://alexscaves.wiki.gg/wiki/Tremorzilla#Behavior

**Comment by pantsguyapp** [comment]
I don't see any food items that will heal the zilla in the list though.

**Comment by PCAwesomeness** [comment]
That's because you shoot it with a raygun or blow it up with a nuke instead :)

**Comment by pantsguyapp** [comment]
What about feeding it with waste drums to heal it?

**Comment by JustAnotherBugReporter** [comment]
Not needed due to having other ways of healing.

**Comment by pantsguyapp** [comment]
Sad.

**Comment by pantsguyapp** [comment]
Does the gamma raygun heal it even more?
