### ISSUE TITLE
Feeding relicheirus primordial soup doesn't give achievement

### ISSUE THREAD

**Issue by joebobthethird** [AlexModGuy/AlexsCaves#926]
I've tried it twice now, and they certainly ate the soup and rampaged, but i got no achievement.

**Comment by AlexModGuy** [comment]
![2024-03-03_10 16 53](https://github.com/AlexModGuy/AlexsCaves/assets/8662109/ad4d816b-2b78-400a-b5cb-f40bc87edb5b)
not able to replicate in 1.1.3.
