### ISSUE TITLE
World stops loading before the caves.

### ISSUE THREAD

**Issue by NotAPotter** [AlexModGuy/AlexsCaves#93]
Trying to get to a cave via following a map leads to a world freezing up all processes and the world stopping at an edge abruptly. I can still move, but basically nothing else.

**Comment by AlexModGuy** [comment]
mod list?

**Comment by NotAPotter** [comment]
![Mod List](https://github.com/AlexModGuy/AlexsCaves/assets/80670323/fd303660-d4df-4825-9b49-fac54b9a371f)
Hope this picture will do.

**Comment by NotAPotter** [comment]
I also have the Manic Datapack loaded, if that helps.

**Comment by Turtl21** [comment]
I have the same exact issue with my game but it also happens whenever I find a cave or anything but as soon as i removed the mod i was fine

**Comment by NotAPotter** [comment]
Resolved as of latest update. Thank you for your hard work.
