### ISSUE TITLE
Map crash on server after update

### ISSUE THREAD

**Issue by Jaeric217** [AlexModGuy/AlexsCaves#930]
I updated Alex's Caves on my server from 1.1.2 to 1.1.3 and now the item cave_map crashes the client any time the player opens their inventory or a chest with that item, it also crashes if searched for in the creative menu. The error reads "Registry Object not present: alexscaves:cave_map_inventory". This crash does not happen in single player.

I can temporarily fix the problem by using commands to remove the item from the player's inventory or from the chest containing the item.

[crash-2024-03-03_16.00.22-client.txt](https://github.com/AlexModGuy/AlexsCaves/files/14475285/crash-2024-03-03_16.00.22-client.txt)

**Comment by AlexModGuy** [comment]
this looks to be a version mismatch, but the log says that the mod is up to date. does this happen on single player 1.1.3?

**Comment by Jaeric217** [comment]
> this looks to be a version mismatch, but the log says that the mod is up to date. does this happen on single player 1.1.3?

You just helped me realize I forgot to update the mod on the server. My bad. 
The problem has been resolved. Thank you.
