### ISSUE TITLE
When Alex's Caves is installed, Lava vision potion from Alex's mobs isnt function.

### ISSUE THREAD

**Issue by ByrneShaw** [AlexModGuy/AlexsCaves#931]
Only three mods：
citadel-2.5.4
alexsmobs-1.22.7
alexscaves-1.1.3

But when I deleted alexscaves or disable fog from alexscaves, it worked again, apparently it's a problem with alexscaves, I know fog issue fixed the  in alexscaves 1.1.3, but apparently the fix failed!

**Comment by AlexModGuy** [comment]
will be fixed in the next AM release.
