### ISSUE TITLE
Undead Mobs Appear in Primordial Caves

### ISSUE THREAD

**Issue by Kaise7** [AlexModGuy/AlexsCaves#932]
Undead appear in Primordial Caves (when using undead mod)
As:
- CrimsonSteve's more mobs
- THE UNDEAD RENEWED
At first I thought it was a bug with the mods so I uninstalled them but I've been testing them and it seems like there's something causing them to appear en masse in the primordial caves (undead mobs only).

**Comment by JustAnotherBugReporter** [comment]
Do you have TACT?

**Comment by Kaise7** [comment]
I'm sorry I do not understand

**Comment by AlexModGuy** [comment]
Remove TACT mod

**Comment by Kaise7** [comment]
No tengo el mod TACT
