### ISSUE TITLE
Undead Mobs Appear in Primordial Caves

### ISSUE THREAD

**Issue by Kaise7** [AlexModGuy/AlexsCaves#935]
The undead appear in the Primordial Caves.

It seems that there is something that makes the Undead appear in large quantities, I attach images and the mods I used.

![2024-03-04_13 01 05](https://github.com/AlexModGuy/AlexsCaves/assets/160568728/973d69d4-ff39-480f-8ef4-e526300ec68b)
![2024-03-04_13 01 18](https://github.com/AlexModGuy/AlexsCaves/assets/160568728/3db66b0c-5aa4-46b9-bad6-19dc92c87049)
![2024-03-04_13 01 26](https://github.com/AlexModGuy/AlexsCaves/assets/160568728/bf31c362-66b0-4fad-9598-0ba486496bbc)
![2024-03-04_13 01 44](https://github.com/AlexModGuy/AlexsCaves/assets/160568728/57fb1ad0-178c-4f29-b32c-6060642609ae)
![2024-03-04_13 12 11](https://github.com/AlexModGuy/AlexsCaves/assets/160568728/60410175-3ccc-4fd6-8e1c-a170a506f8db)
![2024-03-04_13 12 16](https://github.com/AlexModGuy/AlexsCaves/assets/160568728/7d134646-4c46-4547-a2a1-78e6cbe76c02)
![2024-03-04_13 13 22](https://github.com/AlexModGuy/AlexsCaves/assets/160568728/2fbc5c23-e128-499d-8f54-19ed5ad7b4a7)
![2024-03-04_13 14 02](https://github.com/AlexModGuy/AlexsCaves/assets/160568728/b8702870-1a3d-4cf8-8001-20ffcd7d8ed8)
![2024-03-04_13 14 10](https://github.com/AlexModGuy/AlexsCaves/assets/160568728/fa1be8fd-71d9-4af1-b197-0b6f0e6a7caa)
![2024-03-04_13 14 41](https://github.com/AlexModGuy/AlexsCaves/assets/160568728/278b3bda-49fd-457f-9403-4e42a36eb518)
![2024-03-04_13 14 49](https://github.com/AlexModGuy/AlexsCaves/assets/160568728/0de7c745-fa33-4aea-85b1-8ef11df5ce33)
![2024-03-04_13 15 14](https://github.com/AlexModGuy/AlexsCaves/assets/160568728/3f97bf49-3610-48aa-81bb-5ead9973729e)
![2024-03-04_13 15 32](https://github.com/AlexModGuy/AlexsCaves/assets/160568728/479edf57-9959-46c3-b3f6-9b40240c162f)
![2024-03-04_13 15 33](https://github.com/AlexModGuy/AlexsCaves/assets/160568728/3e116bec-3f92-4668-80bd-85f927d9e84c)
![2024-03-04_13 15 52](https://github.com/AlexModGuy/AlexsCaves/assets/160568728/537ddf7e-23f7-49d0-8f05-701f13dd84de)
![Captura de pantalla 2024-03-04 165247](https://github.com/AlexModGuy/AlexsCaves/assets/160568728/f4023843-be6c-46bb-ab98-571e3f786f62)

**Comment by AlexModGuy** [comment]
bug with the undead revamped. they should not be spawning zombies in every biome.
