### ISSUE TITLE
InventoryPets Hood and Cloak of Darkness incompatibiltiy 

### ISSUE THREAD

**Issue by TopHatSerpent2020** [AlexModGuy/AlexsCaves#937]
So I discovered that the Hood and Cloak of darkness don't work when Inventory Pets is installed, like when i try to fly with the armor pieces it changes my screen and it seems like its working but i'm not able to fly.

**Comment by AlexModGuy** [comment]
Looks like an issue on their end https://github.com/capnkirok/Inventory-Pets/issues/587

**Comment by AlexModGuy** [comment]
https://github.com/capnkirok/Inventory-Pets/issues/584

**Comment by capnkirok** [comment]
> Looks like an issue on their end [capnkirok/Inventory-Pets#587](https://github.com/capnkirok/Inventory-Pets/issues/587)

Not related to spectator mode at all, so this is not accurate. The second link is correct (#584).
