### ISSUE TITLE
Config Suggestion

### ISSUE THREAD

**Issue by FietDit** [AlexModGuy/AlexsCaves#94]
Add a config feature that can disables each caves features to the game ex: Primordial, Abyssal, Toxic, etc. this might help people to reduce their lag on the game

[THUS, IF THIS POSSIBLE]

**Comment by AlexModGuy** [comment]
already in. each cave can be disabled in its respective config generation file

**Comment by FietDit** [comment]
> already in. each cave can be disabled in its respective config generation file

what about the features tho?
