### ISSUE TITLE
desolate dagger crash

### ISSUE THREAD

**Issue by nameedo** [AlexModGuy/AlexsCaves#947]
mod version: 1.1.4
 
when a mob dies by desolate daggers ghostly attacks the game crashes

this issue doesnt happen with the mod on its own, its some compat issue

latest log:
https://pastebin.com/raw/un01LP8B

edit: for some reason this doesnt happen to l_enders cataclysm bosses

**Comment by AlexModGuy** [comment]
> Caused by: java.lang.ClassCastException: class com.github.alexmodguy.alexscaves.server.entity.item.DesolateDaggerEntity cannot be cast to class com.minecraftserverzone.cotw.LivingEntityModifier (com.github.alexmodguy.alexscaves.server.entity.item.DesolateDaggerEntity is in module alexscaves@1.1.4 of loader 'TRANSFORMER' @5820070c; com.minecraftserverzone.cotw.LivingEntityModifier is in module cotw@1.0.0 of loader 'TRANSFORMER' @5820070c)

crash is caused by cotw mod. They should check if an entity belongs to a class before haphazardly casting it!
