### ISSUE TITLE
Magnetic Caves items crash

### ISSUE THREAD

**Issue by Smoker120900** [AlexModGuy/AlexsCaves#95]
[crash-2023-10-19_18.51.34-client.txt](https://github.com/AlexModGuy/AlexsCaves/files/13048050/crash-2023-10-19_18.51.34-client.txt)

https://github.com/AlexModGuy/AlexsCaves/assets/132844781/6b45d183-da9e-41a5-b363-436896253609

Any idea of what could be causing this?? (only happens with the Magnetic Caves tab)

**Comment by AlexModGuy** [comment]
update to 1.0.3
