### ISSUE TITLE
[BUG] The quarry from Alex's Caves ignores the durability of blocks and their tag: unbreakeable

### ISSUE THREAD

**Issue by kitovoi111** [AlexModGuy/AlexsCaves#952]
I have the Lootr and Spawners Unbreakeable mod installed where neither explosions nor breaking can break these blocks, but your quarry breaks everything, it does not check whether the block can be broken or not. It would be cool to add a list of tag blocks that the quarry cannot break.

**Comment by TelepathicGrunt** [comment]
Quarry seems to be only checking `alexscaves:unmovable` tag which holds only `#minecraft:wither_immune` tag. 
![image](https://github.com/AlexModGuy/AlexsCaves/assets/40846040/21275ee1-bc4a-43d6-8225-02fea3e13d26)

Some blocks have durability set in ways to signal unbreakable. I think `-1`? There's no tag named unbreakable as far as I know. I think adding a check to Quarry code for negative strength should do it. 
![image](https://github.com/AlexModGuy/AlexsCaves/assets/40846040/5930b928-8fe7-4d74-b207-88c2efe003e7)
