### ISSUE TITLE
Magnetic Quarry smasher cant be picked up after its finished at bedrock for re-use

### ISSUE THREAD

**Issue by tatertotman12** [AlexModGuy/AlexsCaves#954]
The issue is all in the title, I set several quarry smashers out to hit bedrock level and when  go to break them I only get a Neodinium ingot, no heavyweight and its destroyed forever. Is there a different way to pick this up or is this a bug?

**Comment by KillyaSelf101** [comment]
This is intentional

**Comment by tatertotman12** [comment]
If it is intentional would there be any way to configure the settings so as to have them be reusable, Im using these as a substitute for buildcraft quarries cause theyre even better

**Comment by AlexModGuy** [comment]
nope, intentional. craft another one
