### ISSUE TITLE
WT# with the cave maps? :(

### ISSUE THREAD

**Issue by Vinzound** [AlexModGuy/AlexsCaves#961]
Occasionally the maps incorrectly locate areas where the cave biome is not really there, for example in the screenshot I show how the map places me in an area where the Magnetic Caves are supposedly located, when the Forlorn Hollows are clearly located due to the guano blocks on the surface. (this last one may be a bug too, but I personally like how the guano looks on the surface of the overworld).

![image](https://github.com/AlexModGuy/AlexsCaves/assets/144878239/a6bd2e89-c7ca-43ca-8000-b7e574521a79)

**Comment by JustAnotherBugReporter** [comment]
Stand in the center of the map for 30 seconds to regenerate it.

**Comment by AlexModGuy** [comment]
^

**Comment by Vinzound** [comment]
Got it.
