### ISSUE TITLE
Toxic paste should be edible

### ISSUE THREAD

**Issue by pantsguyapp** [AlexModGuy/AlexsCaves#969]
Roaches' guts should be edible imo, sure you get poisoned and irradiated from consuming such a nasty thing but people should be able to eat it if they want to

**Comment by emeraldragon10005** [comment]
Next up: guano should be edible

**Comment by pantsguyapp** [comment]
> Next up: guano should be edible

Umm... no... they are literally defecation, I only suggest this because vanilla has edible spider eye, could be something fun if you are boring enough or maybe in need of some urgent foods.
