### ISSUE TITLE
Rendering entity crash to desktop

### ISSUE THREAD

**Issue by emeraldragon10005** [AlexModGuy/AlexsCaves#970]
Playing on a server, Primordial caves crash specifically. So far Grottoceratops and the pterodactyl have had this problem, i dont know if there are more. It's some sort of rendering issue. Playing on 1.1.4 mod and 1.20.1 minecraft

[crash-2024-03-11_06.06.48-client.txt](https://github.com/AlexModGuy/AlexsCaves/files/14556852/crash-2024-03-11_06.06.48-client.txt)

**Comment by AlexModGuy** [comment]
dupe #806
