### ISSUE TITLE
Entity Collision Loop, server crash

### ISSUE THREAD

**Issue by euquinox** [AlexModGuy/AlexsCaves#971]
hi! apparently some entity from the mod is crashing the server, happpened multiple times
I wonder if it is a conflict with another mod or is it an issue on your side?

[crash-2024-03-11_11.06.11-server.txt](https://github.com/AlexModGuy/AlexsCaves/files/14557596/crash-2024-03-11_11.06.11-server.txt)

**Comment by kitovoi111** [comment]
Lithium in Forge??

**Comment by kitovoi111** [comment]
Don't use Radium

Try mod Canary.

**Comment by AlexModGuy** [comment]
> 	at me.jellysquid.mods.lithium.common.entity.movement.ChunkAwareBlockCollisionSweeper.nextSection(ChunkAwareBlockCollisionSweeper.java:133) ~[radium-mc1.20.1-0.12.2%252bgit.5f80f74.jar%23384!/:?] {re:classloading}
