### ISSUE TITLE
[LAG] CaveBiomeMapWorldWorker low TPS server

### ISSUE THREAD

**Issue by kitovoi111** [AlexModGuy/AlexsCaves#972]
Spark: https://spark.lucko.me/FOydBxq3Y8

**Comment by AlexModGuy** [comment]
Looks like com.teamabnormals.blueprint.common.world.modification.ModdedBiomeSource.getNoiseBiome is causing serious overhead to the cave biome search function. Maybe report this to blueprint repo as well?

**Comment by kitovoi111** [comment]
> Looks like com.teamabnormals.blueprint.common.world.modification.ModdedBiomeSource.getNoiseBiome is causing serious overhead to the cave biome search function. Maybe report this to blueprint repo as well?

ok

**Comment by SmellyModder** [comment]
Explanation here (based on what I can tell):
https://github.com/team-abnormals/blueprint/issues/227
