### ISSUE TITLE
Acid Radrock does not drip in general.

### ISSUE THREAD

**Issue by vinicius1232426** [AlexModGuy/AlexsCaves#973]
By following what the book said, I tried making a sulfur farm, but when plancing the acid radrock and acid with the dripstone on the bottom of the block, the acid did not drip from the dripstone, at least visualy.
![2024-03-12_18 52 11](https://github.com/AlexModGuy/AlexsCaves/assets/149189835/d3bea6a4-76b9-4c2a-ac47-6caf4c4b81c2)
![2024-03-12_18 52 07](https://github.com/AlexModGuy/AlexsCaves/assets/149189835/04b92e0e-67f5-417d-a051-e163cb4b44c6)

**Comment by Mrwerebear** [comment]
Acid radrock drips on its own, no dripstone required. It will take a while for sulfur crystals to grow though, it's a slow process.

**Comment by vinicius1232426** [comment]
thank you I will see if that works
