### ISSUE TITLE
error during loading mods

### ISSUE THREAD

**Issue by PoToPeTou213** [AlexModGuy/AlexsCaves#980]
when I launch my minecraft forge the loading goes well then when I have to load the mods there is an error during loading which comes from the alexs caves mod version 1.1.4 do you know why it does this to me?

**Comment by AlexModGuy** [comment]
no log?

**Comment by 1GamingFox** [comment]
I'm having the same problem and I have an error log
[crash-2024-03-17_06.04.23-client.txt](https://github.com/AlexModGuy/AlexsCaves/files/14627034/crash-2024-03-17_06.04.23-client.txt)

**Comment by 1GamingFox** [comment]
I just got it to work but I'm not sure how...

**Comment by AlexModGuy** [comment]
shcm.shsupercm.forge.citresewn.CITResewn 

shsupercm? Citreswen? idk what this is but its not my mod and its whats crashing your server

**Comment by 1GamingFox** [comment]
I see, thank you for the help
