### ISSUE TITLE
[Bug] If you summon a villager-type mob with a hologram projector, it looks strange when viewed from above or below.

### ISSUE THREAD

**Issue by tankplanelaserkoala** [AlexModGuy/AlexsCaves#981]
mod version : 1.1.4
 
citadel version : 2.5.4

forge version : 47.2.20

The Illager is not included in this.

![image](https://github.com/AlexModGuy/AlexsCaves/assets/157739795/8e468b41-4e7c-4c5d-be81-04f9c9eb1275)

![image](https://github.com/AlexModGuy/AlexsCaves/assets/157739795/3a727aac-4e2f-4637-8188-10b102aaa989)
![image](https://github.com/AlexModGuy/AlexsCaves/assets/157739795/b0e30359-c21c-45e4-b79e-afe14d597421)
![image](https://github.com/AlexModGuy/AlexsCaves/assets/157739795/168c2681-e06c-46f9-a4b9-a9457fd24d9c)

**Comment by AlexModGuy** [comment]
#992
