### ISSUE TITLE
[Bug] If you display a stray on the hologram projector, you can’t see the stray’s rags.

### ISSUE THREAD

**Issue by tankplanelaserkoala** [AlexModGuy/AlexsCaves#982]
mod version : 1.1.4
 
citadel version : 2.5.4

forge version : 47.2.20

![image](https://github.com/AlexModGuy/AlexsCaves/assets/157739795/67644573-0912-43cf-a76b-e9fafe183abe)

**Comment by AlexModGuy** [comment]
#992
