### ISSUE TITLE
[Bug] If you display a snow golem wearing a pumpkin on the hologram projector, it does not appear with the pumpkin on.

### ISSUE THREAD

**Issue by tankplanelaserkoala** [AlexModGuy/AlexsCaves#983]
mod version : 1.1.4
 
citadel version : 2.5.4

forge version : 47.2.20

![image](https://github.com/AlexModGuy/AlexsCaves/assets/157739795/ccd7b9b8-6a69-48e5-b478-553c438a7c21)

**Comment by AlexModGuy** [comment]
#992
