### ISSUE TITLE
[Bug] If you display some large mobs on the hologram projector, they appear at the bottom of the hologram projector.

### ISSUE THREAD

**Issue by tankplanelaserkoala** [AlexModGuy/AlexsCaves#984]
mod version : 1.1.4
 
citadel version : 2.5.4

forge version : 47.2.20

![image](https://github.com/AlexModGuy/AlexsCaves/assets/157739795/4d5e5761-a4d9-45ef-b9a5-d100cc98f399)

![image](https://github.com/AlexModGuy/AlexsCaves/assets/157739795/de4a7f2c-7299-4a94-803d-21563a06631d)

**Comment by AlexModGuy** [comment]
#992
