### ISSUE TITLE
[Bug] If you display a mob with a translucent part on the hologram projector, the translucent part is not visible.

### ISSUE THREAD

**Issue by tankplanelaserkoala** [AlexModGuy/AlexsCaves#985]
mod version : 1.1.4
 
citadel version : 2.5.4

forge version : 47.2.20

![image](https://github.com/AlexModGuy/AlexsCaves/assets/157739795/b71a957a-3e71-467e-9c57-cb0e920c7126)

**Comment by AlexModGuy** [comment]
#992
