### ISSUE TITLE
[Bug] Graphic errors occur when a mob with a thin texture is displayed as a hologram.

### ISSUE THREAD

**Issue by tankplanelaserkoala** [AlexModGuy/AlexsCaves#986]
mod version : 1.1.4
 
citadel version : 2.5.4

forge version : 47.2.20

Other mobs with thin parts will experience the same phenomenon.

![image](https://github.com/AlexModGuy/AlexsCaves/assets/157739795/ba9099a1-1929-4661-a570-fce34f687874)

![image](https://github.com/AlexModGuy/AlexsCaves/assets/157739795/966a74ba-4ece-42f6-bace-83c8c2928c5a)

![image](https://github.com/AlexModGuy/AlexsCaves/assets/157739795/54267d72-e30b-4d06-9b22-dcd1f0f312fe)

![image](https://github.com/AlexModGuy/AlexsCaves/assets/157739795/7071a73c-9084-4341-a783-3d8b638c5885)

![image](https://github.com/AlexModGuy/AlexsCaves/assets/157739795/a703dbb2-573d-44b3-9cff-e8a206426a0a)

**Comment by AlexModGuy** [comment]
#992
