### ISSUE TITLE
Vanilla mobs spawning in toxic caves

### ISSUE THREAD

**Issue by shrekgamer69** [AlexModGuy/AlexsCaves#990]
On my brother's server there's vanilla mobs spawning in the toxic caves, and I'm not sure which one of my mods are causing this.
![image](https://github.com/AlexModGuy/AlexsCaves/assets/163710025/3ceea59e-144d-4382-be9c-a8c64dfbab8e)
![image](https://github.com/AlexModGuy/AlexsCaves/assets/163710025/ffe6b3f7-ce23-4fd1-8dfb-14e3fec61a58)

**Comment by AlexModGuy** [comment]
intentional
