### ISSUE TITLE
[Bug] If there is a hologram behind the Peering Coprolith, it seems to be passed through.

### ISSUE THREAD

**Issue by tankplanelaserkoala** [AlexModGuy/AlexsCaves#991]
mod version : 1.1.4

citadel version : 2.5.4

forge version : 47.2.20

![image](https://github.com/AlexModGuy/AlexsCaves/assets/157739795/d02142c7-e91c-4b7a-b9a3-21a04f7a5dbf)

I thought it was because of the Embedium, but it remains the same even without the Embedium mode.

![image](https://github.com/AlexModGuy/AlexsCaves/assets/157739795/330a8a11-93ce-412e-b20d-8a6bb06c4da1)

**Comment by AlexModGuy** [comment]
#992
