### ISSUE TITLE
Timed out Server when entering or being near an unresearched Cave

### ISSUE THREAD

**Issue by Aeroki** [AlexModGuy/AlexsCaves#995]
On my server we have a Primordial Cave near the spawn. One of our players stumbled upon it and the server just stops responding. Kicks everyone off but continues to stay online saying everyone is still connected. There is no crash report, but a simple restart will fix the issue at the cost of rolling back a few minuets before they got close to the cave. We believe it to be a result of not either having a map to the cave or research on the cave before entering. I tested it in Singleplayer and after crafting the map I entered the cave no issues. On the server this particular player made a map and found a Forlorn cave with no issues, but something about entering the primordial cave without having a map/research essentially crashes the server.

**Comment by JustAnotherBugReporter** [comment]
This should not happen, what is your modlist, also crash log?

**Comment by Aeroki** [comment]
I am so sorry! I forgot to close this! It turns out it had something to do with a Dungeons and Taverns mod? I guess the structure was above the cave. but after the removal it worked fine! There was no crash report so it was trial and error to fix.
